import { readdirSync, readFileSync, statSync } from 'fs';
import { join } from 'path';

import { Tool } from '../../../entities/tool.entity';
import { computeToolHash, computeToolHashWithoutClass, verifyToolIntegrity } from '../../../common/security/tool-integrity';
import { ToolSideEffectClass1750813799000 } from '../../../migrations/1750813799000-ToolSideEffectClass';

/**
 * Where the side-effect class lives (docs/design/code-mode.md, part A):
 * computed when a tool is written, kept when a person set it, part of the
 * integrity hash, and backfilled on every existing tool.
 */
function tool(fields: Partial<Tool>): Tool {
  return Object.assign(new Tool(), {
    name: 'petstore_delete_pet',
    description: 'Delete a pet',
    parameters: { type: 'object', properties: { petId: { type: 'integer' } } },
    code: null,
    executionMethod: null,
    configuration: null,
    httpConfig: null,
    graphqlConfig: null,
    llmConfig: null,
    metadata: { sourceOperation: { method: 'DELETE' }, sourceApi: { type: 'openapi' } },
    ...fields,
  });
}

describe('the stored side-effect class', () => {
  describe('Tool.classify (the entity hook on insert and save)', () => {
    it('classifies a new tool', () => {
      const t = tool({});
      t.classify();
      expect([t.sideEffect, t.openWorld, t.sideEffectSource]).toEqual(['destructive', true, 'http_method']);
    });

    it('reclassifies a saved tool whose definition changed', () => {
      const t = tool({ id: 't-1', sideEffect: 'destructive', sideEffectSource: 'http_method', metadata: { sourceOperation: { method: 'GET' } } });
      t.classify();
      expect(t.sideEffect).toBe('read');
    });

    it('leaves the class alone on a save that did not load every column it is computed from', () => {
      const t = tool({ id: 't-1', sideEffect: 'destructive', sideEffectSource: 'http_method' });
      (t as any).metadata = undefined;
      t.classify();
      expect([t.sideEffect, t.sideEffectSource]).toEqual(['destructive', 'http_method']);
    });

    it('never recomputes a person\'s override away, even when the definition changes (re-import)', () => {
      const t = tool({ id: 't-1', sideEffect: 'read', sideEffectSource: 'override' });
      t.metadata = { sourceOperation: { method: 'DELETE' }, autoGenerated: true };
      t.classify();
      expect([t.sideEffect, t.sideEffectSource]).toEqual(['read', 'override']);
    });
  });

  describe('the integrity hash', () => {
    it('covers the class: the same definition with another class hashes differently', () => {
      const asIs = tool({});
      const overridden = tool({ sideEffect: 'read', sideEffectSource: 'override' });
      expect(computeToolHash(asIs).hash).not.toBe(computeToolHash(overridden).hash);
      expect(computeToolHash(asIs).fields).toContain('sideEffect');
    });

    it('refuses a tool whose stored class was turned from destructive to read outside its update path', () => {
      const t = tool({});
      t.classify();
      const stamped = computeToolHash(t).hash;
      Object.assign(t, { sideEffect: 'read', sideEffectSource: 'override' });
      expect(verifyToolIntegrity(t, stamped).valid).toBe(false);
    });

    it('is the same stamped before the hook runs as after', () => {
      const t = tool({});
      const before = computeToolHash(t).hash;
      t.classify();
      expect(computeToolHash(t).hash).toBe(before);
    });
  });

  describe('the migration', () => {
    function queryRunner(rows: any[]) {
      const updates: any[][] = [];
      const statements: string[] = [];
      return {
        updates,
        statements,
        query: jest.fn(async (sql: string, params?: any[]) => {
          statements.push(sql);
          if (sql.startsWith('SELECT')) return params?.[1] === 0 ? rows : [];
          if (sql.startsWith('UPDATE')) updates.push(params!);
          return [];
        }),
      };
    }

    it('classifies every tool like the hook does, copying a GraphQL operation type into the metadata', async () => {
      const rows = [
        { id: 'a', name: 'getPet', metadata: { sourceOperation: { method: 'GET' }, sourceApi: { type: 'openapi' } }, operationType: 'query' },
        { id: 'b', name: 'pets', metadata: { sourceOperation: { method: 'POST' }, sourceApi: { type: 'graphql' } }, operationType: 'query' },
        { id: 'c', name: 'ask', executionMethod: 'llm', metadata: null },
        { id: 'd', name: 'custom', executionMethod: 'custom', metadata: { sideEffect: 'destructive' } },
        { id: 'e', name: 'remote', configuration: { mcp: { annotations: { readOnlyHint: true, openWorldHint: false } } }, metadata: null },
      ];
      const qr = queryRunner(rows);
      await new ToolSideEffectClass1750813799000().up(qr as any);
      const byId = Object.fromEntries(qr.updates.map((p) => [p[0], p]));
      expect(byId.a.slice(1, 4)).toEqual(['read', true, 'http_method']);
      expect(byId.b.slice(1, 4)).toEqual(['read', true, 'graphql']);
      expect(JSON.parse(byId.b[4]).sourceOperation.type).toBe('query');
      expect(byId.c.slice(1, 4)).toEqual(['read', false, 'default']);
      expect(byId.d.slice(1, 4)).toEqual(['destructive', true, 'override']);
      expect(byId.e.slice(1, 4)).toEqual(['read', false, 'annotation']);
      expect(qr.statements.some((s) => s.includes('CHK_tools_side_effect'))).toBe(true);
    });

    it('re-stamps a hash that still held, and leaves one that did not refused', async () => {
      const intact = { id: 'ok', name: 'getPet', description: 'Get', parameters: { a: 1 }, metadata: { sourceOperation: { method: 'GET' } } };
      const tampered = { id: 'bad', name: 'deletePet', description: 'changed', parameters: {}, metadata: { sourceOperation: { method: 'DELETE' } } };
      const rows = [
        { ...intact, definitionHash: computeToolHashWithoutClass(intact as any) },
        { ...tampered, definitionHash: computeToolHashWithoutClass({ ...tampered, description: 'original' } as any) },
        { id: 'none', name: 'x', metadata: null, definitionHash: null },
      ];
      const qr = queryRunner(rows);
      await new ToolSideEffectClass1750813799000().up(qr as any);
      const byId = Object.fromEntries(qr.updates.map((p) => [p[0], p]));
      expect(byId.ok[5]).toBe(computeToolHash(intact as any).hash);
      expect(verifyToolIntegrity({ ...intact, sideEffect: 'read', sideEffectSource: 'http_method' } as any, byId.ok[5]).valid).toBe(true);
      expect(byId.bad[5]).toBe(rows[1].definitionHash);
      expect(byId.none[5]).toBeNull();
    });
  });

  describe('guards', () => {
    const SRC = join(__dirname, '../../..');
    function sources(dir: string, out: string[] = []): string[] {
      for (const name of readdirSync(dir)) {
        const path = join(dir, name);
        if (statSync(path).isDirectory()) {
          if (name === '__tests__' || name === 'migrations' || name === 'test') continue;
          sources(path, out);
        } else if (name.endsWith('.ts') && !name.endsWith('.spec.ts')) {
          out.push(path);
        }
      }
      return out;
    }

    it('no code writes tools around the classify hook (insert, upsert, query-builder insert, raw INSERT)', () => {
      const offenders: string[] = [];
      for (const file of sources(SRC)) {
        const text = readFileSync(file, 'utf8');
        if (/getRepository\(Tool\)\s*\.\s*(insert|upsert)\(|toolRepository\s*\.\s*(insert|upsert)\(|\.insert\(\)\s*\.into\(Tool\b|INSERT\s+INTO\s+"?tools"?\b/i.test(text)) {
          offenders.push(file.slice(SRC.length));
        }
      }
      expect(offenders).toEqual([]);
    });

    it('every query-builder update of tools leaves the class inputs alone', () => {
      const offenders: string[] = [];
      for (const file of sources(SRC)) {
        const text = readFileSync(file, 'utf8');
        const match = /\.update\(Tool\)\s*\.set\(\{([^}]*)\}/g;
        let m: RegExpExecArray | null;
        while ((m = match.exec(text))) {
          if (/metadata|configuration|httpConfig|graphqlConfig|llmConfig|executionMethod|sideEffect/.test(m[1])) offenders.push(file.slice(SRC.length));
        }
      }
      expect(offenders).toEqual([]);
    });
  });
});
