// Top-level docs navigation, ordered by the user journey rather than
// alphabetically: get started, build the pipeline, operate it, then reference.
export default {
  index: 'Getting Started',
  examples: 'Examples',
  'build-separator': { type: 'separator', title: 'Build' },
  tools: 'Tools',
  gateways: 'Gateways',
  agents: 'Agents',
  'agentic-loops': 'Agentic Loops',
  'llm-providers': 'AI Models',
  interfaces: 'Chat Interfaces',
  'operate-separator': { type: 'separator', title: 'Operate' },
  memory: 'Memory',
  credentials: 'Credentials',
  approvals: 'Approvals',
  organizations: 'Organizations',
  analytics: 'Analytics',
  'cost-governance': 'Cost Governance',
  compliance: 'Compliance',
  runner: 'Runners',
  referrals: 'Referrals',
  enterprise: 'Enterprise',
  'reference-separator': { type: 'separator', title: 'Reference' },
  'control-via-mcp': 'Control via MCP',
  cli: 'CLI',
  'api-reference': 'API Reference',
  'self-hosting': 'Self-Hosting',
}
