// Top-level docs navigation, ordered by the reader's journey rather than
// alphabetically: start, see what it can do, build, run it, then reference.
export default {
  index: 'Get started',
  examples: 'What you can do',
  'build-separator': { type: 'separator', title: 'Build' },
  tools: 'Tools',
  gateways: 'Gateways',
  agents: 'Agents',
  'agentic-loops': 'How agents work in loops',
  models: 'Models',
  'llm-providers': 'Connect a provider',
  channels: 'Channels',
  interfaces: 'Chat apps',
  'hosted-chat': 'Web chat',
  'operate-separator': { type: 'separator', title: 'Run it safely' },
  memory: 'Memory',
  credentials: 'Credentials',
  approvals: 'Approvals',
  organizations: 'Organizations and teams',
  analytics: 'Analytics',
  'cost-governance': 'Spending limits',
  'run-limits': 'Run limits',
  compliance: 'Compliance',
  runner: 'Runners',
  referrals: 'Referrals',
  enterprise: 'Plans and enterprise',
  'reference-separator': { type: 'separator', title: 'Reference for developers' },
  'control-via-mcp': 'Control almyty via MCP',
  cli: 'CLI',
  'api-reference': 'API reference',
  'self-hosting': 'Self-hosting',
}
