import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Generated tools stop being told apart by a sentinel creator.
 *
 * Tool generation wrote the string 'system' into `tools."createdBy"` (and
 * into the initial `tool_versions."createdBy"`), and the API privacy rules
 * matched on it to find an API's generated tools. `createdBy` is an owner
 * column that ownership rules read a user id from; 'system' named no one.
 * Generation now records the importing user (or null), and a `generated`
 * flag says what the sentinel used to.
 *
 * Existing rows: every 'system' tool, and every tool whose metadata says it
 * was auto-generated (the ones made from a private API or an MCP source
 * carry a real owner), is flagged generated; the sentinel becomes null, in
 * tools and tool versions alike. Both are varchar columns, so no cast can
 * fail on a stray value.
 */
export class ToolGeneratedFlag1750812200000 implements MigrationInterface {
  name = 'ToolGeneratedFlag1750812200000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "tools" ADD COLUMN IF NOT EXISTS "generated" boolean NOT NULL DEFAULT false
    `);
    await queryRunner.query(`
      UPDATE "tools" SET "generated" = true
       WHERE "generated" = false
         AND ("createdBy" = 'system' OR ("metadata"::jsonb ->> 'autoGenerated') = 'true')
    `);
    await queryRunner.query(`
      UPDATE "tools" SET "createdBy" = NULL WHERE "createdBy" = 'system'
    `);
    await queryRunner.query(`
      UPDATE "tool_versions" SET "createdBy" = NULL WHERE "createdBy" = 'system'
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // The flag goes; 'system' is not written back, it named no one.
    await queryRunner.query(`ALTER TABLE "tools" DROP COLUMN IF EXISTS "generated"`);
  }
}
