import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { InjectRedis } from '@nestjs-modules/ioredis';
import * as Redis from 'ioredis';

import {
  UtcpManual,
  UtcpTool,
  UtcpCallTemplate,
  UtcpAuthenticationScheme,
  UtcpParameterMapping,
  UtcpDiscoveryInfo,
  UtcpExecutionContext,
  UtcpExecutionResult,
} from './types/utcp.types';

import { Tool, ToolStatus } from '../../entities/tool.entity';
import { Api } from '../../entities/api.entity';
import { Operation } from '../../entities/operation.entity';
import { Organization } from '../../entities/organization.entity';
import { ToolsService } from '../tools/tools.service';
import { ToolExecutorService, ToolExecutionResult } from '../tools/tool-executor.service';

@Injectable()
export class UtcpService {
  private readonly logger = new Logger(UtcpService.name);
  private readonly version = '1.0.0';

  constructor(
    @InjectRepository(Tool)
    private toolRepository: Repository<Tool>,
    @InjectRepository(Api)
    private apiRepository: Repository<Api>,
    @InjectRepository(Operation)
    private operationRepository: Repository<Operation>,
    @InjectRepository(Organization)
    private organizationRepository: Repository<Organization>,
    private toolsService: ToolsService,
    private toolExecutorService: ToolExecutorService,
    @InjectRedis() private readonly redis: Redis.Redis,
  ) {}

  // Generate UTCP Manual for Organization (cached + parallelized)
  async generateManual(organizationId: string): Promise<UtcpManual> {
    // Check Redis cache (5 min TTL)
    const cacheKey = `utcp:manual:${organizationId}`;
    try {
      const cached = await this.redis.get(cacheKey);
      if (cached) return JSON.parse(cached);
    } catch (e) { /* cache miss */ }

    const organization = await this.organizationRepository.findOne({
      where: { id: organizationId },
      relations: ['tools', 'apis'],
    });

    if (!organization) {
      throw new NotFoundException('Organization not found');
    }

    // Get all active tools for this organization
    const { tools } = await this.toolsService.getTools({
      organizationId,
      status: ToolStatus.ACTIVE,
    });

    // Process all tools in parallel instead of sequentially
    const toolResults = await Promise.allSettled(
      tools.map(async (tool) => {
        const [utcpTool, callTemplate, authScheme] = await Promise.all([
          this.convertToolToUtcp(tool),
          this.generateCallTemplate(tool),
          this.extractAuthenticationScheme(tool),
        ]);
        return { utcpTool, callTemplate, authScheme };
      }),
    );

    const utcpTools: UtcpTool[] = [];
    const callTemplates: UtcpCallTemplate[] = [];
    const authSchemeMap = new Map<string, UtcpAuthenticationScheme>();

    for (const r of toolResults) {
      if (r.status !== 'fulfilled') continue;
      const { utcpTool, callTemplate, authScheme } = r.value;
      utcpTools.push(utcpTool);
      if (callTemplate) callTemplates.push(callTemplate);
      if (authScheme && !authSchemeMap.has(authScheme.id)) {
        authSchemeMap.set(authScheme.id, authScheme);
      }
    }

    const manual: UtcpManual = {
      version: this.version,
      info: {
        title: `${organization.name} API Tools`,
        description: `UTCP manual for ${organization.name}'s API tools, automatically generated by almyty`,
        version: '1.0.0',
        contact: {
          name: 'almyty',
          url: 'https://almyty.com',
        },
        license: {
          name: 'Generated by almyty',
          url: 'https://almyty.com/license',
        },
      },
      tools: utcpTools,
      callTemplates,
      authentication: Array.from(authSchemeMap.values()),
      metadata: {
        generatedAt: new Date().toISOString(),
        organizationId,
        toolCount: utcpTools.length,
        apiCount: organization.apis?.length || 0,
        generator: {
          name: 'almyty',
          version: '1.0.0',
          description: 'Universal API-to-AI Tool Translation Platform',
        },
      },
    };

    // Cache for 5 minutes
    try {
      await this.redis.setex(cacheKey, 300, JSON.stringify(manual));
    } catch (e) { /* non-critical */ }

    return manual;
  }

  // Convert our Tool entity to UTCP format
  private async convertToolToUtcp(tool: Tool): Promise<UtcpTool> {
    return {
      id: tool.id,
      name: tool.name,
      description: tool.description || 'AI tool automatically generated from API operation',
      version: tool.version,
      inputSchema: tool.parameters || {
        type: 'object',
        properties: {},
      },
      outputSchema: tool.outputSchema || {
        type: 'object',
        description: 'API response data',
      },
      tags: this.extractToolTags(tool),
      examples: await this.generateToolExamples(tool),
      metadata: {
        sourceApi: tool.metadata?.sourceApi ? {
          name: tool.metadata.sourceApi.name,
          type: tool.metadata.sourceApi.type,
          endpoint: tool.metadata.sourceApi.baseUrl,
          operation: tool.metadata.sourceOperation?.name,
        } : undefined,
        performance: {
          // TODO: Get actual metrics from usage stats
          averageResponseTime: 1500,
          successRate: 0.95,
        },
        autoGenerated: tool.metadata?.autoGenerated || false,
        createdAt: tool.createdAt.toISOString(),
        updatedAt: tool.updatedAt.toISOString(),
      },
    };
  }

  // Generate call template for direct API access
  private async generateCallTemplate(tool: Tool): Promise<UtcpCallTemplate | null> {
    if (!tool.operationId) {
      return null; // Can't generate direct call template without operation
    }

    const operation = await this.operationRepository.findOne({
      where: { id: tool.operationId },
      relations: ['api'],
    });

    if (!operation || !operation.api) {
      return null;
    }

    const api = operation.api;

    return {
      id: `template_${tool.id}`,
      name: `Direct ${tool.name} Call`,
      description: `Direct API call template for ${tool.name} - bypasses almyty proxy`,
      protocol: 'http',
      endpoint: {
        url: `${api.baseUrl}${operation.endpoint}`,
        method: operation.method,
        headers: {
          'Content-Type': this.getContentType(operation),
          'User-Agent': 'almyty-utcp-client/1.0.0',
          ...api.headers,
        },
        timeout: api.timeoutMs || 30000,
        retries: api.retryAttempts || 3,
      },
      authentication: api.authentication ? {
        scheme: api.authentication.type,
        location: 'header',
        parameter: this.getAuthParameter(api.authentication),
        template: this.getAuthTemplate(api.authentication),
      } : undefined,
      requestMapping: {
        parameters: this.generateParameterMappings(operation),
        body: this.generateBodyMapping(operation),
      },
      responseMapping: {
        successCodes: [200, 201, 202, 204],
        dataPath: '$', // Root of response
        errorPath: '$.error',
      },
      rateLimit: api.rateLimits,
      metadata: {
        toolId: tool.id,
        operationId: operation.id,
        apiId: api.id,
        directAccess: true,
        bypassProxy: true,
      },
    };
  }

  // Generate parameter mappings from operation
  private generateParameterMappings(operation: Operation): Record<string, UtcpParameterMapping> {
    const mappings: Record<string, UtcpParameterMapping> = {};

    // Path parameters
    if (operation.parameters?.path) {
      Object.entries(operation.parameters.path).forEach(([name, param]: [string, any]) => {
        mappings[name] = {
          type: 'path',
          name,
          required: param.required || true,
          validation: {
            type: param.type || 'string',
            description: param.description,
          },
        };
      });
    }

    // Query parameters
    if (operation.parameters?.query) {
      Object.entries(operation.parameters.query).forEach(([name, param]: [string, any]) => {
        mappings[name] = {
          type: 'query',
          name,
          required: param.required || false,
          default: param.default,
          validation: {
            type: param.type || 'string',
            description: param.description,
          },
        };
      });
    }

    // Header parameters
    if (operation.parameters?.header) {
      Object.entries(operation.parameters.header).forEach(([name, param]: [string, any]) => {
        mappings[name] = {
          type: 'header',
          name,
          required: param.required || false,
          validation: {
            type: param.type || 'string',
            description: param.description,
          },
        };
      });
    }

    // Body parameters
    if (operation.parameters?.body) {
      Object.entries(operation.parameters.body).forEach(([name, param]: [string, any]) => {
        mappings[name] = {
          type: 'body',
          name,
          required: param.required || false,
          validation: param,
        };
      });
    }

    return mappings;
  }

  private generateBodyMapping(operation: Operation): any {
    if (!operation.parameters?.body) {
      return undefined;
    }

    return {
      contentType: this.getContentType(operation),
      template: JSON.stringify(operation.parameters.body, null, 2),
      schema: {
        type: 'object',
        properties: operation.parameters.body,
      },
    };
  }

  // Extract authentication schemes
  private async extractAuthenticationScheme(tool: Tool): Promise<UtcpAuthenticationScheme | null> {
    if (!tool.operationId) {
      return null;
    }

    const operation = await this.operationRepository.findOne({
      where: { id: tool.operationId },
      relations: ['api'],
    });

    if (!operation?.api?.authentication || operation.api.authentication.type === 'none') {
      return {
        id: 'none',
        name: 'No Authentication',
        type: 'none',
        description: 'No authentication required',
        configuration: {},
      };
    }

    const auth = operation.api.authentication;

    return {
      id: `auth_${operation.api.id}`,
      name: `${operation.api.name} Authentication`,
      type: auth.type as any,
      description: `Authentication scheme for ${operation.api.name} API`,
      configuration: {
        location: auth.config.location || 'header',
        parameter: auth.config.parameter || this.getDefaultAuthParameter(auth.type),
        scheme: auth.config.scheme || this.getDefaultAuthScheme(auth.type),
        // Do NOT spread auth.config under a `custom` key here.
        // auth.config can contain the real secret for the API —
        // apiKey, token, password, clientSecret — and the UTCP
        // manual is returned verbatim to any org member who hits
        // GET /utcp/:orgId/manual (and gets cached in Redis for
        // 5 min). Leaking full credentials to every member is a
        // privilege-escalation path. The other fields on
        // configuration (location/parameter/scheme) describe HOW
        // to authenticate, which is what UTCP consumers need; the
        // secret value itself should only be surfaced through the
        // credentials endpoints (which mask it).
      },
      examples: [
        {
          name: 'Example Usage',
          description: `How to use ${auth.type} authentication`,
          value: this.generateAuthExample(auth),
        },
      ],
    };
  }

  // Utility methods
  private extractToolTags(tool: Tool): string[] {
    const tags = ['ai-tool'];
    
    if (tool.metadata?.sourceApi?.type) {
      tags.push(tool.metadata.sourceApi.type);
    }
    
    if (tool.metadata?.autoGenerated) {
      tags.push('auto-generated');
    }
    
    return tags;
  }

  private async generateToolExamples(tool: Tool): Promise<any[]> {
    // Generate examples based on tool parameters
    const examples = [];
    
    if (tool.parameters && tool.parameters.properties) {
      const exampleInput: Record<string, any> = {};
      
      Object.entries(tool.parameters.properties).forEach(([key, schema]: [string, any]) => {
        exampleInput[key] = this.generateExampleValue(schema);
      });

      examples.push({
        name: 'Basic Usage',
        description: `Example usage of ${tool.name}`,
        input: exampleInput,
        notes: 'This example shows typical parameter values',
      });
    }
    
    return examples;
  }

  private generateExampleValue(schema: any): any {
    switch (schema.type) {
      case 'string':
        return schema.example || 'example-value';
      case 'number':
      case 'integer':
        return schema.example || 42;
      case 'boolean':
        return schema.example || true;
      case 'array':
        return schema.example || ['example-item'];
      case 'object':
        return schema.example || { key: 'value' };
      default:
        return schema.example || 'example';
    }
  }

  private getContentType(operation: Operation): string {
    switch (operation.method) {
      case 'GET':
      case 'DELETE':
        return 'application/json';
      case 'POST':
      case 'PUT':
      case 'PATCH':
        return operation.metadata?.contentType || 'application/json';
      default:
        return 'application/json';
    }
  }

  private getAuthParameter(auth: any): string {
    switch (auth.type) {
      case 'bearer':
        return 'Authorization';
      case 'basic':
        return 'Authorization';
      case 'api_key':
        return auth.config.parameter || 'X-API-Key';
      default:
        return 'Authorization';
    }
  }

  private getAuthTemplate(auth: any): string {
    switch (auth.type) {
      case 'bearer':
        return 'Bearer {token}';
      case 'basic':
        return 'Basic {credentials}';
      case 'api_key':
        return '{api_key}';
      case 'oauth2':
        return 'Bearer {access_token}';
      default:
        return '{auth_value}';
    }
  }

  private getDefaultAuthParameter(type: string): string {
    switch (type) {
      case 'bearer':
      case 'basic':
      case 'oauth2':
        return 'Authorization';
      case 'api_key':
        return 'X-API-Key';
      default:
        return 'Authorization';
    }
  }

  private getDefaultAuthScheme(type: string): string {
    switch (type) {
      case 'bearer':
        return 'Bearer';
      case 'basic':
        return 'Basic';
      case 'oauth2':
        return 'Bearer';
      default:
        return '';
    }
  }

  private generateAuthExample(auth: any): string {
    switch (auth.type) {
      case 'bearer':
        return 'Authorization: Bearer your_token_here';
      case 'basic':
        return 'Authorization: Basic base64(username:password)';
      case 'api_key':
        return `${auth.config.parameter || 'X-API-Key'}: your_api_key_here`;
      case 'oauth2':
        return 'Authorization: Bearer your_oauth_token_here';
      default:
        return 'Authentication required';
    }
  }

  // UTCP Tool Execution (Proxy Mode)
  async executeUtcpTool(
    context: UtcpExecutionContext,
    organizationId: string,
  ): Promise<UtcpExecutionResult> {
    const startTime = Date.now();

    try {
      // Execute using our existing tool executor
      const result: ToolExecutionResult = await this.toolExecutorService.executeTool(
        context.toolId,
        context.parameters,
        {
          userId: 'utcp-client',
          organizationId,
          timeout: context.options?.timeout,
          retries: context.options?.retries,
          skipCache: context.options?.skipCache,
        }
      );

      return {
        success: result.success,
        data: result.data,
        error: result.error ? {
          code: 'EXECUTION_ERROR',
          message: result.error,
          details: result.metadata,
        } : undefined,
        metadata: {
          executionTime: result.executionTime,
          toolId: context.toolId,
          callTemplateId: context.callTemplateId,
          requestId: `utcp_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          timestamp: new Date().toISOString(),
          cached: result.cached,
          retryCount: result.retryCount,
        },
      };
    } catch (error) {
      return {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: error.message,
        },
        metadata: {
          executionTime: Date.now() - startTime,
          toolId: context.toolId,
          callTemplateId: context.callTemplateId,
          requestId: `utcp_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          timestamp: new Date().toISOString(),
        },
      };
    }
  }

  // Get UTCP Discovery Information
  getDiscoveryInfo(organizationId: string): UtcpDiscoveryInfo {
    const baseUrl = process.env.BASE_URL || 'http://localhost:4000';
    
    return {
      protocol: 'utcp',
      version: this.version,
      server: {
        name: 'almyty',
        version: '1.0.0',
        description: 'Universal API-to-AI Tool Translation Platform with UTCP support',
        contact: {
          name: 'almyty',
          url: 'https://almyty.com',
        },
      },
      endpoints: {
        manual: `${baseUrl}/api/utcp/${organizationId}/manual`,
        execute: `${baseUrl}/api/utcp/${organizationId}/execute`,
        health: `${baseUrl}/api/utcp/health`,
      },
      capabilities: {
        directCalling: true,
        proxyMode: true,
        authentication: ['none', 'api_key', 'bearer', 'basic', 'oauth2'],
        protocols: ['http', 'websocket'],
        formats: ['json', 'xml', 'yaml'],
      },
      experimental: {
        almyty: {
          universalApiTranslation: true,
          supportedApiFormats: ['openapi', 'graphql', 'soap', 'protobuf'],
          autoGeneration: true,
        },
      },
    };
  }

  // Validate UTCP manual
  async validateManual(manual: UtcpManual): Promise<{
    isValid: boolean;
    errors: string[];
    warnings: string[];
  }> {
    const errors: string[] = [];
    const warnings: string[] = [];

    // Basic validation
    if (!manual.version) {
      errors.push('Manual version is required');
    }

    if (!manual.info?.title) {
      errors.push('Manual title is required');
    }

    if (!manual.tools || manual.tools.length === 0) {
      warnings.push('No tools defined in manual');
    }

    // Validate each tool
    for (const tool of manual.tools || []) {
      if (!tool.id) {
        errors.push(`Tool missing ID: ${tool.name}`);
      }
      
      if (!tool.name) {
        errors.push(`Tool missing name: ${tool.id}`);
      }
      
      if (!tool.inputSchema) {
        warnings.push(`Tool ${tool.name} missing input schema`);
      }
    }

    // Validate call templates
    for (const template of manual.callTemplates || []) {
      if (!template.id) {
        errors.push(`Call template missing ID`);
      }
      
      if (!template.endpoint?.url) {
        errors.push(`Call template ${template.id} missing endpoint URL`);
      }
    }

    return {
      isValid: errors.length === 0,
      errors,
      warnings,
    };
  }

  // Get manual for specific tool
  async getToolManual(toolId: string, organizationId: string): Promise<UtcpTool> {
    const tool = await this.toolRepository.findOne({
      where: { 
        id: toolId,
        organizationId,
      },
    });

    if (!tool) {
      throw new NotFoundException('Tool not found');
    }

    return this.convertToolToUtcp(tool);
  }
}