import { Test, TestingModule } from '@nestjs/testing';
import { Repository } from 'typeorm';
import { getRepositoryToken } from '@nestjs/typeorm';
import { UtcpService } from './utcp.service';
import { Tool, ToolStatus } from '../../entities/tool.entity';
import { Api, ApiType } from '../../entities/api.entity';
import { Operation, HttpMethod } from '../../entities/operation.entity';
import { Organization } from '../../entities/organization.entity';
import { Gateway, GatewayStatus, GatewayType } from '../../entities/gateway.entity';
import { GatewayTool } from '../../entities/gateway-tool.entity';
import { GatewayAuthType } from '../../entities/gateway-auth.entity';
import { ToolsService } from '../tools/tools.service';
import { ToolExecutorService } from '../tools/tool-executor.service';

const REDIS_TOKEN = 'default_IORedisModuleConnectionToken';

describe('UtcpService — spec compliance', () => {
  let service: UtcpService;
  let operationRepo: jest.Mocked<Repository<Operation>>;
  let organizationRepo: jest.Mocked<Repository<Organization>>;
  let gatewayToolRepo: jest.Mocked<Repository<GatewayTool>>;
  let toolsService: jest.Mocked<ToolsService>;
  let toolExecutor: jest.Mocked<ToolExecutorService>;
  let redis: { get: jest.Mock; setex: jest.Mock };

  const buildApi = (over: Partial<Api> = {}): Api => ({
    id: 'api-1',
    name: 'Open-Meteo Weather',
    type: ApiType.OPENAPI,
    baseUrl: 'https://api.open-meteo.com',
    headers: { 'X-Test-Header': 'value' },
    authentication: { type: 'none' as any, config: {} },
    ...over,
  } as any);

  const buildOperation = (over: Partial<Operation> = {}): Operation => ({
    id: 'op-1',
    method: 'GET',
    endpoint: '/v1/forecast',
    parameters: { query: { lat: { type: 'number', required: true } } },
    metadata: {},
    api: buildApi(),
    ...over,
  } as any);

  const buildTool = (over: Partial<Tool> = {}): Tool => ({
    id: 'tool-1',
    name: 'open_meteo_forecast',
    description: 'Get weather forecast',
    parameters: { type: 'object', properties: { lat: { type: 'number' } } },
    outputSchema: { type: 'object' },
    operationId: 'op-1',
    status: ToolStatus.ACTIVE,
    metadata: { sourceApi: { type: 'openapi' }, autoGenerated: true },
    ...over,
  } as any);

  const buildGateway = (over: Partial<Gateway> = {}): Gateway => ({
    id: 'gw-1',
    name: 'Test UTCP',
    type: GatewayType.UTCP,
    status: GatewayStatus.ACTIVE,
    endpoint: '/test-utcp',
    organizationId: 'org-1',
    updatedAt: new Date('2026-04-01T00:00:00Z'),
    authConfigs: [],
    ...over,
  } as any);

  beforeEach(async () => {
    redis = { get: jest.fn().mockResolvedValue(null), setex: jest.fn().mockResolvedValue('OK') };
    operationRepo = { findOne: jest.fn() } as any;
    organizationRepo = {
      findOne: jest
        .fn()
        .mockResolvedValue({ id: 'org-1', name: 'Test', updatedAt: new Date('2026-04-01T00:00:00Z') }),
    } as any;
    gatewayToolRepo = { find: jest.fn() } as any;
    toolsService = { getTools: jest.fn() } as any;
    toolExecutor = { executeTool: jest.fn() } as any;

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        UtcpService,
        { provide: getRepositoryToken(Tool), useValue: {} },
        { provide: getRepositoryToken(Api), useValue: {} },
        { provide: getRepositoryToken(Operation), useValue: operationRepo },
        { provide: getRepositoryToken(Organization), useValue: organizationRepo },
        { provide: getRepositoryToken(GatewayTool), useValue: gatewayToolRepo },
        { provide: ToolsService, useValue: toolsService },
        { provide: ToolExecutorService, useValue: toolExecutor },
        { provide: REDIS_TOKEN, useValue: redis },
      ],
    }).compile();

    service = module.get(UtcpService);
  });

  describe('generateManual — spec-compliant top-level shape', () => {
    it('uses snake_case top-level fields utcp_version, manual_version, tools', async () => {
      toolsService.getTools.mockResolvedValue({ tools: [buildTool()], total: 1 } as any);
      operationRepo.findOne.mockResolvedValue(buildOperation());

      const manual = await service.generateManual({ organizationId: 'org-1' });

      expect(manual.utcp_version).toBe('1.0.0');
      expect(typeof manual.manual_version).toBe('string');
      expect(manual.manual_version.length).toBeGreaterThan(0);
      expect(Array.isArray(manual.tools)).toBe(true);

      // No legacy/extension fields at top level — UTCP SDKs reject unknown fields.
      expect((manual as any).version).toBeUndefined();
      expect((manual as any).info).toBeUndefined();
      expect((manual as any).callTemplates).toBeUndefined();
      expect((manual as any).authentication).toBeUndefined();
      expect((manual as any).metadata).toBeUndefined();
    });

    it('scopes the manual to gateway-assigned tools when gateway is supplied', async () => {
      const tool = buildTool({ id: 'tool-assigned', name: 'assigned' });
      const otherTool = buildTool({ id: 'tool-not-assigned', name: 'leaked' });
      gatewayToolRepo.find.mockResolvedValue([{ tool, isActive: true } as any]);
      operationRepo.findOne.mockResolvedValue(buildOperation());
      // Even if global tools include a leaked one, gateway scoping must hide it
      toolsService.getTools.mockResolvedValue({ tools: [tool, otherTool], total: 2 } as any);

      const manual = await service.generateManual({
        organizationId: 'org-1',
        gateway: buildGateway(),
      });

      expect(manual.tools.map((t) => t.name)).toEqual(['assigned']);
      expect(gatewayToolRepo.find).toHaveBeenCalledWith({
        where: { gatewayId: 'gw-1', isActive: true },
        relations: ['tool'],
      });
    });
  });

  describe('UtcpTool — spec-compliant tool shape', () => {
    it('uses inputs/outputs/tool_call_template (not inputSchema/outputSchema/separate templates)', async () => {
      toolsService.getTools.mockResolvedValue({ tools: [buildTool()], total: 1 } as any);
      operationRepo.findOne.mockResolvedValue(buildOperation());

      const manual = await service.generateManual({ organizationId: 'org-1' });
      const tool = manual.tools[0];

      expect(tool.name).toBe('open_meteo_forecast');
      expect(tool.description).toBeDefined();
      expect(tool.inputs).toBeDefined();
      expect(tool.outputs).toBeDefined();
      expect(Array.isArray(tool.tags)).toBe(true);
      expect(tool.tool_call_template).toBeDefined();

      // Must NOT have extension fields on tool — these break UTCP SDK parsing.
      expect((tool as any).id).toBeUndefined();
      expect((tool as any).version).toBeUndefined();
      expect((tool as any).inputSchema).toBeUndefined();
      expect((tool as any).outputSchema).toBeUndefined();
      expect((tool as any).examples).toBeUndefined();
      expect((tool as any).metadata).toBeUndefined();
    });
  });

  describe('UtcpHttpCallTemplate — spec-compliant call template shape', () => {
    it('uses call_template_type, http_method, url (not protocol/endpoint nested)', async () => {
      toolsService.getTools.mockResolvedValue({ tools: [buildTool()], total: 1 } as any);
      operationRepo.findOne.mockResolvedValue(
        buildOperation({ method: HttpMethod.POST, endpoint: '/v1/predict' }),
      );

      const manual = await service.generateManual({ organizationId: 'org-1' });
      const tmpl = manual.tools[0].tool_call_template as any;

      expect(tmpl.call_template_type).toBe('http');
      expect(tmpl.http_method).toBe('POST');
      expect(tmpl.url).toBe('https://api.open-meteo.com/v1/predict');
      expect(tmpl.content_type).toBe('application/json');

      // No legacy nesting
      expect(tmpl.protocol).toBeUndefined();
      expect(tmpl.endpoint).toBeUndefined();
      expect(tmpl.requestMapping).toBeUndefined();
      expect(tmpl.responseMapping).toBeUndefined();
    });
  });

  describe('UtcpAuth — spec-compliant auth descriptor', () => {
    it('emits api_key auth_type with var_name + location (not the legacy {type, configuration} shape)', async () => {
      toolsService.getTools.mockResolvedValue({ tools: [buildTool()], total: 1 } as any);
      operationRepo.findOne.mockResolvedValue(
        buildOperation({
          api: buildApi({
            authentication: {
              type: 'api_key' as any,
              config: { parameter: 'X-Custom-Key', location: 'header' },
            },
          } as any),
        }),
      );

      const manual = await service.generateManual({ organizationId: 'org-1' });
      const auth = manual.tools[0].tool_call_template.auth as any;

      expect(auth.auth_type).toBe('api_key');
      expect(auth.var_name).toBe('X-Custom-Key');
      expect(auth.location).toBe('header');

      // Secret must be a placeholder, never the raw value
      expect(auth.api_key).toMatch(/^\{\{.*\}\}$/);
    });

    it('does not leak raw api auth secrets through the manual', async () => {
      toolsService.getTools.mockResolvedValue({ tools: [buildTool()], total: 1 } as any);
      operationRepo.findOne.mockResolvedValue(
        buildOperation({
          api: buildApi({
            authentication: {
              type: 'api_key' as any,
              config: { parameter: 'X-API-Key', apiKey: 'super-secret-real-key' },
            },
          } as any),
        }),
      );

      const manual = await service.generateManual({ organizationId: 'org-1' });
      const json = JSON.stringify(manual);

      expect(json).not.toContain('super-secret-real-key');
    });

    it('omits auth on the call template for unauthenticated APIs', async () => {
      toolsService.getTools.mockResolvedValue({ tools: [buildTool()], total: 1 } as any);
      operationRepo.findOne.mockResolvedValue(
        buildOperation({
          api: buildApi({ authentication: { type: 'none' as any, config: {} } } as any),
        }),
      );

      const manual = await service.generateManual({ organizationId: 'org-1' });
      expect(manual.tools[0].tool_call_template.auth).toBeUndefined();
    });
  });

  describe('getDiscoveryInfo — spec-compliant discovery descriptor', () => {
    it('uses utcp_version + manual_url and points at the correct gateway-scoped manual path', () => {
      const gateway = buildGateway({ endpoint: '/my-gw' });
      const info = service.getDiscoveryInfo({
        organizationId: 'org-1',
        gateway,
        baseUrl: 'https://api.staging.almyty.com',
        orgSlug: 'fb-1234',
      });

      expect(info.utcp_version).toBe('1.0.0');
      expect(typeof info.manual_version).toBe('string');
      expect(info.manual_url).toBe('https://api.staging.almyty.com/fb-1234/my-gw/manual');

      // No legacy /api/ prefix that 404s
      expect(info.manual_url).not.toContain('/api/');
    });

    it('dedupes gateway auth descriptors when multiple active rows of the same type exist', () => {
      const gateway = buildGateway({
        authConfigs: [
          {
            id: 'a-1',
            type: GatewayAuthType.API_KEY,
            isActive: true,
            configuration: { keyHeader: 'x-api-key' },
          },
          {
            id: 'a-2', // duplicate — auto-created + manually added
            type: GatewayAuthType.API_KEY,
            isActive: true,
            configuration: { keyHeader: 'x-api-key' },
          },
        ] as any,
      });

      const info = service.getDiscoveryInfo({
        organizationId: 'org-1',
        gateway,
        baseUrl: 'https://x',
        orgSlug: 'org',
      });

      // One entry, not two — discovery descriptor should advertise each scheme once.
      expect(info.auth).toBeDefined();
      expect(Array.isArray(info.auth)).toBe(false);
    });

    it('embeds gateway api_key auth descriptor when the gateway requires API key', () => {
      const gateway = buildGateway({
        authConfigs: [
          {
            id: 'a-1',
            type: GatewayAuthType.API_KEY,
            isActive: true,
            configuration: { keyHeader: 'x-api-key' },
          } as any,
        ],
      });

      const info = service.getDiscoveryInfo({
        organizationId: 'org-1',
        gateway,
        baseUrl: 'https://x',
        orgSlug: 'org',
      });

      const auth = info.auth as any;
      expect(auth).toBeDefined();
      expect(auth.auth_type).toBe('api_key');
      expect(auth.var_name).toBe('x-api-key');
      expect(auth.location).toBe('header');
    });
  });

  describe('executeUtcpTool', () => {
    it('returns spec-shaped success result with metadata.requestId + executionTime', async () => {
      toolExecutor.executeTool.mockResolvedValue({
        success: true,
        data: { temp: 22 },
        executionTime: 100,
      } as any);

      const result = await service.executeUtcpTool(
        { toolId: 'tool-1', parameters: {} },
        'org-1',
      );

      expect(result.success).toBe(true);
      expect(result.data).toEqual({ temp: 22 });
      expect(result.metadata.toolId).toBe('tool-1');
      expect(result.metadata.requestId).toMatch(/^utcp_/);
      expect(typeof result.metadata.timestamp).toBe('string');
    });
  });
});
