import { Test, TestingModule } from '@nestjs/testing';
import { Repository } from 'typeorm';
import { getRepositoryToken } from '@nestjs/typeorm';
import { UtcpService, utcpCallArguments } from './utcp.service';
import { Tool, ToolStatus } from '../../entities/tool.entity';
import { Api, ApiType } from '../../entities/api.entity';
import { Operation, HttpMethod } from '../../entities/operation.entity';
import { Organization } from '../../entities/organization.entity';
import { Gateway, GatewayStatus, GatewayType } from '../../entities/gateway.entity';
import { GatewayTool } from '../../entities/gateway-tool.entity';
import { GatewayAuthType } from '../../entities/gateway-auth.entity';
import { ToolsService } from '../tools/tools.service';
import { ToolExecutorService } from '../tools/tool-executor.service';
import { fakeRepository } from '../../test/fake-repository';

const REDIS_TOKEN = 'default_IORedisModuleConnectionToken';
/** Where the server is reached; a tool that runs here is called at this gateway's address under it. */
const MANUAL_AT = { baseUrl: 'https://api.test', orgSlug: 'acme' };

describe('UtcpService — spec compliance', () => {
  let service: UtcpService;
  let operationRepo: jest.Mocked<Repository<Operation>>;
  let organizationRepo: jest.Mocked<Repository<Organization>>;
  let gatewayToolRepo: jest.Mocked<Repository<GatewayTool>>;
  let toolsService: jest.Mocked<ToolsService>;
  let toolExecutor: jest.Mocked<ToolExecutorService>;
  let redis: { get: jest.Mock; setex: jest.Mock };

  const buildApi = (over: Partial<Api> = {}): Api => ({
    id: 'api-1',
    name: 'Open-Meteo Weather',
    type: ApiType.OPENAPI,
    baseUrl: 'https://api.open-meteo.com',
    headers: { 'X-Test-Header': 'value' },
    authentication: { type: 'none' as any, config: {} },
    ...over,
  } as any);

  const buildOperation = (over: Partial<Operation> = {}): Operation => ({
    id: 'op-1',
    method: 'GET',
    endpoint: '/v1/forecast',
    parameters: { query: { lat: { type: 'number', required: true } } },
    metadata: {},
    api: buildApi(),
    ...over,
  } as any);

  const buildTool = (over: Partial<Tool> = {}): Tool => ({
    id: 'tool-1',
    name: 'open_meteo_forecast',
    description: 'Get weather forecast',
    parameters: { type: 'object', properties: { lat: { type: 'number' } } },
    outputSchema: { type: 'object' },
    operationId: 'op-1',
    status: ToolStatus.ACTIVE,
    metadata: { sourceApi: { type: 'openapi' }, autoGenerated: true },
    ...over,
  } as any);

  const buildGateway = (over: Partial<Gateway> = {}): Gateway => ({
    id: 'gw-1',
    name: 'Test UTCP',
    type: GatewayType.UTCP,
    status: GatewayStatus.ACTIVE,
    endpoint: '/test-utcp',
    organizationId: 'org-1',
    updatedAt: new Date('2026-04-01T00:00:00Z'),
    authConfigs: [],
    ...over,
  } as any);

  beforeEach(async () => {
    redis = { get: jest.fn().mockResolvedValue(null), setex: jest.fn().mockResolvedValue('OK') };
    operationRepo = { findOne: jest.fn() } as any;
    organizationRepo = {
      findOne: jest
        .fn()
        .mockResolvedValue({ id: 'org-1', name: 'Test', updatedAt: new Date('2026-04-01T00:00:00Z') }),
    } as any;
    // Default: gateway has the canonical fixture tool assigned. Specific
    // tests override this when they want to exercise scoping.
    gatewayToolRepo = fakeRepository<any>([
      { gatewayId: 'gw-1', toolId: 'tool-1', isActive: true, tool: buildTool(), gateway: buildGateway() },
    ]) as any;
    toolsService = { getTools: jest.fn() } as any;
    toolExecutor = { executeTool: jest.fn() } as any;

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        UtcpService,
        { provide: getRepositoryToken(Tool), useValue: {} },
        { provide: getRepositoryToken(Api), useValue: {} },
        { provide: getRepositoryToken(Operation), useValue: operationRepo },
        { provide: getRepositoryToken(Organization), useValue: organizationRepo },
        { provide: getRepositoryToken(GatewayTool), useValue: gatewayToolRepo },
        { provide: ToolsService, useValue: toolsService },
        { provide: ToolExecutorService, useValue: toolExecutor },
        { provide: REDIS_TOKEN, useValue: redis },
      ],
    }).compile();

    service = module.get(UtcpService);
  });

  describe('generateManual — spec-compliant top-level shape', () => {
    it('uses snake_case top-level fields utcp_version, manual_version, tools', async () => {
      toolsService.getTools.mockResolvedValue({ tools: [buildTool()], total: 1 } as any);
      operationRepo.findOne.mockResolvedValue(buildOperation());

      const manual = await service.generateManual({ ...MANUAL_AT, organizationId: 'org-1', gateway: buildGateway() });

      expect(manual.utcp_version).toBe('1.0.0');
      expect(typeof manual.manual_version).toBe('string');
      expect(manual.manual_version.length).toBeGreaterThan(0);
      expect(Array.isArray(manual.tools)).toBe(true);

      // No legacy/extension fields at top level — UTCP SDKs reject unknown fields.
      expect((manual as any).version).toBeUndefined();
      expect((manual as any).info).toBeUndefined();
      expect((manual as any).callTemplates).toBeUndefined();
      expect((manual as any).authentication).toBeUndefined();
      expect((manual as any).metadata).toBeUndefined();
    });

    it('scopes the manual to gateway-assigned tools when gateway is supplied', async () => {
      const tool = buildTool({ id: 'tool-assigned', name: 'assigned' });
      const otherTool = buildTool({ id: 'tool-not-assigned', name: 'leaked' });
      // Only the assigned tool on gw-1; the other is attached -- to gw-2.
      const table = gatewayToolRepo as any;
      await table.delete({ gatewayId: 'gw-1' });
      table.seed({ gatewayId: 'gw-1', toolId: tool.id, isActive: true, tool, gateway: buildGateway() });
      table.seed({ gatewayId: 'gw-2', toolId: otherTool.id, isActive: true, tool: otherTool, gateway: buildGateway({ id: 'gw-2' }) });
      operationRepo.findOne.mockResolvedValue(buildOperation());
      // Even if global tools include a leaked one, gateway scoping must hide it
      toolsService.getTools.mockResolvedValue({ tools: [tool, otherTool], total: 2 } as any);

      const manual = await service.generateManual({
        ...MANUAL_AT,
        organizationId: 'org-1',
        gateway: buildGateway(),
      });

      expect(manual.tools.map((t) => t.name)).toEqual(['assigned']);
    });
  });

  describe('UtcpTool — spec-compliant tool shape', () => {
    it('uses inputs/outputs/tool_call_template (not inputSchema/outputSchema/separate templates)', async () => {
      toolsService.getTools.mockResolvedValue({ tools: [buildTool()], total: 1 } as any);
      operationRepo.findOne.mockResolvedValue(buildOperation());

      const manual = await service.generateManual({ ...MANUAL_AT, organizationId: 'org-1', gateway: buildGateway() });
      const tool = manual.tools[0];

      expect(tool.name).toBe('open_meteo_forecast');
      expect(tool.description).toBeDefined();
      expect(tool.inputs).toBeDefined();
      expect(tool.outputs).toBeDefined();
      expect(Array.isArray(tool.tags)).toBe(true);
      expect(tool.tool_call_template).toBeDefined();

      // Must NOT have extension fields on tool — these break UTCP SDK parsing.
      expect((tool as any).id).toBeUndefined();
      expect((tool as any).version).toBeUndefined();
      expect((tool as any).inputSchema).toBeUndefined();
      expect((tool as any).outputSchema).toBeUndefined();
      expect((tool as any).examples).toBeUndefined();
      expect((tool as any).metadata).toBeUndefined();
    });
  });

  describe('UtcpHttpCallTemplate — spec-compliant call template shape', () => {
    it('uses call_template_type, http_method, url (not protocol/endpoint nested)', async () => {
      toolsService.getTools.mockResolvedValue({ tools: [buildTool()], total: 1 } as any);
      operationRepo.findOne.mockResolvedValue(
        buildOperation({ method: HttpMethod.POST, endpoint: '/v1/predict' }),
      );

      const manual = await service.generateManual({ ...MANUAL_AT, organizationId: 'org-1', gateway: buildGateway() });
      const tmpl = manual.tools[0].tool_call_template as any;

      expect(tmpl.call_template_type).toBe('http');
      expect(tmpl.http_method).toBe('POST');
      expect(tmpl.url).toBe('https://api.open-meteo.com/v1/predict');
      expect(tmpl.content_type).toBe('application/json');

      // No legacy nesting
      expect(tmpl.protocol).toBeUndefined();
      expect(tmpl.endpoint).toBeUndefined();
      expect(tmpl.requestMapping).toBeUndefined();
      expect(tmpl.responseMapping).toBeUndefined();
    });
  });

  describe('UtcpAuth — spec-compliant auth descriptor', () => {
    it('emits api_key auth_type with var_name + location (not the legacy {type, configuration} shape)', async () => {
      toolsService.getTools.mockResolvedValue({ tools: [buildTool()], total: 1 } as any);
      operationRepo.findOne.mockResolvedValue(
        buildOperation({
          api: buildApi({
            authentication: {
              type: 'api_key' as any,
              config: { parameter: 'X-Custom-Key', location: 'header' },
            },
          } as any),
        }),
      );

      const manual = await service.generateManual({ ...MANUAL_AT, organizationId: 'org-1', gateway: buildGateway() });
      const auth = manual.tools[0].tool_call_template.auth as any;

      expect(auth.auth_type).toBe('api_key');
      expect(auth.var_name).toBe('X-Custom-Key');
      expect(auth.location).toBe('header');

      // Secret must be a placeholder, never the raw value
      expect(auth.api_key).toMatch(/^\{\{.*\}\}$/);
    });

    it('does not leak raw api auth secrets through the manual', async () => {
      toolsService.getTools.mockResolvedValue({ tools: [buildTool()], total: 1 } as any);
      operationRepo.findOne.mockResolvedValue(
        buildOperation({
          api: buildApi({
            authentication: {
              type: 'api_key' as any,
              config: { parameter: 'X-API-Key', apiKey: 'super-secret-real-key' },
            },
          } as any),
        }),
      );

      const manual = await service.generateManual({ ...MANUAL_AT, organizationId: 'org-1', gateway: buildGateway() });
      const json = JSON.stringify(manual);

      expect(json).not.toContain('super-secret-real-key');
    });

    it('omits auth on the call template for unauthenticated APIs', async () => {
      toolsService.getTools.mockResolvedValue({ tools: [buildTool()], total: 1 } as any);
      operationRepo.findOne.mockResolvedValue(
        buildOperation({
          api: buildApi({ authentication: { type: 'none' as any, config: {} } } as any),
        }),
      );

      const manual = await service.generateManual({ ...MANUAL_AT, organizationId: 'org-1', gateway: buildGateway() });
      expect(manual.tools[0].tool_call_template.auth).toBeUndefined();
    });
  });

  describe('a tool no API operation backs', () => {
    it.each([
      ['HTTP', { httpConfig: { method: 'GET', path: 'https://hooks.example.com/x' } }],
      ['JavaScript', { code: 'return 1' }],
      ['GraphQL', { graphqlConfig: { endpoint: 'https://g.example.com', query: '{ a }' } }],
      ['LLM', { llmConfig: { providerId: 'p', promptTemplate: 'x', outputMode: 'text' } }],
    ])('lists a hand-made %s tool with a call template for this gateway', async (_type, config) => {
      const tool = buildTool({ id: 'tool-hand', name: 'hand_made', operationId: null, ...(config as any) });
      const gateway = buildGateway({
        authConfigs: [{ type: GatewayAuthType.API_KEY, isActive: true, configuration: { keyHeader: 'x-api-key' } }] as any,
      });
      const table = gatewayToolRepo as any;
      await table.delete({ gatewayId: 'gw-1' });
      table.seed({ gatewayId: 'gw-1', toolId: tool.id, isActive: true, tool, gateway });

      const manual = await service.generateManual({ ...MANUAL_AT, organizationId: 'org-1', gateway });

      expect(manual.tools.map((t) => t.name)).toEqual(['hand_made']);
      expect(manual.tools[0].tool_call_template).toEqual({
        call_template_type: 'http',
        url: 'https://api.test/acme/test-utcp/execute/tool-hand',
        http_method: 'POST',
        content_type: 'application/json',
        auth: { auth_type: 'api_key', api_key: '{{GATEWAY_GW-1_API_KEY}}', var_name: 'x-api-key', location: 'header' },
      });
      expect(operationRepo.findOne).not.toHaveBeenCalled();
    });

    it('keeps a generated tool whose operation cannot be read, on this gateway\'s template', async () => {
      operationRepo.findOne.mockRejectedValue(new Error('connection reset'));
      const manual = await service.generateManual({ ...MANUAL_AT, organizationId: 'org-1', gateway: buildGateway() });
      expect(manual.tools.map((t) => t.name)).toEqual(['open_meteo_forecast']);
      expect(manual.tools[0].tool_call_template.url).toBe('https://api.test/acme/test-utcp/execute/tool-1');
    });
  });

  describe('utcpCallArguments', () => {
    const schema = {
      type: 'object',
      properties: {
        city: { type: 'string' },
        days: { type: 'integer' },
        ratio: { type: 'number' },
        exact: { type: 'boolean' },
        tags: { type: 'array' },
        filter: { type: 'object' },
        maybe: { type: ['null', 'integer'] },
      },
    };

    it('reads query strings back to the types the schema declares', () => {
      expect(
        utcpCallArguments(
          schema,
          { city: '42', days: '3', ratio: '0.5', exact: 'false', tags: '["a","b"]', filter: '{"x":1}', maybe: '7' },
          undefined,
        ),
      ).toEqual({ city: '42', days: 3, ratio: 0.5, exact: false, tags: ['a', 'b'], filter: { x: 1 }, maybe: 7 });
    });

    it('leaves a value that does not parse, and an undeclared argument, as it arrived', () => {
      expect(utcpCallArguments(schema, { days: 'many', exact: 'yes', extra: '1', tags: 'solo' }, undefined)).toEqual({
        days: 'many',
        exact: 'yes',
        extra: '1',
        tags: ['solo'],
      });
    });

    it('takes a JSON object body as the arguments, over the query string', () => {
      expect(utcpCallArguments(schema, { city: 'Oslo', days: '2' }, { city: 'Paris' })).toEqual({ city: 'Paris', days: 2 });
      expect(utcpCallArguments(schema, {}, ['not', 'an', 'object'])).toEqual({});
      expect(utcpCallArguments(null, undefined, undefined)).toEqual({});
    });
  });

  describe('getDiscoveryInfo — spec-compliant discovery descriptor', () => {
    it('uses utcp_version + manual_url and points at the correct gateway-scoped manual path', () => {
      const gateway = buildGateway({ endpoint: '/my-gw' });
      const info = service.getDiscoveryInfo({
        organizationId: 'org-1',
        gateway,
        baseUrl: 'https://api.staging.almyty.com',
        orgSlug: 'fb-1234',
      });

      expect(info.utcp_version).toBe('1.0.0');
      expect(typeof info.manual_version).toBe('string');
      expect(info.manual_url).toBe('https://api.staging.almyty.com/fb-1234/my-gw/manual');

      // No legacy /api/ prefix that 404s
      expect(info.manual_url).not.toContain('/api/');
    });

    it('dedupes gateway auth descriptors when multiple active rows of the same type exist', () => {
      const gateway = buildGateway({
        authConfigs: [
          {
            id: 'a-1',
            type: GatewayAuthType.API_KEY,
            isActive: true,
            configuration: { keyHeader: 'x-api-key' },
          },
          {
            id: 'a-2', // duplicate — auto-created + manually added
            type: GatewayAuthType.API_KEY,
            isActive: true,
            configuration: { keyHeader: 'x-api-key' },
          },
        ] as any,
      });

      const info = service.getDiscoveryInfo({
        organizationId: 'org-1',
        gateway,
        baseUrl: 'https://x',
        orgSlug: 'org',
      });

      // One entry, not two — discovery descriptor should advertise each scheme once.
      expect(info.auth).toBeDefined();
      expect(Array.isArray(info.auth)).toBe(false);
    });

    it('embeds gateway api_key auth descriptor when the gateway requires API key', () => {
      const gateway = buildGateway({
        authConfigs: [
          {
            id: 'a-1',
            type: GatewayAuthType.API_KEY,
            isActive: true,
            configuration: { keyHeader: 'x-api-key' },
          } as any,
        ],
      });

      const info = service.getDiscoveryInfo({
        organizationId: 'org-1',
        gateway,
        baseUrl: 'https://x',
        orgSlug: 'org',
      });

      const auth = info.auth as any;
      expect(auth).toBeDefined();
      expect(auth.auth_type).toBe('api_key');
      expect(auth.var_name).toBe('x-api-key');
      expect(auth.location).toBe('header');
    });
  });

  describe('executeUtcpTool', () => {
    it('returns spec-shaped success result with metadata.requestId + executionTime', async () => {
      toolExecutor.executeTool.mockResolvedValue({
        success: true,
        data: { temp: 22 },
        executionTime: 100,
      } as any);

      const result = await service.executeUtcpTool(
        { toolId: 'tool-1', parameters: {} },
        'org-1',
        'user-uuid',
      );

      expect(result.success).toBe(true);
      expect(result.data).toEqual({ temp: 22 });
      expect(result.metadata.toolId).toBe('tool-1');
      expect(result.metadata.requestId).toMatch(/^utcp_/);
      expect(typeof result.metadata.timestamp).toBe('string');
      // ToolExecutor must receive the real userId, never a placeholder.
      // 'utcp-client' crashes the Postgres UUID cast on the
      // execution row's userId FK.
      expect(toolExecutor.executeTool).toHaveBeenCalledWith(
        'tool-1',
        {},
        expect.objectContaining({ userId: 'user-uuid', organizationId: 'org-1' }),
      );
    });

    it('passes null userId straight through (no placeholder string)', async () => {
      toolExecutor.executeTool.mockResolvedValue({ success: true, data: {}, executionTime: 1 } as any);

      await service.executeUtcpTool({ toolId: 'tool-1', parameters: {} }, 'org-1', null);

      expect(toolExecutor.executeTool).toHaveBeenCalledWith(
        'tool-1',
        {},
        expect.objectContaining({ userId: null }),
      );
    });
  });
});
