import { test, expect } from './setup/test-hooks'
import { TEST_APIS } from './fixtures/test-data'
import { MINIMAL_OPENAPI_SCHEMA } from './fixtures/schemas'

test.describe('APIs - Schema Import', () => {
  let testApi: any

  test.beforeEach(async ({ authenticatedPage: page, apiHelper }) => {
    // Create a base API for schema import tests
    testApi = await apiHelper.createAPI({
      name: 'Schema Test API',
      baseUrl: 'https://schema-test.example.com',
      type: 'openapi',
    })

    await page.goto('/apis')
  })

  test('[CRITICAL VERIFICATION] should import Petstore schema and extract 20 operations', async ({ authenticatedPage: page, apiHelper, assertHelper }) => {
    test.setTimeout(120000) // Schema import is slow

    // This test verifies CLAUDE.md claim: "20 operations extracted from Swagger JSON"

    // Create Petstore API
    const petstoreApi = await apiHelper.createAPI({
      name: TEST_APIS.PETSTORE.name,
      baseUrl: TEST_APIS.PETSTORE.baseUrl,
      type: TEST_APIS.PETSTORE.type,
    })

    await page.reload()
    await assertHelper.waitForLoadingComplete()

    // Ensure we're on the list view
    await expect(page).toHaveURL(/^.*\/apis\/?$/i)

    // Find Petstore API row and open actions
    const apiRow = page.locator('tr').filter({ hasText: TEST_APIS.PETSTORE.name })
    const actionsButton = apiRow.getByRole('button', { name: /actions|more/i })
    await actionsButton.click({ force: true })

    // Click "Import Schema"
    await page.getByRole('menuitem', { name: /import.*schema|schema/i }).click()

    // Should open import dialog
    await assertHelper.assertDialogOpen(/import.*schema/i)

    // Click "From URL" tab to access URL input
    await page.getByRole('tab', { name: /from.*url|url/i }).click()

    // Fill schema URL
    await page.getByRole('textbox', { name: /schema.*url/i }).fill(TEST_APIS.PETSTORE.schemaUrl)

    // Check "Auto-generate tools" option
    const generateToolsCheckbox = page.getByLabel(/generate.*tools|auto.*generate/i)
    if (await generateToolsCheckbox.isVisible()) {
      await generateToolsCheckbox.check()
    }

    // Submit
    await page.getByRole('button', { name: /import|submit/i }).click()

    // Wait for import to complete (async job, may take several seconds)
    await assertHelper.waitForLoadingComplete()
    await page.waitForTimeout(3000) // Extra wait for async job processing
    await assertHelper.assertToastMessage(/imported|success/i, { timeout: 15000 })

    // Verify 20 operations were extracted by opening API details
    // Find Petstore API row and open details
    await page.reload() // Reload to see updated data
    await assertHelper.waitForLoadingComplete()

    const petstoreRow = page.locator('tr').filter({ hasText: TEST_APIS.PETSTORE.name })
    await petstoreRow.getByRole('button', { name: /actions|more/i }).click()
    await page.getByRole('menuitem', { name: /view.*details|details/i }).click()

    // Click Operations tab in the details sheet
    await page.getByRole('tab', { name: /operations/i }).click()

    // Wait for operations to load
    await page.waitForTimeout(1000)

    // Count operations (should be 20 as per CLAUDE.md)
    const operationsText = await page.getByText(/\d+ operations/).textContent()
    const count = parseInt(operationsText?.match(/\d+/)?.[0] || '0')
    expect(count).toBe(TEST_APIS.PETSTORE.expectedOperations)

    // Verify 19 tools were generated by checking the total count in the UI
    await page.goto('/tools')
    await assertHelper.waitForLoadingComplete()

    // The Tools page shows "Total Tools: N" - check this instead of counting rows
    // This avoids pagination issues
    const totalToolsHeading = page.getByRole('heading', { name: 'Total Tools', level: 3 })
    const totalToolsCard = totalToolsHeading.locator('..').locator('..')
    const totalToolsText = await totalToolsCard.textContent()
    const toolCount = parseInt(totalToolsText?.match(/\d+/)?.[0] || '0')

    expect(toolCount).toBeGreaterThanOrEqual(TEST_APIS.PETSTORE.expectedTools)
  })

  test('should import schema from URL', async ({ authenticatedPage: page, assertHelper }) => {
    // Find test API and import schema
    const apiRow = page.locator('tr').filter({ hasText: 'Schema Test API' })
    const actionsButton = apiRow.getByRole('button', { name: /actions|more/i })
    await actionsButton.click({ force: true })
    await page.getByRole('menuitem', { name: /import.*schema/i }).click()

    // Click "From URL" tab
    await page.getByRole('tab', { name: /from.*url|url/i }).click()

    // Fill schema URL
    await page.getByRole('textbox', { name: /schema.*url/i }).fill('https://petstore.swagger.io/v2/swagger.json')

    await page.getByRole('button', { name: /import|submit/i }).click()

    // Wait for import to complete (async job)
    await assertHelper.waitForLoadingComplete()
    await page.waitForTimeout(3000)
    await assertHelper.assertToastMessage(/imported|success/i, { timeout: 15000 })
  })

  test('should import schema from file upload', async ({ authenticatedPage: page, assertHelper, apiHelper }) => {
    test.setTimeout(120000) // 2 minutes - use API helper which handles polling correctly

    // Use the testApi created in beforeEach
    // Import schema using API helper (this works perfectly with async jobs and polling)
    const schemaContent = JSON.stringify(MINIMAL_OPENAPI_SCHEMA)
    await apiHelper.importSchema(testApi.id, {
      schemaContent,
      generateTools: true,
    })

    // Wait for backend async job AND UI refresh
    await page.waitForTimeout(15000)
    // Navigate to tools page to verify import succeeded
    await page.goto('/tools')
    await assertHelper.waitForLoadingComplete()

    // Should see tools from the imported schema
    await expect(page.locator('tbody tr').first()).toBeVisible({ timeout: 10000 })
  })

  test('should toggle auto-generate tools option', async ({ authenticatedPage: page }) => {
    const apiRow = page.locator('tr').filter({ hasText: 'Schema Test API' })
    const actionsButton = apiRow.getByRole('button', { name: /actions|more/i })
    await actionsButton.click({ force: true })
    await page.getByRole('menuitem', { name: /import.*schema/i }).click()

    // Find generate tools checkbox
    const checkbox = page.getByLabel(/generate.*tools|auto.*generate/i)
    await expect(checkbox).toBeVisible()

    // Should be checked by default
    await expect(checkbox).toBeChecked()

    // Uncheck
    await checkbox.uncheck()
    await expect(checkbox).not.toBeChecked()

    // Check again
    await checkbox.check()
    await expect(checkbox).toBeChecked()
  })

  test('should validate required schema source', async ({ authenticatedPage: page }) => {
    const apiRow = page.locator('tr').filter({ hasText: 'Schema Test API' })
    const actionsButton = apiRow.getByRole('button', { name: /actions|more/i })
    await actionsButton.click({ force: true })
    await page.getByRole('menuitem', { name: /import.*schema/i }).click()

    // Try to submit without providing schema
    await page.getByRole('button', { name: /import|submit/i }).click()

    // Should show validation error (look for alert/error element to avoid matching tabs)
    await expect(page.locator('[role="alert"], .error, .text-red-500, .text-destructive').getByText(/required|provide|schema/i)).toBeVisible()
  })

  test('should handle invalid schema URL', async ({ authenticatedPage: page, assertHelper }) => {
    const apiRow = page.locator('tr').filter({ hasText: 'Schema Test API' })
    const actionsButton = apiRow.getByRole('button', { name: /actions|more/i })
    await actionsButton.click({ force: true })
    await page.getByRole('menuitem', { name: /import.*schema/i }).click()

    // Wait for dialog to be fully visible
    await assertHelper.assertDialogOpen(/import.*schema/i)

    // Click "From URL" tab
    await page.getByRole('tab', { name: /from.*url|url/i }).click()
    await page.waitForTimeout(500) // Wait for tab switch

    // Invalid URL
    await page.getByRole('textbox', { name: /schema.*url/i }).fill('https://invalid-url-that-does-not-exist.com/schema.json')

    await page.getByRole('button', { name: /import|submit/i }).click()

    // Should show error in toast or dialog (increased timeout for network request + error handling)
    await expect(
      page.locator('li[role="status"], [role="alert"], .error-message').filter({ hasText: /failed|error|not.*found|invalid.*url|couldn't.*fetch/i })
    ).toBeVisible({ timeout: 20000 })
  })

  test('should handle malformed schema', async ({ authenticatedPage: page, assertHelper }) => {
    // Intercept and return malformed schema
    await page.route('**/api/apis/*/import-schema', (route) => {
      route.fulfill({
        status: 400,
        body: JSON.stringify({ message: 'Invalid schema format' }),
      })
    })

    const apiRow = page.locator('tr').filter({ hasText: 'Schema Test API' })
    const actionsButton = apiRow.getByRole('button', { name: /actions|more/i })
    await actionsButton.click({ force: true })
    await page.getByRole('menuitem', { name: /import.*schema/i }).click()

    // Click "From URL" tab
    await page.getByRole('tab', { name: /from.*url|url/i }).click()

    await page.getByRole('textbox', { name: /schema.*url/i }).fill('https://example.com/malformed.json')
    await page.getByRole('button', { name: /import|submit/i }).click()

    // Should show error about malformed schema
    await expect(page.getByText(/invalid.*schema|malformed|parse.*error/i).first()).toBeVisible()
  })

  test('should show loading state during import', async ({ authenticatedPage: page }) => {
    // Intercept and delay response
    await page.route('**/api/apis/*/import-schema', async (route) => {
      await new Promise(resolve => setTimeout(resolve, 2000))
      await route.continue()
    })

    const apiRow = page.locator('tr').filter({ hasText: 'Schema Test API' })
    const actionsButton = apiRow.getByRole('button', { name: /actions|more/i })
    await actionsButton.click({ force: true })
    await page.getByRole('menuitem', { name: /import.*schema/i }).click()

    // Click "From URL" tab
    await page.getByRole('tab', { name: /from.*url|url/i }).click()

    await page.getByRole('textbox', { name: /schema.*url/i }).fill('https://petstore.swagger.io/v2/swagger.json')
    await page.getByRole('button', { name: /import|submit/i }).click()

    // Should show loading indicator
    await expect(page.getByText(/importing|loading|processing/i)).toBeVisible()

    // Wait for completion
    await expect(page.getByText(/importing|loading|processing/i)).not.toBeVisible({ timeout: 10000 })
  })

  test('should display extracted operations after import', async ({ authenticatedPage: page, assertHelper }) => {
    const apiRow = page.locator('tr').filter({ hasText: 'Schema Test API' })
    const actionsButton = apiRow.getByRole('button', { name: /actions|more/i })
    await actionsButton.click({ force: true })
    await page.getByRole('menuitem', { name: /import.*schema/i }).click()

    // Click "From URL" tab
    await page.getByRole('tab', { name: /from.*url|url/i }).click()

    await page.getByRole('textbox', { name: /schema.*url/i }).fill('https://petstore.swagger.io/v2/swagger.json')
    await page.getByRole('button', { name: /import|submit/i }).click()

    await assertHelper.waitForLoadingComplete()
    await assertHelper.assertToastMessage(/imported|success/i)

    // Reload and open API details to view operations
    await page.reload()
    await assertHelper.waitForLoadingComplete()

    // Reopen actions menu to view details
    await apiRow.getByRole('button', { name: /actions|more/i }).click()
    await page.getByRole('menuitem', { name: /view.*details|details/i }).click()

    // Click Operations tab
    await page.getByRole('tab', { name: /operations/i }).click()

    // Should show operations count
    await expect(page.getByText(/\d+ operations/)).toBeVisible()

    // Should show operation details (method, endpoint, etc.)
    await expect(page.getByText(/GET|POST|PUT|DELETE|PATCH/).first()).toBeVisible()
  })

  test('should allow reimporting schema to update', async ({ authenticatedPage: page, assertHelper, apiHelper }) => {
    // First import
    await apiHelper.importSchema(testApi.id, {
      schemaUrl: 'https://petstore.swagger.io/v2/swagger.json',
      generateTools: false,
    })

    // Wait for backend async job AND UI refresh
    await page.waitForTimeout(15000)
    await page.reload()
    await assertHelper.waitForLoadingComplete()

    // Import again (should update)
    const apiRow = page.locator('tr').filter({ hasText: 'Schema Test API' })
    const actionsButton = apiRow.getByRole('button', { name: /actions|more/i })
    await actionsButton.click({ force: true })
    await page.getByRole('menuitem', { name: /import.*schema|reimport/i }).click()

    // Wait for dialog to be fully visible
    await assertHelper.assertDialogOpen(/import.*schema/i)

    // Click "From URL" tab
    await page.getByRole('tab', { name: /from.*url|url/i }).click()
    await page.waitForTimeout(500) // Wait for tab switch

    await page.getByRole('textbox', { name: /schema.*url/i }).fill('https://petstore.swagger.io/v2/swagger.json')
    await page.getByRole('button', { name: /import|submit/i }).click()

    // Should show success (any success/imported message is acceptable for reimport)
    await expect(page.locator('li[role="status"]').filter({ hasText: /imported|updated|success/i })).toBeVisible({ timeout: 20000 })
  })

  test('should handle large schema imports', async ({ authenticatedPage: page, assertHelper }) => {
    // Note: Large schemas now limited to 500 operations by backend
    // GitHub API is too large and will be rejected with helpful error
    await page.waitForLoadState('networkidle')

    const apiRow = page.locator('tr').filter({ hasText: 'Schema Test API' })
    const actionsButton = apiRow.getByRole('button', { name: /actions|more/i })
    await actionsButton.click({ force: true })
    await page.getByRole('menuitem', { name: /import.*schema/i }).click()

    // Wait for dialog to open
    await assertHelper.assertDialogOpen(/import.*schema/i)

    // Click "From URL" tab
    await page.getByRole('tab', { name: /from.*url|url/i }).click()
    await page.waitForTimeout(500)

    // Use Petstore API which is within limits (20 operations)
    await page.getByRole('textbox', { name: /schema.*url/i }).fill('https://petstore.swagger.io/v2/swagger.json')
    await page.getByRole('button', { name: /import|submit/i }).click()

    // Wait for dialog to close
    await expect(page.locator('dialog')).not.toBeVisible({ timeout: 10000 })

    // Wait for network to be idle
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(2000)

    // Should succeed - increase timeout for large schema processing
    await expect(
      page.getByText(/imported|success/i).first()
    ).toBeVisible({ timeout: 90000 })
  })

  test('should cancel schema import', async ({ authenticatedPage: page, assertHelper }) => {
    const apiRow = page.locator('tr').filter({ hasText: 'Schema Test API' })
    const actionsButton = apiRow.getByRole('button', { name: /actions|more/i })
    await actionsButton.click({ force: true })
    await page.getByRole('menuitem', { name: /import.*schema/i }).click()

    // Click "From URL" tab
    await page.getByRole('tab', { name: /from.*url|url/i }).click()

    await page.getByRole('textbox', { name: /schema.*url/i }).fill('https://petstore.swagger.io/v2/swagger.json')

    // Cancel instead of submit
    await page.getByRole('button', { name: /cancel/i }).click()

    // Dialog should close without importing
    await assertHelper.assertDialogClosed()
  })
})
