import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { Tool, ToolExecutionMethod } from '../../entities/tool.entity';
import { Gateway } from '../../entities/gateway.entity';
import { GatewayTool } from '../../entities/gateway-tool.entity';

export interface CliOutput {
  name: string;
  content: string;
  format: 'bash' | 'node';
  toolCount: number;
}

@Injectable()
export class CliGeneratorService {
  private readonly logger = new Logger(CliGeneratorService.name);

  constructor(
    @InjectRepository(Tool)
    private toolRepository: Repository<Tool>,
    @InjectRepository(Gateway)
    private gatewayRepository: Repository<Gateway>,
    @InjectRepository(GatewayTool)
    private gatewayToolRepository: Repository<GatewayTool>,
  ) {}

  /**
   * Generate a CLI script for a single tool.
   *
   * @param organizationId Required. Previously this lookup had no org
   *   filter, letting any authenticated user download any org's tool
   *   scripts by UUID.
   */
  async generateToolCli(
    toolId: string,
    format: 'bash' | 'node' = 'bash',
    organizationId?: string,
  ): Promise<CliOutput> {
    if (!organizationId) {
      throw new NotFoundException(`Tool not found: ${toolId}`);
    }
    const tool = await this.toolRepository.findOne({
      where: { id: toolId, organizationId },
      relations: ['operation'],
    });

    if (!tool) {
      throw new NotFoundException(`Tool not found: ${toolId}`);
    }

    const content = format === 'bash'
      ? this.renderBashScript(tool)
      : this.renderNodeScript(tool);

    return {
      name: this.slugify(tool.name),
      content,
      format,
      toolCount: 1,
    };
  }

  /**
   * Generate a CLI bundle for all tools in a gateway.
   *
   * @param organizationId Required (see generateToolCli).
   */
  async generateGatewayCliBunde(
    gatewayId: string,
    format: 'bash' | 'node' = 'bash',
    organizationId?: string,
  ): Promise<CliOutput> {
    if (!organizationId) {
      throw new NotFoundException(`Gateway not found: ${gatewayId}`);
    }
    const gateway = await this.gatewayRepository.findOne({
      where: { id: gatewayId, organizationId },
    });

    if (!gateway) {
      throw new NotFoundException(`Gateway not found: ${gatewayId}`);
    }

    const gatewayTools = await this.gatewayToolRepository.find({
      where: { gatewayId, isActive: true },
      relations: ['tool', 'tool.operation'],
    });

    const tools = gatewayTools.map(gt => gt.tool).filter(Boolean);

    const content = format === 'bash'
      ? this.renderBashBundle(gateway, tools)
      : this.renderNodeBundle(gateway, tools);

    return {
      name: this.slugify(gateway.name),
      content,
      format,
      toolCount: tools.length,
    };
  }

  // --- Bash generators ---

  private renderBashScript(tool: Tool): string {
    const params = tool.parameters as any;
    const properties = params?.properties || {};
    const required = params?.required || [];
    const method = tool.operation?.method?.toUpperCase() || 'GET';
    const endpoint = tool.operation?.endpoint || '/';

    const lines: string[] = [];
    lines.push('#!/usr/bin/env bash');
    lines.push(`# CLI wrapper for: ${tool.name}`);
    lines.push(`# ${tool.description || 'No description'}`);
    lines.push(`# Generated by almyty`);
    lines.push('');
    lines.push('set -euo pipefail');
    lines.push('');

    // Configuration
    lines.push('# Configuration');
    lines.push('BASE_URL="${ALMYTY_BASE_URL:-http://localhost:4000}"');
    lines.push('TOKEN="${ALMYTY_TOKEN:-}"');
    lines.push('');

    // Usage function
    lines.push('usage() {');
    lines.push(`  echo "Usage: $0 [options]"`);
    lines.push('  echo ""');
    lines.push('  echo "Options:"');
    for (const [name, schema] of Object.entries(properties)) {
      const paramSchema = schema as any;
      const isReq = required.includes(name);
      const flag = this.toFlag(name);
      lines.push(`  echo "  --${flag} <${paramSchema.type || 'string'}>  ${paramSchema.description || name}${isReq ? ' (required)' : ''}"`);
    }
    lines.push('  echo "  --help                Show this help"');
    lines.push('  exit 1');
    lines.push('}');
    lines.push('');

    // Parse arguments
    lines.push('# Parse arguments');
    for (const name of Object.keys(properties)) {
      lines.push(`${this.toVarName(name)}=""`);
    }
    lines.push('');
    lines.push('while [[ $# -gt 0 ]]; do');
    lines.push('  case "$1" in');
    for (const name of Object.keys(properties)) {
      const flag = this.toFlag(name);
      lines.push(`    --${flag}) ${this.toVarName(name)}="$2"; shift 2 ;;`);
    }
    lines.push('    --help) usage ;;');
    lines.push('    *) echo "Unknown option: $1"; usage ;;');
    lines.push('  esac');
    lines.push('done');
    lines.push('');

    // Validate required
    if (required.length > 0) {
      lines.push('# Validate required parameters');
      for (const name of required) {
        const varName = this.toVarName(name);
        lines.push(`if [[ -z "$${varName}" ]]; then echo "Error: --${this.toFlag(name)} is required"; usage; fi`);
      }
      lines.push('');
    }

    // Build JSON body
    lines.push('# Build request');
    lines.push('JSON_BODY="{"');
    const paramNames = Object.keys(properties);
    for (let i = 0; i < paramNames.length; i++) {
      const name = paramNames[i];
      const varName = this.toVarName(name);
      const comma = i < paramNames.length - 1 ? ',' : '';
      lines.push(`if [[ -n "$${varName}" ]]; then JSON_BODY+="\\"${name}\\":\\"$${varName}\\"${comma}"; fi`);
    }
    lines.push('JSON_BODY+="}"');
    lines.push('');

    // Execute via almyty UTCP endpoint
    lines.push('# Execute tool via almyty');
    lines.push(`curl -s -X POST \\`);
    lines.push(`  "\${BASE_URL}/api/utcp/tools/${this.slugify(tool.name)}/execute" \\`);
    lines.push('  -H "Content-Type: application/json" \\');
    lines.push('  -H "Authorization: Bearer ${TOKEN}" \\');
    lines.push('  -d "$JSON_BODY" | python3 -m json.tool 2>/dev/null || cat');
    lines.push('');

    return lines.join('\n');
  }

  private renderBashBundle(gateway: any, tools: Tool[]): string {
    const lines: string[] = [];
    lines.push('#!/usr/bin/env bash');
    lines.push(`# CLI bundle for gateway: ${gateway.name}`);
    lines.push(`# ${tools.length} tools available`);
    lines.push(`# Generated by almyty`);
    lines.push('');
    lines.push('set -euo pipefail');
    lines.push('');
    lines.push('BASE_URL="${ALMYTY_BASE_URL:-http://localhost:4000}"');
    lines.push('TOKEN="${ALMYTY_TOKEN:-}"');
    lines.push('');

    // List available commands
    lines.push('usage() {');
    lines.push(`  echo "${gateway.name} CLI"`);
    lines.push('  echo ""');
    lines.push('  echo "Commands:"');
    for (const tool of tools) {
      lines.push(`  echo "  ${this.slugify(tool.name)}  ${tool.description || 'No description'}"`);
    }
    lines.push('  echo ""');
    lines.push('  echo "Usage: $0 <command> [--param value ...]"');
    lines.push('  exit 1');
    lines.push('}');
    lines.push('');

    lines.push('if [[ $# -lt 1 ]]; then usage; fi');
    lines.push('');
    lines.push('COMMAND="$1"; shift');
    lines.push('');

    // Build JSON from remaining args
    lines.push('# Build JSON body from --key value pairs');
    lines.push('JSON_BODY="{"');
    lines.push('FIRST=true');
    lines.push('while [[ $# -gt 0 ]]; do');
    lines.push('  KEY="${1#--}"');
    lines.push('  VALUE="$2"');
    lines.push('  if [[ "$FIRST" == "true" ]]; then FIRST=false; else JSON_BODY+=","; fi');
    lines.push('  JSON_BODY+="\\"$KEY\\":\\"$VALUE\\""');
    lines.push('  shift 2');
    lines.push('done');
    lines.push('JSON_BODY+="}"');
    lines.push('');

    // Execute
    lines.push('curl -s -X POST \\');
    lines.push('  "${BASE_URL}/api/utcp/tools/${COMMAND}/execute" \\');
    lines.push('  -H "Content-Type: application/json" \\');
    lines.push('  -H "Authorization: Bearer ${TOKEN}" \\');
    lines.push('  -d "$JSON_BODY" | python3 -m json.tool 2>/dev/null || cat');
    lines.push('');

    return lines.join('\n');
  }

  // --- Node.js generators ---

  private renderNodeScript(tool: Tool): string {
    const params = tool.parameters as any;
    const properties = params?.properties || {};
    const required = params?.required || [];

    const lines: string[] = [];
    lines.push('#!/usr/bin/env node');
    lines.push(`// CLI wrapper for: ${tool.name}`);
    lines.push(`// ${tool.description || 'No description'}`);
    lines.push('// Generated by almyty');
    lines.push('');
    lines.push("const BASE_URL = process.env.ALMYTY_BASE_URL || 'http://localhost:4000';");
    lines.push("const TOKEN = process.env.ALMYTY_TOKEN || '';");
    lines.push('');

    // Parse args
    lines.push('function parseArgs(args) {');
    lines.push('  const parsed = {};');
    lines.push('  for (let i = 0; i < args.length; i++) {');
    lines.push("    if (args[i].startsWith('--')) {");
    lines.push('      const key = args[i].slice(2);');
    lines.push('      parsed[key] = args[i + 1] || true;');
    lines.push('      i++;');
    lines.push('    }');
    lines.push('  }');
    lines.push('  return parsed;');
    lines.push('}');
    lines.push('');

    lines.push('async function main() {');
    lines.push('  const args = parseArgs(process.argv.slice(2));');
    lines.push('');

    // Help
    lines.push("  if (args.help) {");
    lines.push(`    console.log('Usage: ${this.slugify(tool.name)} [options]');`);
    lines.push("    console.log('');");
    lines.push("    console.log('Options:');");
    for (const [name, schema] of Object.entries(properties)) {
      const paramSchema = schema as any;
      const isReq = required.includes(name);
      lines.push(`    console.log('  --${this.toFlag(name)} <${paramSchema.type || 'string'}>  ${(paramSchema.description || name).replace(/'/g, "\\'")}${isReq ? ' (required)' : ''}');`);
    }
    lines.push("    process.exit(0);");
    lines.push('  }');
    lines.push('');

    // Validate required
    if (required.length > 0) {
      for (const name of required) {
        const flag = this.toFlag(name);
        lines.push(`  if (!args['${flag}']) { console.error('Error: --${flag} is required'); process.exit(1); }`);
      }
      lines.push('');
    }

    // Build params object
    lines.push('  const params = {};');
    for (const name of Object.keys(properties)) {
      const flag = this.toFlag(name);
      lines.push(`  if (args['${flag}'] !== undefined) params['${name}'] = args['${flag}'];`);
    }
    lines.push('');

    // Execute
    lines.push(`  const response = await fetch(\`\${BASE_URL}/api/utcp/tools/${this.slugify(tool.name)}/execute\`, {`);
    lines.push("    method: 'POST',");
    lines.push("    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${TOKEN}` },");
    lines.push('    body: JSON.stringify(params),');
    lines.push('  });');
    lines.push('');
    lines.push('  const result = await response.json();');
    lines.push('  console.log(JSON.stringify(result, null, 2));');
    lines.push('}');
    lines.push('');
    lines.push('main().catch(err => { console.error(err.message); process.exit(1); });');
    lines.push('');

    return lines.join('\n');
  }

  private renderNodeBundle(gateway: any, tools: Tool[]): string {
    const lines: string[] = [];
    lines.push('#!/usr/bin/env node');
    lines.push(`// CLI bundle for gateway: ${gateway.name}`);
    lines.push(`// ${tools.length} tools available`);
    lines.push('// Generated by almyty');
    lines.push('');
    lines.push("const BASE_URL = process.env.ALMYTY_BASE_URL || 'http://localhost:4000';");
    lines.push("const TOKEN = process.env.ALMYTY_TOKEN || '';");
    lines.push('');

    lines.push('const COMMANDS = {');
    for (const tool of tools) {
      lines.push(`  '${this.slugify(tool.name)}': '${(tool.description || 'No description').replace(/'/g, "\\'")}',`);
    }
    lines.push('};');
    lines.push('');

    lines.push('function parseArgs(args) {');
    lines.push('  const parsed = {};');
    lines.push('  for (let i = 0; i < args.length; i++) {');
    lines.push("    if (args[i].startsWith('--')) {");
    lines.push('      parsed[args[i].slice(2)] = args[i + 1] || true;');
    lines.push('      i++;');
    lines.push('    }');
    lines.push('  }');
    lines.push('  return parsed;');
    lines.push('}');
    lines.push('');

    lines.push('async function main() {');
    lines.push('  const command = process.argv[2];');
    lines.push('  const args = parseArgs(process.argv.slice(3));');
    lines.push('');
    lines.push("  if (!command || command === '--help') {");
    lines.push(`    console.log('${gateway.name} CLI');`);
    lines.push("    console.log('');");
    lines.push("    console.log('Commands:');");
    lines.push("    for (const [name, desc] of Object.entries(COMMANDS)) {");
    lines.push("      console.log(`  ${name}  ${desc}`);");
    lines.push('    }');
    lines.push("    process.exit(0);");
    lines.push('  }');
    lines.push('');
    lines.push('  if (!COMMANDS[command]) {');
    lines.push("    console.error(`Unknown command: ${command}`);");
    lines.push("    process.exit(1);");
    lines.push('  }');
    lines.push('');
    lines.push('  const response = await fetch(`${BASE_URL}/api/utcp/tools/${command}/execute`, {');
    lines.push("    method: 'POST',");
    lines.push("    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${TOKEN}` },");
    lines.push('    body: JSON.stringify(args),');
    lines.push('  });');
    lines.push('');
    lines.push('  const result = await response.json();');
    lines.push('  console.log(JSON.stringify(result, null, 2));');
    lines.push('}');
    lines.push('');
    lines.push('main().catch(err => { console.error(err.message); process.exit(1); });');
    lines.push('');

    return lines.join('\n');
  }

  // --- Helpers ---

  private slugify(name: string): string {
    if (!name) return 'unnamed';
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      || 'unnamed';
  }

  private toFlag(name: string): string {
    return name.replace(/([A-Z])/g, '-$1').toLowerCase().replace(/^-/, '');
  }

  private toVarName(name: string): string {
    return name.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
  }
}
