import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { Tool } from '../../entities/tool.entity';
import { Gateway } from '../../entities/gateway.entity';
import { GatewayTool } from '../../entities/gateway-tool.entity';
import { servableOnGateway } from '../../common/authorization/private-visibility';
import {
  jsComment,
  jsDocText,
  jsIdentifier,
  jsStringLiteral,
  singleLine,
  tsPropertyKey,
} from '../../common/security/untrusted-text';

export interface SdkOutput {
  name: string;
  files: SdkFile[];
  toolCount: number;
}

export interface SdkFile {
  path: string;
  content: string;
}

@Injectable()
export class CodegenService {
  private readonly logger = new Logger(CodegenService.name);

  constructor(
    @InjectRepository(Tool)
    private toolRepository: Repository<Tool>,
    @InjectRepository(Gateway)
    private gatewayRepository: Repository<Gateway>,
    @InjectRepository(GatewayTool)
    private gatewayToolRepository: Repository<GatewayTool>,
  ) {}

  /**
   * Generate a TypeScript SDK for a single tool.
   *
   * @param organizationId Required for org scoping. Previously omitted,
   *   which let any authenticated user download any tool's SDK (and
   *   therefore its parameter schema + endpoint slug) just by guessing
   *   a UUID, regardless of which org the tool belonged to.
   */
  async generateToolSdk(toolId: string, organizationId: string): Promise<SdkOutput> {
    if (!organizationId) {
      throw new NotFoundException(`Tool not found: ${toolId}`);
    }
    const tool = await this.toolRepository.findOne({
      where: { id: toolId, organizationId },
      relations: { operation: true },
    });

    if (!tool) {
      throw new NotFoundException(`Tool not found: ${toolId}`);
    }

    const name = this.slugify(tool.name);
    const files: SdkFile[] = [
      { path: `${name}.ts`, content: this.renderToolModule(tool) },
    ];

    return { name, files, toolCount: 1 };
  }

  /**
   * Generate a complete TypeScript SDK package for a gateway.
   *
   * @param organizationId Required for org scoping (see generateToolSdk).
   */
  async generateGatewaySdk(gatewayId: string, organizationId: string): Promise<SdkOutput> {
    if (!organizationId) {
      throw new NotFoundException(`Gateway not found: ${gatewayId}`);
    }
    const gateway = await this.gatewayRepository.findOne({
      where: { id: gatewayId, organizationId },
    });

    if (!gateway) {
      throw new NotFoundException(`Gateway not found: ${gatewayId}`);
    }

    const gatewayTools = await this.gatewayToolRepository.find({
      where: { gatewayId, isActive: true },
      relations: { tool: { operation: true } },
    });

    // A private tool is served only on its owner's own private gateway.
    const tools = servableOnGateway(gatewayTools.map(gt => gt.tool).filter(Boolean), gateway);
    const packageName = this.slugify(gateway.name);

    const files: SdkFile[] = [
      { path: 'package.json', content: this.renderPackageJson(packageName, tools) },
      { path: 'tsconfig.json', content: this.renderTsConfig() },
      { path: 'src/index.ts', content: this.renderIndex(gateway, tools) },
      { path: 'src/client.ts', content: this.renderClient(gateway) },
      { path: 'src/types.ts', content: this.renderTypes(tools) },
    ];

    for (const tool of tools) {
      files.push({
        path: `src/${this.slugify(tool.name)}.ts`,
        content: this.renderToolModule(tool),
      });
    }

    return { name: packageName, files, toolCount: tools.length };
  }

  // --- Renderers ---

  private renderPackageJson(name: string, _tools: Tool[]): string {
    const pkg = {
      name: `@almyty/${name}`,
      version: '1.0.0',
      description: `TypeScript SDK for ${name} (generated by almyty)`,
      main: 'dist/index.js',
      types: 'dist/index.d.ts',
      scripts: {
        build: 'tsc',
        prepublishOnly: 'npm run build',
      },
      dependencies: {},
      devDependencies: {
        typescript: '^5.3.0',
      },
    };
    return JSON.stringify(pkg, null, 2);
  }

  private renderTsConfig(): string {
    const config = {
      compilerOptions: {
        target: 'ES2020',
        module: 'commonjs',
        lib: ['ES2020'],
        declaration: true,
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
      },
      include: ['src/**/*'],
    };
    return JSON.stringify(config, null, 2);
  }

  // Schema text (tool names and descriptions, parameter names, enum
  // values) reaches the generated TypeScript only as identifiers reduced
  // to a safe charset, JSON string literals / quoted keys, or single-line
  // comments with the terminator defused. See common/security/untrusted-text.

  private renderIndex(gateway: any, tools: Tool[]): string {
    const lines: string[] = [];
    lines.push(jsComment(`${gateway.name} SDK - Generated by almyty`));
    lines.push(`// ${tools.length} tools available`);
    lines.push('');
    lines.push("export { AlmytyClient, ClientConfig } from './client';");
    lines.push("export * from './types';");
    lines.push('');

    for (const tool of tools) {
      const slug = this.slugify(tool.name);
      const funcName = this.toCamelCase(tool.name);
      lines.push(`export { ${funcName} } from ${jsStringLiteral(`./${slug}`)};`);
    }
    lines.push('');

    // Convenience: create a pre-configured client
    lines.push("import { AlmytyClient, ClientConfig } from './client';");
    lines.push('');
    lines.push('export function createClient(config: ClientConfig): AlmytyClient {');
    lines.push('  return new AlmytyClient(config);');
    lines.push('}');
    lines.push('');

    return lines.join('\n');
  }

  private renderClient(gateway: any): string {
    const lines: string[] = [];
    lines.push(jsComment(`HTTP client for ${gateway.name}`));
    lines.push('');
    lines.push('export interface ClientConfig {');
    lines.push('  baseUrl: string;');
    lines.push('  token: string;');
    lines.push('  timeout?: number;');
    lines.push('}');
    lines.push('');
    lines.push('export class AlmytyClient {');
    lines.push('  private baseUrl: string;');
    lines.push('  private token: string;');
    lines.push('  private timeout: number;');
    lines.push('');
    lines.push('  constructor(config: ClientConfig) {');
    lines.push("    this.baseUrl = config.baseUrl.replace(/\\/$/, '');");
    lines.push('    this.token = config.token;');
    lines.push('    this.timeout = config.timeout || 30000;');
    lines.push('  }');
    lines.push('');
    lines.push('  async callTool<T = any>(toolName: string, params: Record<string, any>): Promise<T> {');
    lines.push('    const controller = new AbortController();');
    lines.push('    const timeoutId = setTimeout(() => controller.abort(), this.timeout);');
    lines.push('');
    lines.push('    try {');
    lines.push('      const response = await fetch(');
    lines.push('        `${this.baseUrl}/utcp/tools/${toolName}/execute`,');
    lines.push('        {');
    lines.push("          method: 'POST',");
    lines.push('          headers: {');
    lines.push("            'Content-Type': 'application/json',");
    lines.push("            'Authorization': `Bearer ${this.token}`,");
    lines.push('          },');
    lines.push('          body: JSON.stringify(params),');
    lines.push('          signal: controller.signal,');
    lines.push('        },');
    lines.push('      );');
    lines.push('');
    lines.push('      if (!response.ok) {');
    lines.push('        const error = await response.json().catch(() => ({ message: response.statusText }));');
    lines.push('        throw new Error(`API error ${response.status}: ${error.message || response.statusText}`);');
    lines.push('      }');
    lines.push('');
    lines.push('      return response.json();');
    lines.push('    } finally {');
    lines.push('      clearTimeout(timeoutId);');
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
    lines.push('');

    return lines.join('\n');
  }

  private renderTypes(tools: Tool[]): string {
    const lines: string[] = [];
    lines.push('// Generated TypeScript types for tool parameters and responses');
    lines.push('');

    for (const tool of tools) {
      lines.push(...this.renderParamsInterface(tool));
      lines.push('');
    }

    return lines.join('\n');
  }

  private renderParamsInterface(tool: Tool): string[] {
    const typeName = this.toPascalCase(tool.name);
    const params = tool.parameters as any;
    const properties = params?.properties || {};
    const required: string[] = Array.isArray(params?.required) ? params.required : [];

    const lines: string[] = [];
    lines.push(`export interface ${typeName}Params {`);
    for (const [name, schema] of Object.entries(properties)) {
      const paramSchema = (schema || {}) as any;
      const tsType = this.jsonSchemaToTs(paramSchema);
      const optional = required.includes(name) ? '' : '?';
      if (paramSchema.description) {
        lines.push(`  /** ${jsDocText(paramSchema.description)} */`);
      }
      lines.push(`  ${tsPropertyKey(name)}${optional}: ${tsType};`);
    }
    lines.push('}');
    return lines;
  }

  private renderToolModule(tool: Tool): string {
    const funcName = this.toCamelCase(tool.name);
    const typeName = this.toPascalCase(tool.name);
    const slug = this.slugify(tool.name);

    const lines: string[] = [];
    lines.push(jsComment(tool.description || tool.name));
    lines.push("import { AlmytyClient } from './client';");
    lines.push('');

    // Inline params type for standalone use
    lines.push(...this.renderParamsInterface(tool));
    lines.push('');

    // Function
    if (tool.description) {
      lines.push(`/** ${jsDocText(tool.description)} */`);
    }
    lines.push(`export async function ${funcName}(client: AlmytyClient, params: ${typeName}Params): Promise<any> {`);
    lines.push(`  return client.callTool(${jsStringLiteral(slug)}, params);`);
    lines.push('}');
    lines.push('');

    return lines.join('\n');
  }

  // --- Type conversion ---

  private jsonSchemaToTs(schema: any, depth = 0): string {
    if (!schema || typeof schema !== 'object' || depth > 8) return 'any';

    switch (schema.type) {
      case 'string':
        if (Array.isArray(schema.enum) && schema.enum.length > 0) {
          return schema.enum.map((v: unknown) => this.tsLiteralType(v)).join(' | ');
        }
        return 'string';
      case 'integer':
      case 'number':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'array': {
        const itemType = schema.items ? this.jsonSchemaToTs(schema.items, depth + 1) : 'any';
        return itemType.includes('|') ? `(${itemType})[]` : `${itemType}[]`;
      }
      case 'object':
        if (schema.properties && typeof schema.properties === 'object') {
          const props = Object.entries(schema.properties)
            .map(([k, v]) => `${tsPropertyKey(k)}: ${this.jsonSchemaToTs(v as any, depth + 1)}`)
            .join('; ');
          return `{ ${props} }`;
        }
        return 'Record<string, any>';
      default:
        return 'any';
    }
  }

  /** A literal type for an enum member; anything but a finite primitive is `any`. */
  private tsLiteralType(value: unknown): string {
    if (typeof value === 'string') return jsStringLiteral(value, 256);
    if (typeof value === 'number' && Number.isFinite(value)) return String(value);
    if (typeof value === 'boolean') return String(value);
    return 'any';
  }

  // --- Helpers ---

  private slugify(name: string): string {
    if (!name) return 'unnamed';
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      || 'unnamed';
  }

  private toCamelCase(name: string): string {
    if (!name) return 'unnamed';
    // If already camelCase, keep it
    if (/^[a-z][a-zA-Z0-9]*$/.test(name)) return jsIdentifier(name);
    // Convert from snake_case, kebab-case, or PascalCase, then drop
    // anything that isn't an identifier character.
    const camel = singleLine(name, 128)
      .replace(/[^A-Za-z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''))
      .replace(/^[A-Z]/, (c) => c.toLowerCase());
    return jsIdentifier(camel);
  }

  private toPascalCase(name: string): string {
    const camel = this.toCamelCase(name).replace(/^_/, '');
    return jsIdentifier(camel.charAt(0).toUpperCase() + camel.slice(1), 'Unnamed');
  }
}