import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { Tool } from '../../entities/tool.entity';
import { Gateway } from '../../entities/gateway.entity';
import { GatewayTool } from '../../entities/gateway-tool.entity';

export interface SdkOutput {
  name: string;
  files: SdkFile[];
  toolCount: number;
}

export interface SdkFile {
  path: string;
  content: string;
}

@Injectable()
export class CodegenService {
  private readonly logger = new Logger(CodegenService.name);

  constructor(
    @InjectRepository(Tool)
    private toolRepository: Repository<Tool>,
    @InjectRepository(Gateway)
    private gatewayRepository: Repository<Gateway>,
    @InjectRepository(GatewayTool)
    private gatewayToolRepository: Repository<GatewayTool>,
  ) {}

  /**
   * Generate a TypeScript SDK for a single tool.
   *
   * @param organizationId Required for org scoping. Previously omitted,
   *   which let any authenticated user download any tool's SDK (and
   *   therefore its parameter schema + endpoint slug) just by guessing
   *   a UUID, regardless of which org the tool belonged to.
   */
  async generateToolSdk(toolId: string, organizationId: string): Promise<SdkOutput> {
    if (!organizationId) {
      throw new NotFoundException(`Tool not found: ${toolId}`);
    }
    const tool = await this.toolRepository.findOne({
      where: { id: toolId, organizationId },
      relations: ['operation'],
    });

    if (!tool) {
      throw new NotFoundException(`Tool not found: ${toolId}`);
    }

    const name = this.slugify(tool.name);
    const files: SdkFile[] = [
      { path: `${name}.ts`, content: this.renderToolModule(tool) },
    ];

    return { name, files, toolCount: 1 };
  }

  /**
   * Generate a complete TypeScript SDK package for a gateway.
   *
   * @param organizationId Required for org scoping (see generateToolSdk).
   */
  async generateGatewaySdk(gatewayId: string, organizationId: string): Promise<SdkOutput> {
    if (!organizationId) {
      throw new NotFoundException(`Gateway not found: ${gatewayId}`);
    }
    const gateway = await this.gatewayRepository.findOne({
      where: { id: gatewayId, organizationId },
    });

    if (!gateway) {
      throw new NotFoundException(`Gateway not found: ${gatewayId}`);
    }

    const gatewayTools = await this.gatewayToolRepository.find({
      where: { gatewayId, isActive: true },
      relations: ['tool', 'tool.operation'],
    });

    const tools = gatewayTools.map(gt => gt.tool).filter(Boolean);
    const packageName = this.slugify(gateway.name);

    const files: SdkFile[] = [
      { path: 'package.json', content: this.renderPackageJson(packageName, tools) },
      { path: 'tsconfig.json', content: this.renderTsConfig() },
      { path: 'src/index.ts', content: this.renderIndex(gateway, tools) },
      { path: 'src/client.ts', content: this.renderClient(gateway) },
      { path: 'src/types.ts', content: this.renderTypes(tools) },
    ];

    for (const tool of tools) {
      const moduleName = this.toCamelCase(tool.name);
      files.push({
        path: `src/${this.slugify(tool.name)}.ts`,
        content: this.renderToolModule(tool),
      });
    }

    return { name: packageName, files, toolCount: tools.length };
  }

  // --- Renderers ---

  private renderPackageJson(name: string, tools: Tool[]): string {
    const pkg = {
      name: `@almyty/${name}`,
      version: '1.0.0',
      description: `TypeScript SDK for ${name} (generated by almyty)`,
      main: 'dist/index.js',
      types: 'dist/index.d.ts',
      scripts: {
        build: 'tsc',
        prepublishOnly: 'npm run build',
      },
      dependencies: {},
      devDependencies: {
        typescript: '^5.3.0',
      },
    };
    return JSON.stringify(pkg, null, 2);
  }

  private renderTsConfig(): string {
    const config = {
      compilerOptions: {
        target: 'ES2020',
        module: 'commonjs',
        lib: ['ES2020'],
        declaration: true,
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
      },
      include: ['src/**/*'],
    };
    return JSON.stringify(config, null, 2);
  }

  private renderIndex(gateway: any, tools: Tool[]): string {
    const lines: string[] = [];
    lines.push(`// ${gateway.name} SDK - Generated by almyty`);
    lines.push(`// ${tools.length} tools available`);
    lines.push('');
    lines.push("export { AlmytyClient, ClientConfig } from './client';");
    lines.push("export * from './types';");
    lines.push('');

    for (const tool of tools) {
      const slug = this.slugify(tool.name);
      const funcName = this.toCamelCase(tool.name);
      lines.push(`export { ${funcName} } from './${slug}';`);
    }
    lines.push('');

    // Convenience: create a pre-configured client
    lines.push("import { AlmytyClient, ClientConfig } from './client';");
    lines.push('');
    lines.push('export function createClient(config: ClientConfig): AlmytyClient {');
    lines.push('  return new AlmytyClient(config);');
    lines.push('}');
    lines.push('');

    return lines.join('\n');
  }

  private renderClient(gateway: any): string {
    const lines: string[] = [];
    lines.push(`// HTTP client for ${gateway.name}`);
    lines.push('');
    lines.push('export interface ClientConfig {');
    lines.push('  baseUrl: string;');
    lines.push('  token: string;');
    lines.push('  timeout?: number;');
    lines.push('}');
    lines.push('');
    lines.push('export class AlmytyClient {');
    lines.push('  private baseUrl: string;');
    lines.push('  private token: string;');
    lines.push('  private timeout: number;');
    lines.push('');
    lines.push('  constructor(config: ClientConfig) {');
    lines.push("    this.baseUrl = config.baseUrl.replace(/\\/$/, '');");
    lines.push('    this.token = config.token;');
    lines.push('    this.timeout = config.timeout || 30000;');
    lines.push('  }');
    lines.push('');
    lines.push('  async callTool<T = any>(toolName: string, params: Record<string, any>): Promise<T> {');
    lines.push('    const controller = new AbortController();');
    lines.push('    const timeoutId = setTimeout(() => controller.abort(), this.timeout);');
    lines.push('');
    lines.push('    try {');
    lines.push('      const response = await fetch(');
    lines.push('        `${this.baseUrl}/api/utcp/tools/${toolName}/execute`,');
    lines.push('        {');
    lines.push("          method: 'POST',");
    lines.push('          headers: {');
    lines.push("            'Content-Type': 'application/json',");
    lines.push("            'Authorization': `Bearer ${this.token}`,");
    lines.push('          },');
    lines.push('          body: JSON.stringify(params),');
    lines.push('          signal: controller.signal,');
    lines.push('        },');
    lines.push('      );');
    lines.push('');
    lines.push('      if (!response.ok) {');
    lines.push('        const error = await response.json().catch(() => ({ message: response.statusText }));');
    lines.push('        throw new Error(`API error ${response.status}: ${error.message || response.statusText}`);');
    lines.push('      }');
    lines.push('');
    lines.push('      return response.json();');
    lines.push('    } finally {');
    lines.push('      clearTimeout(timeoutId);');
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
    lines.push('');

    return lines.join('\n');
  }

  private renderTypes(tools: Tool[]): string {
    const lines: string[] = [];
    lines.push('// Generated TypeScript types for tool parameters and responses');
    lines.push('');

    for (const tool of tools) {
      const typeName = this.toPascalCase(tool.name);
      const params = tool.parameters as any;
      const properties = params?.properties || {};
      const required = params?.required || [];

      lines.push(`export interface ${typeName}Params {`);
      for (const [name, schema] of Object.entries(properties)) {
        const paramSchema = schema as any;
        const tsType = this.jsonSchemaToTs(paramSchema);
        const optional = required.includes(name) ? '' : '?';
        if (paramSchema.description) {
          lines.push(`  /** ${paramSchema.description} */`);
        }
        lines.push(`  ${name}${optional}: ${tsType};`);
      }
      lines.push('}');
      lines.push('');
    }

    return lines.join('\n');
  }

  private renderToolModule(tool: Tool): string {
    const funcName = this.toCamelCase(tool.name);
    const typeName = this.toPascalCase(tool.name);
    const slug = this.slugify(tool.name);
    const params = tool.parameters as any;
    const properties = params?.properties || {};
    const required = params?.required || [];

    const lines: string[] = [];
    lines.push(`// ${tool.description || tool.name}`);
    lines.push("import { AlmytyClient } from './client';");
    lines.push('');

    // Inline params type for standalone use
    lines.push(`export interface ${typeName}Params {`);
    for (const [name, schema] of Object.entries(properties)) {
      const paramSchema = schema as any;
      const tsType = this.jsonSchemaToTs(paramSchema);
      const optional = required.includes(name) ? '' : '?';
      if (paramSchema.description) {
        lines.push(`  /** ${paramSchema.description} */`);
      }
      lines.push(`  ${name}${optional}: ${tsType};`);
    }
    lines.push('}');
    lines.push('');

    // Function
    if (tool.description) {
      lines.push(`/** ${tool.description} */`);
    }
    lines.push(`export async function ${funcName}(client: AlmytyClient, params: ${typeName}Params): Promise<any> {`);
    lines.push(`  return client.callTool('${slug}', params);`);
    lines.push('}');
    lines.push('');

    return lines.join('\n');
  }

  // --- Type conversion ---

  private jsonSchemaToTs(schema: any): string {
    if (!schema) return 'any';

    switch (schema.type) {
      case 'string':
        if (schema.enum) return schema.enum.map((v: string) => `'${v}'`).join(' | ');
        return 'string';
      case 'integer':
      case 'number':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'array':
        const itemType = schema.items ? this.jsonSchemaToTs(schema.items) : 'any';
        return `${itemType}[]`;
      case 'object':
        if (schema.properties) {
          const props = Object.entries(schema.properties)
            .map(([k, v]) => `${k}: ${this.jsonSchemaToTs(v as any)}`)
            .join('; ');
          return `{ ${props} }`;
        }
        return 'Record<string, any>';
      default:
        return 'any';
    }
  }

  // --- Helpers ---

  private slugify(name: string): string {
    if (!name) return 'unnamed';
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      || 'unnamed';
  }

  private toCamelCase(name: string): string {
    if (!name) return 'unnamed';
    // If already camelCase, keep it
    if (/^[a-z][a-zA-Z0-9]*$/.test(name)) return name;
    // Convert from snake_case, kebab-case, or PascalCase
    return name
      .replace(/[-_\s]+(.)?/g, (_, c) => c ? c.toUpperCase() : '')
      .replace(/^[A-Z]/, c => c.toLowerCase());
  }

  private toPascalCase(name: string): string {
    const camel = this.toCamelCase(name);
    return camel.charAt(0).toUpperCase() + camel.slice(1);
  }
}
