import { Injectable, Logger, NotFoundException, BadRequestException, Inject, forwardRef } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { ToolStatus } from '../../entities/tool.entity';
import { Tool, ToolType, ToolExecutionMethod } from '../../entities/tool.entity';
import { Operation } from '../../entities/operation.entity';
import { ApiSchema } from '../../entities/api-schema.entity';
import { ToolsService } from './tools.service';

@Injectable()
export class ToolsOperationHelper {
  private readonly logger = new Logger(ToolsOperationHelper.name);

  constructor(
    @InjectRepository(Tool)
    private toolRepository: Repository<Tool>,
    @InjectRepository(Operation)
    private operationRepository: Repository<Operation>,
    @InjectRepository(ApiSchema)
    private apiSchemaRepository: Repository<ApiSchema>,
    @Inject(forwardRef(() => ToolsService))
    private readonly tools: ToolsService,
  ) {}

  async createFromOperation(
    operation: Operation,
    options: {
      name: string;
      description: string;
      organizationId: string;
    }
  ): Promise<Tool> {
    // Load the operation with its API
    const operationWithApi = await this.operationRepository.findOne({
      where: { id: operation.id },
      relations: ['api'],
    });

    if (!operationWithApi) {
      throw new NotFoundException('Operation not found');
    }

    // Generate tool parameters from operation parameters
    const toolParameters = await this.generateToolParametersFromOperation(operationWithApi);

    // Generate tool configuration
    const toolConfiguration = {
      timeout: operationWithApi.timeoutMs || operationWithApi.api?.timeoutMs || 30000,
      retries: operationWithApi.api?.retryAttempts || 3,
      cache: {
        enabled: operationWithApi.type === 'query', // Cache read operations by default
        ttl: 300, // 5 minutes
      },
      rateLimit: operationWithApi.rateLimit || operationWithApi.api?.rateLimits,
    };

    // Create the tool
    const tool = this.toolRepository.create({
      name: options.name,
      description: options.description,
      type: this.mapOperationToToolType(operationWithApi),
      parameters: toolParameters,
      configuration: toolConfiguration,
      organizationId: options.organizationId,
      operationId: operation.id,
      status: ToolStatus.ACTIVE,
      version: '1.0.0',
      createdBy: 'system', // Auto-generated
      metadata: {
        autoGenerated: true,
        sourceOperation: {
          id: operationWithApi.id,
          name: operationWithApi.name,
          method: operationWithApi.method,
          endpoint: operationWithApi.endpoint,
        },
        sourceApi: {
          id: operationWithApi.api.id,
          name: operationWithApi.api.name,
          type: operationWithApi.api.type,
          baseUrl: operationWithApi.api.baseUrl,
        },
      },
    });

    const savedTool = await this.toolRepository.save(tool);

    // Create initial version
    await this.tools.createToolVersion(savedTool, 'Auto-generated from API operation', 'system');

    this.logger.log(`Auto-generated tool '${savedTool.name}' from operation '${operationWithApi.name}'`);

    return savedTool;
  }

  async updateFromOperation(
    toolId: string,
    operation: Operation,
    options: {
      name: string;
      description: string;
      organizationId: string;
    }
  ): Promise<Tool> {
    // Load the existing tool
    const tool = await this.toolRepository.findOne({
      where: { id: toolId },
    });

    if (!tool) {
      throw new NotFoundException('Tool not found');
    }

    // Load the operation with its API
    const operationWithApi = await this.operationRepository.findOne({
      where: { id: operation.id },
      relations: ['api'],
    });

    if (!operationWithApi) {
      throw new NotFoundException('Operation not found');
    }

    // Regenerate tool parameters from operation
    const toolParameters = await this.generateToolParametersFromOperation(operationWithApi);

    // Update tool fields
    tool.description = options.description;
    tool.parameters = toolParameters;
    tool.metadata = {
      ...tool.metadata,
      autoGenerated: true,
      sourceOperation: {
        id: operationWithApi.id,
        name: operationWithApi.name,
        method: operationWithApi.method,
        endpoint: operationWithApi.endpoint,
      },
      sourceApi: {
        id: operationWithApi.api.id,
        name: operationWithApi.api.name,
        type: operationWithApi.api.type,
        baseUrl: operationWithApi.api.baseUrl,
      },
    };

    const updatedTool = await this.toolRepository.save(tool);

    this.logger.log(`Updated tool '${updatedTool.name}' from operation '${operationWithApi.name}'`);

    return updatedTool;
  }

  async generateToolParametersFromOperation(operation: Operation): Promise<Record<string, any>> {
    const parameters: Record<string, any> = {
      type: 'object',
      properties: {},
      required: [],
    };

    // Add path parameters
    if (operation.parameters?.path) {
      Object.entries(operation.parameters.path).forEach(([name, param]: [string, any]) => {
        parameters.properties[name] = {
          type: param.type || 'string',
          description: param.description || `Path parameter: ${name}`,
          ...(param.enum && { enum: param.enum }),
          ...(param.example && { example: param.example }),
        };
        if (param.required) {
          parameters.required.push(name);
        }
      });
    }

    // Add query parameters
    if (operation.parameters?.query) {
      Object.entries(operation.parameters.query).forEach(([name, param]: [string, any]) => {
        parameters.properties[name] = {
          type: param.type || 'string',
          description: param.description || `Query parameter: ${name}`,
          ...(param.enum && { enum: param.enum }),
          ...(param.example && { example: param.example }),
        };
        if (param.required) {
          parameters.required.push(name);
        }
      });
    }

    // GraphQL operations have a different body shape: instead of a
    // single `schema`, the parser emits `body.query` (the GraphQL
    // query string) and `body.variables` (an object whose
    // `properties` map describes each variable). Lift those
    // variables to top-level so the generated SKILL.md surfaces
    // them as proper parameters.
    if (
      operation.parameters?.body?.variables?.properties &&
      typeof operation.parameters.body.variables.properties === 'object'
    ) {
      const vars = operation.parameters.body.variables;
      Object.entries(vars.properties as Record<string, any>).forEach(([name, prop]) => {
        parameters.properties[name] = prop;
      });
      if (Array.isArray(vars.required)) {
        parameters.required.push(...vars.required);
      }
    }

    // Add body parameters
    if (operation.parameters?.body) {
      this.logger.log(`[PARAMS] Body found for ${operation.name}: ${JSON.stringify(operation.parameters.body)}`);

      // Check if body has a schema with $ref
      if (operation.parameters.body.schema) {
        const bodySchema = operation.parameters.body.schema;
        this.logger.log(`[PARAMS] Body schema: ${JSON.stringify(bodySchema)}`);

        // If it's a $ref, resolve it
        if (bodySchema.$ref) {
          this.logger.log(`[PARAMS] Resolving $ref: ${bodySchema.$ref} for API ${operation.apiId}`);
          const resolvedSchema = await this.resolveSchemaRef(bodySchema.$ref, operation.apiId);
          this.logger.log(`[PARAMS] Resolved schema: ${JSON.stringify(resolvedSchema)}`);

          if (resolvedSchema && resolvedSchema.properties) {
            // Flatten the resolved schema properties into tool parameters
            Object.entries(resolvedSchema.properties).forEach(([name, prop]: [string, any]) => {
              parameters.properties[name] = prop;
            });
            if (resolvedSchema.required) {
              parameters.required.push(...resolvedSchema.required);
            }
            this.logger.log(`[PARAMS] Added ${Object.keys(parameters.properties).length} properties from resolved schema`);
          }
        }
        // If schema has properties directly
        else if (bodySchema.properties) {
          Object.entries(bodySchema.properties).forEach(([name, prop]: [string, any]) => {
            parameters.properties[name] = prop;
          });
          if (bodySchema.required) {
            parameters.required.push(...bodySchema.required);
          }
        }
      }
    }

    return parameters;
  }

  async resolveSchemaRef(ref: string, apiId: string): Promise<any> {
    try {
      // Get the API's schema
      const apiSchema = await this.apiSchemaRepository.findOne({
        where: { apiId },
        order: { createdAt: 'DESC' },
      });

      if (!apiSchema || !apiSchema.rawSchema) {
        this.logger.warn(`No schema found for API ${apiId} to resolve $ref: ${ref}`);
        return null;
      }

      // Parse the rawSchema if it's a string
      let schemaObj: any;
      if (typeof apiSchema.rawSchema === 'string') {
        try {
          schemaObj = JSON.parse(apiSchema.rawSchema);
        } catch (error) {
          this.logger.error(`Failed to parse rawSchema: ${error.message}`);
          return null;
        }
      } else {
        schemaObj = apiSchema.rawSchema;
      }

      // Parse the $ref (e.g., "#/definitions/Order" -> ["definitions", "Order"])
      const refPath = ref.replace(/^#\//, '').split('/');

      // Navigate through the schema to find the definition
      let resolvedSchema: any = schemaObj;
      for (const key of refPath) {
        if (resolvedSchema && typeof resolvedSchema === 'object' && key in resolvedSchema) {
          resolvedSchema = resolvedSchema[key];
        } else {
          this.logger.warn(`Failed to resolve $ref ${ref}: path ${key} not found`);
          return null;
        }
      }

      return resolvedSchema || null;
    } catch (error) {
      this.logger.error(`Error resolving $ref ${ref}: ${error.message}`);
      return null;
    }
  }

  mapOperationToToolType(operation: Operation): ToolType {
    switch (operation.method) {
      case 'GET': return ToolType.API;
      case 'POST':
      case 'PUT':
      case 'PATCH': return ToolType.API;
      case 'DELETE': return ToolType.API;
      default: return ToolType.API;
    }
  }

}
