export default {
  index: 'Overview',

  'guides-separator': { type: 'separator', title: 'Step-by-step guides' },
  'customer-support-assistant': 'Customer support assistant',
  'sales-assistant-slack': 'Sales assistant in Slack',
  'website-product-chat': 'Product chat for your website',
  'nightly-systems-report': 'Nightly systems report',
  'internal-help-desk': 'Internal help desk',
  'developers-apis-and-machines': 'For developers',

  'support-separator': { type: 'separator', title: 'Support and sales' },
  'support-ticket-triage': 'Sort tickets, draft replies',
  'docs-deflection-bot': 'Answer from your docs',
  'governed-refund-agent': 'Refunds with safeguards',
  'lead-enrichment-routing': 'Score and route leads',
  'meeting-notes-to-crm': 'Call notes to your CRM',
  'agent-that-remembers': 'An assistant that remembers',

  'ops-separator': { type: 'separator', title: 'Operations, data and finance' },
  'scheduled-monitoring-agent': 'Checks on a schedule',
  'nightly-data-quality-digest': 'Nightly data check',
  'nl-query-your-database': 'Ask your database',
  'stripe-payout-reconciliation': 'Match Stripe payouts',
  'cross-vendor-contract-review': 'Contract review',
  'connect-google-sharepoint': 'Google Drive and SharePoint',

  'governance-separator': { type: 'separator', title: 'Control and compliance' },
  'govern-ai-spend': 'Cap AI spending',
  'approval-policies': 'Who signs off',
  'multi-team-rbac': 'Keep teams separate',
  'sso-scim-onboarding': 'Company sign-in',
  'audit-to-siem': 'Audit trail to your security tools',
  'eu-ai-act-compliance': 'Ready for the EU AI Act',
  'air-gapped-self-host': 'Inside your own network',

  'engineering-separator': { type: 'separator', title: 'Engineering' },
  'give-claude-your-api': 'Your API in a coding assistant',
  'modernize-legacy-soap': 'Modernize an old SOAP service',
  'npm-package-tools': 'A code library as tools',
  'expose-any-machine': 'Work on one of your machines',
  'github-issue-triage': 'Sort GitHub issues',
  'pr-review-bot': 'First pass on pull requests',
  'oncall-alert-triage': 'Summarize on-call alerts',
  'multi-vendor-coding-fleet': 'Several coding assistants',
}
