apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: almyty-dev

namePrefix: dev-

resources:
  - ../../base
  - secret.yaml

patches:
  - target:
      kind: Namespace
      name: almyty
    patch: |-
      - op: replace
        path: /metadata/name
        value: almyty-dev

  - target:
      kind: ConfigMap
      name: almyty-config
    patch: |-
      - op: replace
        path: /data/NODE_ENV
        value: production
      - op: replace
        path: /data/SWAGGER_ENABLED
        value: "true"
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
      - op: replace
        path: /data/CORS_ORIGIN
        value: "https://app.dev.almyty.dev"
      - op: replace
        path: /data/DATABASE_HOST
        value: "dev-almyty-postgres"
      - op: replace
        path: /data/REDIS_HOST
        value: "dev-almyty-redis"
      - op: replace
        path: /data/BASE_URL
        value: "https://api.dev.almyty.dev"

  - target:
      kind: Deployment
      name: api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  # Development uses in-cluster postgres
  - target:
      kind: Deployment
      name: postgres
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Ingress
      name: almyty-ingress
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: dev-letsencrypt-prod
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.dev.almyty.dev
      - op: replace
        path: /spec/tls/0/secretName
        value: api-dev-apif-ai-tls
      - op: replace
        path: /spec/tls/1/hosts/0
        value: app.dev.almyty.dev
      - op: replace
        path: /spec/tls/1/secretName
        value: app-dev-apif-ai-tls
      - op: replace
        path: /spec/rules/0/host
        value: api.dev.almyty.dev
      - op: replace
        path: /spec/rules/1/host
        value: app.dev.almyty.dev

images:
  - name: ghcr.io/frane/almyty/api
    newTag: dev-latest
  - name: ghcr.io/frane/almyty/frontend
    newTag: dev-latest
