import React, { useState, useEffect } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { Code, Search, Plus, Wrench, Server, Plug, MoreHorizontal, CheckCircle2, Building2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { ProtocolBadge } from '@/components/ui/protocol-badge'
import { EmptyState } from '@/components/ui/empty-state'
import { QueryError } from '@/components/ui/query-error'
import { useNewParamRedirect } from '@/hooks/use-new-param-redirect'
import { PageHeader } from '@/components/layout/page-header'
import { pluralized } from '@/lib/utils'
import { Checkbox } from '@/components/ui/checkbox'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from '@/components/ui/dropdown-menu'
import {
  DataTable,
  createActionsColumn,
} from '@/components/ui/data-table'
import { toolsApi } from '@/lib/api'
import { useOrganizationStore } from '@/store/organization'
import { useNotifications } from '@/store/app'
import { TeamFilter, useTeamLookup, VisibilityBadge, filterByTeamVisibility, type TeamFilterValue } from '@/components/ui/team-filter'
import { McpSourcesPanel } from '@/components/tools/mcp-sources-panel'
import { isPublishable } from '@/components/tools/publish-tool-form'
import { ToolHubPage } from '@/pages/tool-hub'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { getApiErrorMessage } from '@/lib/api-error'
import { toolSourceApi, DELETED_API_LABEL } from '@/lib/tool-source'

interface Tool {
  id: string
  name: string
  description?: string
  type: string
  // Read all over this page (the row subtitle) but never
  // declared, so every read went through an `any`. Publishing needs it
  // typed: only an HTTP tool can become a template.
  executionMethod?: string | null
  status: string
  operation?: {
    method?: string
    path?: string
  }
  metadata?: {
    autoGenerated?: boolean
    sourceApi?: {
      id?: string
      name?: string
      type?: string
    }
    sourceOperation?: {
      name?: string
      method?: string
      endpoint?: string
    }
  }
  usage?: {
    total: number
    success: number
  }
  configuration?: {
    timeout?: number
    retries?: number
    cache?: {
      enabled: boolean
    }
  }
  createdAt?: string
  updatedAt?: string
}

export function ToolsPage() {
  const [searchParams, setSearchParams] = useSearchParams()
  const activeTab = searchParams.get('tab') === 'hub' ? 'hub' : 'my-tools'

  useEffect(() => {
    document.title = 'Tools | almyty'
    return () => { document.title = 'almyty' }
  }, [])

  const { currentOrganization } = useOrganizationStore()
  const queryClient = useQueryClient()
  const notifications = useNotifications()
  const navigate = useNavigate()

  const [searchQuery, setSearchQuery] = useState('')
  const [statusFilter, setStatusFilter] = useState('all')
  const [typeFilter, setTypeFilter] = useState('all')
  const [apiFilter, setApiFilter] = useState('all')
  const [teamFilter, setTeamFilter] = useState<TeamFilterValue>('all')
  const { byId: teamLookup } = useTeamLookup(currentOrganization?.id)
  const [page, setPage] = useState(1)
  const PAGE_SIZE = 10
  const [deletingTool, setDeletingTool] = useState<Tool | null>(null)
  // Old ?new=1 links (bookmarks, docs) land on the create page.
  useNewParamRedirect('/tools/new')

  const { data: toolsData, isLoading, isError, error: toolsError, refetch: refetchTools } = useQuery({
    queryKey: ['tools', currentOrganization?.id, page],
    queryFn: () => toolsApi.getAll(currentOrganization?.id, { limit: PAGE_SIZE, page }),
    enabled: !!currentOrganization,
    placeholderData: (prev) => prev, // keep previous data while loading next page
  })

  const deleteToolMutation = useMutation({
    mutationFn: (id: string) => toolsApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tools'] })
      notifications.success('Tool deleted', 'The tool has been removed.')
      setDeletingTool(null)
    },
    onError: (error: any) => {
      notifications.error('Could not delete the tool', getApiErrorMessage(error, 'The tool is still there.'))
    },
  })

  const [selectedToolIds, setSelectedToolIds] = useState<Set<string>>(new Set())

  /*
    Bulk activation, by loop rather than by a new endpoint.

    There is no bulk activate route: POST /organizations/:org/tools/:id/activate
    is the only one. The MCP control plane's `activate_tool` already
    handles `toolIds` the same way -- it loops the single-tool service
    method and reports each id -- so looping here keeps one server-side
    code path, one authorization check per tool and per-tool reasons,
    instead of adding a second route that would have to re-derive all of
    that. An 18-operation import is 18 short requests, which is fine; if
    imports ever run to hundreds, a real bulk route is the change to make.
  */
  const activateToolsMutation = useMutation({
    mutationFn: async (toolIds: string[]) => {
      const orgId = currentOrganization?.id || ''
      const results = await Promise.allSettled(
        toolIds.map((toolId) => toolsApi.activate(toolId, orgId)),
      )
      return {
        activated: results.filter((r) => r.status === 'fulfilled').length,
        failed: results
          .map((r, index) => ({ r, toolId: toolIds[index] }))
          .filter(({ r }) => r.status === 'rejected')
          .map(({ r, toolId }) => ({
            toolId,
            reason: getApiErrorMessage((r as PromiseRejectedResult).reason, 'Activation failed.'),
          })),
      }
    },
    onSuccess: ({ activated, failed }) => {
      queryClient.invalidateQueries({ queryKey: ['tools'] })
      setSelectedToolIds(new Set())
      if (failed.length === 0) {
        notifications.success(
          activated === 1 ? 'Tool activated' : `${activated} tools activated`,
          'Active tools can be assigned to a gateway.',
        )
        return
      }
      const detail = [...new Set(failed.map((f) => f.reason))].slice(0, 2).join(' ')
      if (activated === 0) {
        notifications.error('Could not activate', detail)
      } else {
        notifications.warning(
          `${activated} of ${activated + failed.length} tools activated`,
          detail,
        )
      }
    },
    onError: (error: any) => {
      notifications.error('Could not activate', getApiErrorMessage(error, 'Please try again.'))
    },
  })

  const toolsExtracted = toolsData?.tools || toolsData || []
  const tools = Array.isArray(toolsExtracted) ? toolsExtracted : []
  const toolsTotal = toolsData?.total ?? tools.length
  const totalPages = Math.max(1, Math.ceil(toolsTotal / PAGE_SIZE))

  // Client-side filters applied to the current page of results
  // Note: for full search across all tools, backend search support is needed
  const filteredTools = filterByTeamVisibility(tools as any[], teamFilter).filter((tool: Tool) => {
    const matchesSearch =
      !searchQuery ||
      tool.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (tool.description || '').toLowerCase().includes(searchQuery.toLowerCase()) ||
      (toolSourceApi(tool).name || '').toLowerCase().includes(searchQuery.toLowerCase())

    const matchesStatus = statusFilter === 'all' || tool.status === statusFilter
    const matchesType = typeFilter === 'all' || tool.type === typeFilter
    const matchesApi =
      apiFilter === 'all' || toolSourceApi(tool).name === apiFilter

    return matchesSearch && matchesStatus && matchesType && matchesApi
  })

  // Get unique API sources for filter (from current page only)
  const apiSources = Array.from(
    new Set(
      tools
        .map((t: Tool) => toolSourceApi(t).name)
        .filter(Boolean)
    )
  ) as string[]

  const handleViewDetails = (tool: Tool) => {
    navigate(`/tools/${tool.id}`)
  }

  /*
    Selection is held here rather than inside DataTable because DataTable
    keeps its row selection private and exposes no way to read it, and a
    bulk action needs the ids.
  */
  const visibleSelectedIds = filteredTools
    .filter((tool: Tool) => selectedToolIds.has(tool.id))
    .map((tool: Tool) => tool.id)
  const selectableDraftIds = filteredTools
    .filter((tool: Tool) => tool.status !== 'active')
    .map((tool: Tool) => tool.id)

  const toggleToolSelected = (toolId: string, selected: boolean) =>
    setSelectedToolIds((current) => {
      const next = new Set(current)
      if (selected) next.add(toolId)
      else next.delete(toolId)
      return next
    })

  const columns = [
    {
      id: 'select',
      header: () => (
        <Checkbox
          checked={
            visibleSelectedIds.length > 0 && visibleSelectedIds.length === filteredTools.length
              ? true
              : visibleSelectedIds.length > 0
                ? 'indeterminate'
                : false
          }
          onCheckedChange={(value) =>
            setSelectedToolIds(
              value ? new Set(filteredTools.map((tool: Tool) => tool.id)) : new Set<string>(),
            )
          }
          aria-label="Select all tools"
        />
      ),
      cell: ({ row }: any) => (
        <div onClick={(e) => e.stopPropagation()}>
          <Checkbox
            checked={selectedToolIds.has(row.original.id)}
            onCheckedChange={(value) => toggleToolSelected(row.original.id, !!value)}
            aria-label={`Select ${row.original.name}`}
          />
        </div>
      ),
      enableSorting: false,
      enableHiding: false,
    },
    {
      accessorKey: 'name',
      header: 'Name',
      cell: ({ row }: any) => {
        const tool = row.original
        const isRunnerTool = !!tool.runnerConfig
        const isMcpTool = tool.type === 'mcp'
        return (
          <div className="flex items-center space-x-3">
            <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${isRunnerTool ? 'bg-cyan-500/10' : 'bg-primary/10'}`}>
              {isRunnerTool ? <Server className="h-5 w-5 text-cyan-500" /> : <Code className="h-5 w-5 text-primary" />}
            </div>
            <div className="max-w-[300px]">
              <div className="flex items-center gap-2">
                <span className="font-medium text-primary hover:underline truncate" title={tool.name}>{tool.name}</span>
                {isRunnerTool && (
                  <Badge variant="outline" className="text-cyan-600 border-cyan-300 dark:border-cyan-800 dark:text-cyan-400 shrink-0">
                    runner: {tool.runnerConfig?.runnerName}
                  </Badge>
                )}
                {isMcpTool && (
                  <ProtocolBadge protocol="mcp" className="shrink-0" />
                )}
                <VisibilityBadge
                  visibility={(tool as any).visibility}
                  teamId={(tool as any).teamId}
                  teamLookup={teamLookup}
                />
              </div>
              <div className="text-sm text-muted-foreground truncate">
                {isRunnerTool ? `runner method: ${tool.runnerConfig?.method}` : isMcpTool ? `MCP server: ${tool.metadata?.mcpSource?.name ?? "external"}` : toolSourceApi(tool).name || (tool.type === 'api' ? DELETED_API_LABEL : tool.executionMethod === 'custom' ? 'Custom JavaScript' : tool.executionMethod === 'llm' ? 'Model Tool' : tool.executionMethod === 'graphql' ? 'GraphQL Tool' : tool.executionMethod === 'http' ? 'HTTP Tool' : tool.executionMethod === 'sdk' ? 'SDK Tool' : 'Custom Tool')}
              </div>
            </div>
          </div>
        )
      },
    },
    {
      accessorKey: 'status',
      header: 'Status',
      cell: ({ row }: any) => {
        const status = row.original.status
        const variant = status === 'active' ? 'success' : 'secondary'
        return <Badge variant={variant}>{status === 'active' ? 'Active' : 'Inactive'}</Badge>
      },
    },
    createActionsColumn<Tool>({
      cell: ({ row }: any) => {
        const tool: Tool = row.original
        const isActive = tool.status === 'active'

        return (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" className="h-8 w-8 p-0" onClick={(e) => e.stopPropagation()}>
                <span className="sr-only">Actions</span>
                <MoreHorizontal className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem
                onClick={(e) => {
                  e.stopPropagation()
                  handleViewDetails(tool)
                }}
              >
                View details
              </DropdownMenuItem>
              <DropdownMenuItem
                onClick={(e) => {
                  e.stopPropagation()
                  // The tool's page has the test form (its "Test tool" tab).
                  navigate(`/tools/${tool.id}?tab=test`)
                }}
              >
                Test tool
              </DropdownMenuItem>
              {/*
                Activate, here, on the row.

                Every tool generated from a schema is a draft, and a
                gateway only serves active tools -- so this was the one
                action a new user had to take, and the only place in the
                product that offered it was a toggle on a single tool's
                detail page. An eighteen-operation import meant eighteen
                page visits, and nothing said so.
              */}
              {!isActive && (
                <DropdownMenuItem
                  onClick={(e) => {
                    e.stopPropagation()
                    activateToolsMutation.mutate([tool.id])
                  }}
                >
                  Activate
                </DropdownMenuItem>
              )}
              {/*
                Publish, here, on the row.

                Nothing in the product wrote a tool template, so the Tool
                Hub tab was a permanent empty state. This is the authoring
                path: a working tool becomes a template your organization
                can install anywhere. Offered only for HTTP tools, because
                that is the only shape a template carries back into a tool
                that can execute.
              */}
              {isPublishable(tool) && (
                <DropdownMenuItem
                  onClick={(e) => {
                    e.stopPropagation()
                    navigate(`/tools/${tool.id}/publish`)
                  }}
                >
                  Publish to hub
                </DropdownMenuItem>
              )}
              <DropdownMenuSeparator />
              <DropdownMenuItem
                onClick={(e) => {
                  e.stopPropagation()
                  setDeletingTool(tool)
                }}
              >
                Delete
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        )
      },
    }),
  ]

  if (!currentOrganization) {
    return (
      <EmptyState
        variant="panel"
        icon={Building2}
        title="No organization selected"
        description="Select or create an organization to see its tools."
      />
    )
  }
  return (
    <div className="space-y-6">
      <PageHeader
        title="Tools"
        description={pluralized(toolsTotal, 'tool')}
        actions={
          activeTab === 'my-tools' ? (
            <>
              <Button variant="outline" asChild>
                <Link to="/tools/mcp-servers/new">
                  <Plug className="mr-2 h-4 w-4" />
                  Add MCP server
                </Link>
              </Button>
              <Button asChild>
                <Link to="/tools/new">
                  <Plus className="mr-2 h-4 w-4" />
                  Create tool
                </Link>
              </Button>
            </>
          ) : undefined
        }
      />

      <Tabs value={activeTab} onValueChange={(v) => setSearchParams(v === 'hub' ? { tab: 'hub' } : {})}>
        <TabsList>
          <TabsTrigger value="my-tools">My tools</TabsTrigger>
          <TabsTrigger value="hub">Tool Hub</TabsTrigger>
        </TabsList>
        <TabsContent value="hub">
          <ToolHubPage />
        </TabsContent>
        <TabsContent value="my-tools">

      {/* Connected MCP servers (hidden while none registered) */}
      <McpSourcesPanel organizationId={currentOrganization?.id} />

      {/* Tools Table */}
      {isError ? (
        <QueryError error={toolsError} onRetry={() => refetchTools()} title="Couldn't load tools" />
      ) : !isLoading && tools.length === 0 ? (
        // The sample offer belongs here, on the branch that actually
        // renders: a DataTable emptyState under this branch is never
        // reached, which once left a new user with no way to the sample.
        <EmptyState
          variant="panel"
          icon={Wrench}
          title="No tools yet"
          description="Tools are generated from your APIs. Import an API and its operations appear here."
          action={
            <div className="flex flex-wrap justify-center gap-2">
              <Button asChild>
                <Link to="/apis/new">
                  <Plus className="mr-2 h-4 w-4" />
                  Import API
                </Link>
              </Button>
              <Button variant="outline" asChild>
                <Link to="/tools/new">Create tool</Link>
              </Button>
            </div>
          }
        />
      ) : (
        <Card>
          <CardContent className="pt-6 space-y-4">
            {/*
              Bulk activation bar. Drafts are the normal state of a fresh
              import, so the count of drafts on screen is shown even
              before anything is selected -- that is the fact the product
              used to keep to itself.
            */}
            {(visibleSelectedIds.length > 0 || selectableDraftIds.length > 0) && (
              <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-cyan-500/30 bg-cyan-500/5 p-3">
                <p className="text-sm text-muted-foreground">
                  {visibleSelectedIds.length > 0
                    ? `${visibleSelectedIds.length} selected.`
                    : `${selectableDraftIds.length} tool${selectableDraftIds.length === 1 ? ' is a draft' : 's are drafts'}. A gateway only serves active tools.`}
                </p>
                <div className="flex items-center gap-2">
                  {visibleSelectedIds.length === 0 ? (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setSelectedToolIds(new Set(selectableDraftIds))}
                    >
                      Select the drafts
                    </Button>
                  ) : (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setSelectedToolIds(new Set())}
                    >
                      Clear
                    </Button>
                  )}
                  <Button
                    size="sm"
                    disabled={visibleSelectedIds.length === 0 || activateToolsMutation.isPending}
                    onClick={() => activateToolsMutation.mutate(visibleSelectedIds)}
                  >
                    <CheckCircle2 className="mr-2 h-4 w-4" />
                    {activateToolsMutation.isPending ? 'Activating…' : 'Activate selected'}
                  </Button>
                </div>
              </div>
            )}
            <DataTable
              columns={columns}
              data={filteredTools}
              loading={isLoading}
              onRowClick={(tool) => handleViewDetails(tool)}
              hideSelectionCount
              manualPagination
              pageCount={totalPages}
              pageIndex={page - 1}
              onPageChange={(idx) => setPage(idx + 1)}
              pageSize={PAGE_SIZE}
              headerExtra={
                <div className="flex items-center gap-4 flex-1">
                  <div className="flex-1">
                    <div className="relative">
                      <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                      <Input
                        placeholder="Search current page..."
                        className="pl-10"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                      />
                    </div>
                  </div>
                  <Select value={statusFilter} onValueChange={setStatusFilter}>
                    <SelectTrigger className="w-32">
                      <SelectValue placeholder="Status" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Status</SelectItem>
                      <SelectItem value="active">Active</SelectItem>
                      <SelectItem value="inactive">Inactive</SelectItem>
                    </SelectContent>
                  </Select>
                  <Select value={typeFilter} onValueChange={setTypeFilter}>
                    <SelectTrigger className="w-32" aria-label="Filter by Type">
                      <SelectValue placeholder="Type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Types</SelectItem>
                      <SelectItem value="REST_API">REST</SelectItem>
                      <SelectItem value="GRAPHQL">GraphQL</SelectItem>
                      <SelectItem value="SOAP">SOAP</SelectItem>
                    </SelectContent>
                  </Select>
                  {apiSources.length > 0 && (
                    <Select value={apiFilter} onValueChange={setApiFilter}>
                      <SelectTrigger className="w-48" aria-label="Filter by API">
                        <SelectValue placeholder="Filter by API" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="all">All APIs</SelectItem>
                        {apiSources.map((apiName: string) => (
                          <SelectItem key={apiName} value={apiName}>
                            {apiName}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  )}
                  <TeamFilter
                    organizationId={currentOrganization?.id}
                    value={teamFilter}
                    onChange={setTeamFilter}
                  />
                </div>
              }
            />
          </CardContent>
        </Card>
      )}

      </TabsContent>
      </Tabs>

      {/* Delete Confirmation Dialog */}
      <AlertDialog
        open={!!deletingTool}
        onOpenChange={(open) => !open && setDeletingTool(null)}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete tool?</AlertDialogTitle>
            <AlertDialogDescription>
              This will permanently delete the tool "{deletingTool?.name}". This
              action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                if (deletingTool) {
                  deleteToolMutation.mutate(deletingTool.id)
                }
              }}
              variant="destructive"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

    </div>
  )
}
