import React, { useState, useEffect } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import * as z from 'zod'
import { Code, Search, Play, Copy, Eye, Trash2, ExternalLink, Settings, Plus, Wrench, Server } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { LoadingSpinner } from '@/components/ui/loading-spinner'
import { EmptyState } from '@/components/ui/empty-state'
import { QueryError } from '@/components/ui/query-error'
import { useCreateDeepLink } from '@/hooks/use-create-deep-link'
import { Switch } from '@/components/ui/switch'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from '@/components/ui/dropdown-menu'
import {
  DataTable,
  createSelectColumn,
  createActionsColumn,
  createSortableColumn,
} from '@/components/ui/data-table'
import { toolsApi, llmProvidersApi } from '@/lib/api'
import { useOrganizationStore } from '@/store/organization'
import { useNotifications } from '@/store/app'
import { CreateToolDialog } from '@/components/tools/create-tool-dialog'
import { ToolExecutionDialog } from '@/components/tools/tool-execution-dialog'
import { ToolHubPage } from '@/pages/tool-hub'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { JsonSchemaBuilder } from '@/components/JsonSchemaBuilder'
import CodeMirror from '@uiw/react-codemirror'
import { javascript } from '@codemirror/lang-javascript'
import { json } from '@codemirror/lang-json'
import { autocompletion } from '@codemirror/autocomplete'
import { githubLight } from '@uiw/codemirror-theme-github'
import { useMemo } from 'react'

// Form Schema for manual tool creation
const createToolSchema = z.object({
  name: z.string().min(1, 'Name is required'),
  description: z.string().optional(),
})

type CreateToolForm = z.infer<typeof createToolSchema>

interface Tool {
  id: string
  name: string
  description?: string
  type: string
  status: string
  operation?: {
    method?: string
    path?: string
  }
  metadata?: {
    autoGenerated?: boolean
    sourceApi?: {
      id?: string
      name?: string
      type?: string
    }
    sourceOperation?: {
      name?: string
      method?: string
      endpoint?: string
    }
  }
  usage?: {
    total: number
    success: number
  }
  configuration?: {
    timeout?: number
    retries?: number
    cache?: {
      enabled: boolean
    }
  }
  createdAt?: string
  updatedAt?: string
}

export function ToolsPage() {
  const [searchParams, setSearchParams] = useSearchParams()
  const activeTab = searchParams.get('tab') === 'hub' ? 'hub' : 'my-tools'

  useEffect(() => {
    document.title = 'Tools | almyty'
    return () => { document.title = 'almyty' }
  }, [])

  const { currentOrganization } = useOrganizationStore()
  const queryClient = useQueryClient()
  const notifications = useNotifications()
  const navigate = useNavigate()

  const [searchQuery, setSearchQuery] = useState('')
  const [statusFilter, setStatusFilter] = useState('all')
  const [typeFilter, setTypeFilter] = useState('all')
  const [apiFilter, setApiFilter] = useState('all')
  const [page, setPage] = useState(1)
  const PAGE_SIZE = 10
  const [selectedTool, setSelectedTool] = useState<Tool | null>(null)
  const [deletingTool, setDeletingTool] = useState<Tool | null>(null)
  const [toolForSettings, setToolForSettings] = useState<Tool | null>(null)
  const [toolForExecution, setToolForExecution] = useState<Tool | null>(null)
  const [isDetailsDialogOpen, setIsDetailsDialogOpen] = useState(false)
  const [isSettingsDialogOpen, setIsSettingsDialogOpen] = useState(false)
  const [isExecutionDialogOpen, setIsExecutionDialogOpen] = useState(false)
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false)
  // Honour ?new=1 from the command palette Create Tool action.
  useCreateDeepLink(setIsCreateDialogOpen)
  const [executionParameters, setExecutionParameters] = useState<Record<string, any>>({})
  const [executionResult, setExecutionResult] = useState<any>(null)
  const [toolParameters, setToolParameters] = useState<any>({ type: 'object', properties: {} })
  const [toolCode, setToolCode] = useState('')
  const [executionMethod, setExecutionMethod] = useState<'http' | 'graphql' | 'soap' | 'grpc' | 'custom' | 'llm' | 'sdk'>('http')
  const [sdkConfig, setSdkConfig] = useState<any>(null)
  const [llmConfig, setLlmConfig] = useState({
    providerId: '',
    promptTemplate: '',
    systemPrompt: '',
    model: '',
    maxTokens: 1024,
    temperature: 0.7,
    outputMode: 'text' as 'text' | 'json',
    outputSchema: '',
  })

  // Create parameter autocomplete extension for CodeMirror
  const parameterAutocomplete = useMemo(() => {
    const paramNames = Object.keys(toolParameters.properties || {});
    return autocompletion({
      override: [
        (context) => {
          const word = context.matchBefore(/\w*/);
          if (!word || (word.from === word.to && !context.explicit)) return null;

          return {
            from: word.from,
            options: paramNames.map((name) => ({
              label: name,
              type: 'variable',
              detail: toolParameters.properties[name]?.type || 'parameter',
              info: toolParameters.properties[name]?.description || '',
            })),
          };
        },
      ],
    });
  }, [toolParameters])
  const [httpConfig, setHttpConfig] = useState({
    method: 'GET',
    url: '',
    headers: {},
    body: '',
  })
  const [graphqlConfig, setGraphqlConfig] = useState({
    endpoint: '',
    query: '',
    variables: '',
  })
  const [soapConfig, setSoapConfig] = useState({
    wsdlUrl: '',
    operation: '',
  })
  const [grpcConfig, setGrpcConfig] = useState({
    serviceUrl: '',
    method: '',
    protoFile: '',
  })
  const [authConfig, setAuthConfig] = useState({
    type: 'none',
    apiKey: '',
    bearerToken: '',
    username: '',
    password: '',
  })

  const createForm = useForm<CreateToolForm>({
    resolver: zodResolver(createToolSchema),
    defaultValues: {
      name: '',
      description: '',
    },
  })

  const { data: toolsData, isLoading, isError, error: toolsError, refetch: refetchTools } = useQuery({
    queryKey: ['tools', currentOrganization?.id, page],
    queryFn: () => toolsApi.getAll(currentOrganization?.id, { limit: PAGE_SIZE, page }),
    enabled: !!currentOrganization,
    placeholderData: (prev) => prev, // keep previous data while loading next page
  })

  const { data: providersData } = useQuery({
    queryKey: ['llm-providers'],
    queryFn: () => llmProvidersApi.getAll(),
    enabled: !!currentOrganization,
  })
  const llmProvidersExtracted = providersData?.providers || providersData || []
  const llmProviders = Array.isArray(llmProvidersExtracted) ? llmProvidersExtracted : []
  const activeProviders = llmProviders.filter((p: any) => p.status === 'active' || p.isActive)

  const deleteToolMutation = useMutation({
    mutationFn: (id: string) => toolsApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tools'] })
      notifications.success('Success', 'Tool deleted successfully')
      setDeletingTool(null)
    },
    onError: (error: any) => {
      notifications.error('Error', error.message || 'Failed to delete tool')
    },
  })

  // Fetch available APIs for linking HTTP tools
  const { data: apisData } = useQuery({
    queryKey: ['apis', currentOrganization?.id],
    queryFn: () => import('@/lib/api').then(m => m.apisApi.getAll()),
    enabled: !!currentOrganization,
  })
  const apisExtracted = apisData?.apis || apisData || []
  const availableApis = Array.isArray(apisExtracted) ? apisExtracted : []

  const createToolMutation = useMutation({
    mutationFn: (data: any) => {
      let code = undefined;

      if (executionMethod === 'custom') {
        // Custom JavaScript: user writes their own code, no auto-generation
        code = toolCode;
      } else if (executionMethod === 'graphql') {
        code = `
// axios is available as a global — no require needed
// Parameters available as variables
const response = await axios.post('${graphqlConfig.endpoint}', {
  query: \`${graphqlConfig.query}\`,
  variables: parameters
});
return response;
`;
      } else if (executionMethod === 'soap') {
        code = `
// soap is available as a global — no require needed
const client = await soap.createClientAsync('${soapConfig.wsdlUrl}');
// Parameters available as variables
const result = await client.${soapConfig.operation}Async(parameters);
return result;
`;
      } else if (executionMethod === 'grpc') {
        code = `
const grpc = require('@grpc/grpc-js');
const protoLoader = require('@grpc/proto-loader');

// Load proto definition
const packageDefinition = protoLoader.loadSync('${grpcConfig.protoFile}', {});
const protoDescriptor = grpc.loadPackageDefinition(packageDefinition);

// Create client
const client = new protoDescriptor.${grpcConfig.method.split('/')[0]}('${grpcConfig.serviceUrl}', grpc.credentials.createInsecure());

// Call method
return new Promise((resolve, reject) => {
  client.${grpcConfig.method.split('/')[1]}(parameters, (error, response) => {
    if (error) reject(error);
    else resolve(response);
  });
});
`;
      }
      // HTTP: no code generation — uses httpConfig instead

      // Auto-assign tool type based on execution method
      let type = 'function';
      if (executionMethod === 'http') {
        type = ['POST', 'PUT', 'PATCH', 'DELETE'].includes(httpConfig.method) ? 'action' : 'query';
      } else if (executionMethod === 'graphql') {
        type = graphqlConfig.query.trim().startsWith('mutation') ? 'mutation' : 'query';
      } else if (executionMethod === 'sdk') {
        type = 'function';
      }

      // Build LLM config if LLM execution method
      let llmConfigPayload = undefined;
      if (executionMethod === 'llm') {
        llmConfigPayload = {
          providerId: llmConfig.providerId,
          promptTemplate: llmConfig.promptTemplate,
          systemPrompt: llmConfig.systemPrompt || undefined,
          model: llmConfig.model || undefined,
          maxTokens: llmConfig.maxTokens,
          temperature: llmConfig.temperature,
          outputMode: llmConfig.outputMode,
          outputSchema: llmConfig.outputMode === 'json' && llmConfig.outputSchema
            ? JSON.parse(llmConfig.outputSchema)
            : undefined,
        };
      }

      // Build httpConfig payload for HTTP tools (structured, no code)
      let httpConfigPayload = undefined;
      if (executionMethod === 'http') {
        httpConfigPayload = {
          method: httpConfig.method,
          path: httpConfig.url,
          bodyEncoding: ['POST', 'PUT', 'PATCH'].includes(httpConfig.method) ? undefined : undefined,
          bodyTemplate: httpConfig.body || undefined,
          headers: httpConfig.headers && Object.keys(httpConfig.headers).length > 0 ? httpConfig.headers : undefined,
        };
      }

      const payload: any = {
        ...data,
        type,
        parameters: toolParameters,
        executionMethod,
        llmConfig: llmConfigPayload,
      };

      // HTTP tools: send httpConfig, no code
      if (executionMethod === 'http') {
        payload.httpConfig = httpConfigPayload;
      } else if (executionMethod === 'sdk') {
        // SDK tools: send sdkConfig, no code
        payload.sdkConfig = sdkConfig;
      } else {
        // All other methods that generate code
        payload.code = code;
      }

      return toolsApi.create(payload, currentOrganization?.id);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tools'] })
      notifications.success('Success', 'Tool created successfully')
      setIsCreateDialogOpen(false)
      createForm.reset()
      setToolParameters({ type: 'object', properties: {} })
      setToolCode('')
      setHttpConfig({ method: 'GET', url: '', headers: {}, body: '' })
      setSdkConfig(null)
      setExecutionMethod('http')
    },
    onError: (error: any) => {
      notifications.error('Error', error.response?.data?.message || 'Failed to create tool')
    },
  })

  const executeToolMutation = useMutation({
    mutationFn: ({ id, parameters }: { id: string; parameters: Record<string, any> }) =>
      toolsApi.execute(id, { parameters }, currentOrganization?.id || ''),
    onSuccess: (response: any) => {
      setExecutionResult(response)
      if (response.success) {
        notifications.success('Success', 'Tool executed successfully')
      } else {
        notifications.error('Execution Failed', response.error || 'Tool execution failed')
      }
    },
    onError: (error: any) => {
      notifications.error('Error', error.message || 'Failed to execute tool')
      setExecutionResult({
        success: false,
        error: error.message || 'Failed to execute tool',
      })
    },
  })

  const toolsExtracted = toolsData?.tools || toolsData || []
  const tools = Array.isArray(toolsExtracted) ? toolsExtracted : []
  const toolsTotal = toolsData?.total ?? tools.length
  const totalPages = Math.max(1, Math.ceil(toolsTotal / PAGE_SIZE))

  // Client-side filters applied to the current page of results
  // Note: for full search across all tools, backend search support is needed
  const filteredTools = tools.filter((tool: Tool) => {
    const matchesSearch =
      !searchQuery ||
      tool.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (tool.description || '').toLowerCase().includes(searchQuery.toLowerCase()) ||
      (tool.metadata?.sourceApi?.name || '').toLowerCase().includes(searchQuery.toLowerCase())

    const matchesStatus = statusFilter === 'all' || tool.status === statusFilter
    const matchesType = typeFilter === 'all' || tool.type === typeFilter
    const matchesApi =
      apiFilter === 'all' || tool.metadata?.sourceApi?.name === apiFilter

    return matchesSearch && matchesStatus && matchesType && matchesApi
  })

  // Get unique API sources for filter (from current page only)
  const apiSources = Array.from(
    new Set(
      tools
        .map((t: Tool) => t.metadata?.sourceApi?.name)
        .filter(Boolean)
    )
  ) as string[]

  const handleCopyEndpoint = (tool: Tool) => {
    const endpoint = tool.metadata?.sourceOperation?.endpoint || tool.operation?.path || '/unknown'
    navigator.clipboard.writeText(endpoint)
    notifications.success('Copied', 'Endpoint copied to clipboard')
  }

  const handleViewDetails = (tool: Tool) => {
    navigate(`/tools/${tool.id}`)
  }

  const columns = [
    {
      accessorKey: 'name',
      header: 'Name',
      cell: ({ row }: any) => {
        const tool = row.original
        const isRunnerTool = !!tool.runnerConfig
        return (
          <div className="flex items-center space-x-3">
            <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${isRunnerTool ? 'bg-cyan-500/10' : 'bg-primary/10'}`}>
              {isRunnerTool ? <Server className="h-5 w-5 text-cyan-500" /> : <Code className="h-5 w-5 text-primary" />}
            </div>
            <div className="max-w-[300px]">
              <div className="flex items-center gap-2">
                <span className="font-medium text-primary hover:underline truncate" title={tool.name}>{tool.name}</span>
                {isRunnerTool && (
                  <Badge variant="outline" className="text-cyan-600 border-cyan-300 dark:border-cyan-800 dark:text-cyan-400 shrink-0">
                    runner: {tool.runnerConfig?.runnerName}
                  </Badge>
                )}
              </div>
              <div className="text-sm text-muted-foreground truncate">
                {isRunnerTool ? `runner method: ${tool.runnerConfig?.method}` : tool.metadata?.sourceApi?.name || (tool.type === 'api' ? 'Unknown API' : tool.executionMethod === 'custom' ? 'Custom JavaScript' : tool.executionMethod === 'llm' ? 'LLM Tool' : tool.executionMethod === 'graphql' ? 'GraphQL Tool' : tool.executionMethod === 'http' ? 'HTTP Tool' : tool.executionMethod === 'sdk' ? 'SDK Tool' : 'Custom Tool')}
              </div>
            </div>
          </div>
        )
      },
    },
    {
      accessorKey: 'status',
      header: 'Status',
      cell: ({ row }: any) => {
        const status = row.original.status
        const variant = status === 'active' ? 'success' : 'secondary'
        return <Badge variant={variant}>{status === 'active' ? 'Active' : 'Inactive'}</Badge>
      },
    },
    createActionsColumn<Tool>(
      (tool) => handleViewDetails(tool),
      (tool) => setDeletingTool(tool),
      [
        {
          label: 'View Details',
          onClick: (tool) => handleViewDetails(tool),
        },
        {
          label: 'Test Tool',
          onClick: (tool) => {
            setToolForExecution(tool)
            setExecutionParameters({})
            setExecutionResult(null)
            setIsExecutionDialogOpen(true)
          },
        },
      ]
    ),
  ]

  if (!currentOrganization) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="text-center">
          <p className="text-muted-foreground">No organization context</p>
        </div>
      </div>
    )
  }

  if (isError) {
    return <QueryError error={toolsError} onRetry={() => refetchTools()} title="Couldn't load tools" />
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-4xl font-heading font-extrabold tracking-tight bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text text-transparent">Tools</h1>
          <p className="text-muted-foreground">
            {toolsTotal} tool{toolsTotal !== 1 ? 's' : ''} total
          </p>
        </div>
        {activeTab === 'my-tools' && (
          <Button onClick={() => setIsCreateDialogOpen(true)} disabled={!currentOrganization}>
            <Plus className="mr-2 h-4 w-4" />
            Create Tool
          </Button>
        )}
      </div>

      <Tabs value={activeTab} onValueChange={(v) => setSearchParams(v === 'hub' ? { tab: 'hub' } : {})}>
        <TabsList>
          <TabsTrigger value="my-tools">My Tools</TabsTrigger>
          <TabsTrigger value="hub">Tool Hub</TabsTrigger>
        </TabsList>
        <TabsContent value="hub">
          <ToolHubPage />
        </TabsContent>
        <TabsContent value="my-tools">

      {/* Tools Table */}
      {tools.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-16">
            <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mb-4">
              <Code className="h-8 w-8 text-primary" />
            </div>
            <h3 className="text-xl font-semibold mb-2">No tools</h3>
            <p className="text-muted-foreground mb-6 text-center max-w-md">
              Generate tools from API schemas automatically. Create your first tool by importing an API.
            </p>
            <Button size="lg" asChild>
              <a href="/apis">
                <Plus className="mr-2 h-4 w-4" />
                Go to APIs
              </a>
            </Button>
          </CardContent>
        </Card>
      ) : (
        <Card>
          <CardContent className="pt-6 space-y-4">
            <DataTable
              columns={columns}
              data={filteredTools}
              loading={isLoading}
              onRowClick={(tool) => handleViewDetails(tool)}
              hideSelectionCount
              emptyState={
                tools.length === 0 ? (
                  <EmptyState
                    icon={Wrench}
                    title="No tools yet"
                    description="Tools are what your agents call. Import an API to auto-generate tools from its operations, or create one by hand for an HTTP endpoint, GraphQL query, JavaScript script, or LLM prompt."
                    action={
                      <Button onClick={() => setIsCreateDialogOpen(true)}>
                        <Plus className="h-4 w-4 mr-2" />
                        Create Tool
                      </Button>
                    }
                    className="py-16"
                  />
                ) : undefined
              }
              manualPagination
              pageCount={totalPages}
              pageIndex={page - 1}
              onPageChange={(idx) => setPage(idx + 1)}
              pageSize={PAGE_SIZE}
              headerExtra={
                <div className="flex items-center gap-4 flex-1">
                  <div className="flex-1">
                    <div className="relative">
                      <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                      <Input
                        placeholder="Search current page..."
                        className="pl-10"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                      />
                    </div>
                  </div>
                  <Select value={statusFilter} onValueChange={setStatusFilter}>
                    <SelectTrigger className="w-32">
                      <SelectValue placeholder="Status" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Status</SelectItem>
                      <SelectItem value="active">Active</SelectItem>
                      <SelectItem value="inactive">Inactive</SelectItem>
                    </SelectContent>
                  </Select>
                  <Select value={typeFilter} onValueChange={setTypeFilter}>
                    <SelectTrigger className="w-32" aria-label="Filter by Type">
                      <SelectValue placeholder="Type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Types</SelectItem>
                      <SelectItem value="REST_API">REST</SelectItem>
                      <SelectItem value="GRAPHQL">GraphQL</SelectItem>
                      <SelectItem value="SOAP">SOAP</SelectItem>
                    </SelectContent>
                  </Select>
                  {apiSources.length > 0 && (
                    <Select value={apiFilter} onValueChange={setApiFilter}>
                      <SelectTrigger className="w-48" aria-label="Filter by API">
                        <SelectValue placeholder="Filter by API" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="all">All APIs</SelectItem>
                        {apiSources.map((apiName: string) => (
                          <SelectItem key={apiName} value={apiName}>
                            {apiName}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  )}
                </div>
              }
            />
          </CardContent>
        </Card>
      )}

      </TabsContent>
      </Tabs>

      {/* Tool Details Dialog */}
      <Dialog open={isDetailsDialogOpen} onOpenChange={setIsDetailsDialogOpen}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-3">
              <Code className="h-5 w-5" />
              {selectedTool?.name}
            </DialogTitle>
            <DialogDescription>
              {selectedTool?.description || 'AI tool generated from API operation'}
            </DialogDescription>
          </DialogHeader>

          {selectedTool && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <h4 className="text-sm font-medium mb-2">Source API</h4>
                  <div className="text-sm space-y-1">
                    <div>
                      <span className="text-muted-foreground">API: </span>
                      {selectedTool.metadata?.sourceApi?.name || 'Unknown'}
                    </div>
                    <div>
                      <span className="text-muted-foreground">Type: </span>
                      {selectedTool.metadata?.sourceApi?.type || 'Unknown'}
                    </div>
                    <div>
                      <span className="text-muted-foreground">Operation: </span>
                      {selectedTool.metadata?.sourceOperation?.name || 'Unknown'}
                    </div>
                    <div>
                      <span className="text-muted-foreground">Method: </span>
                      <Badge className="font-mono">
                        {selectedTool.metadata?.sourceOperation?.method ||
                          selectedTool.operation?.method ||
                          'GET'}
                      </Badge>
                    </div>
                    <div>
                      <span className="text-muted-foreground">Endpoint: </span>
                      <code className="text-xs bg-muted px-1 py-0.5 rounded">
                        {selectedTool.metadata?.sourceOperation?.endpoint ||
                          selectedTool.operation?.path ||
                          'Unknown'}
                      </code>
                    </div>
                  </div>
                </div>

                <div>
                  <h4 className="text-sm font-medium mb-2">Configuration</h4>
                  <div className="text-sm space-y-1">
                    <div>
                      <span className="text-muted-foreground">Status: </span>
                      <Badge
                        variant={
                          selectedTool.status === 'active' ? 'success' : 'secondary'
                        }
                      >
                        {selectedTool.status}
                      </Badge>
                    </div>
                    <div>
                      <span className="text-muted-foreground">Timeout: </span>
                      {selectedTool.configuration?.timeout || 30000}ms
                    </div>
                    <div>
                      <span className="text-muted-foreground">Retries: </span>
                      {selectedTool.configuration?.retries || 3}
                    </div>
                    <div>
                      <span className="text-muted-foreground">Cache: </span>
                      {selectedTool.configuration?.cache?.enabled
                        ? 'Enabled'
                        : 'Disabled'}
                    </div>
                    <div>
                      <span className="text-muted-foreground">Auto-generated: </span>
                      {selectedTool.metadata?.autoGenerated ? 'Yes' : 'No'}
                    </div>
                  </div>
                </div>
              </div>

              <div className="border-t pt-4">
                <h4 className="text-sm font-medium mb-2">Assigned Gateways</h4>
                <div className="flex gap-2 flex-wrap">
                  {(selectedTool as any)?.gatewayAssociations?.length > 0 ? (
                    (selectedTool as any).gatewayAssociations.map((assoc: any) => (
                      <Badge key={assoc.id} variant="secondary">
                        {assoc.gateway?.name || 'Unknown'} ({assoc.gateway?.type?.toUpperCase() || 'N/A'})
                      </Badge>
                    ))
                  ) : (
                    <p className="text-sm text-muted-foreground">
                      Not assigned to any gateway. Go to <a href="/gateways" className="underline">Gateways page</a> to assign this tool.
                    </p>
                  )}
                </div>
              </div>

              <div className="flex gap-2 pt-4 border-t">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => handleCopyEndpoint(selectedTool)}
                >
                  <Copy className="h-3 w-3 mr-1" />
                  Copy Endpoint
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => {
                    // Execute tool with empty parameters for quick test
                    if (selectedTool) {
                      executeToolMutation.mutate({
                        id: selectedTool.id,
                        parameters: {}
                      })
                    }
                  }}
                  disabled={executeToolMutation.isPending}
                >
                  <Play className="h-3 w-3 mr-1" />
                  {executeToolMutation.isPending ? 'Testing...' : 'Test Tool'}
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => {
                    // Close details dialog and open execution dialog to show parameters
                    setIsDetailsDialogOpen(false)
                    setToolForExecution(selectedTool)
                    setIsExecutionDialogOpen(true)
                  }}
                >
                  <ExternalLink className="h-3 w-3 mr-1" />
                  View Parameters
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Tool Settings Dialog */}
      <Dialog open={isSettingsDialogOpen} onOpenChange={setIsSettingsDialogOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-3">
              <Settings className="h-5 w-5" />
              Tool Settings
            </DialogTitle>
            <DialogDescription>
              Configure {toolForSettings?.name} execution settings
            </DialogDescription>
          </DialogHeader>

          {toolForSettings && (
            <div className="space-y-6">
              <div className="space-y-4">
                <div>
                  <h4 className="text-sm font-medium mb-3">Execution Configuration</h4>
                  <div className="space-y-4">
                    <div>
                      <label className="text-sm font-medium">Timeout (ms)</label>
                      <Input
                        type="number"
                        defaultValue={toolForSettings.configuration?.timeout || 30000}
                        className="mt-1"
                        placeholder="30000"
                      />
                      <p className="text-xs text-muted-foreground mt-1">
                        Maximum time in milliseconds to wait for tool execution
                      </p>
                    </div>

                    <div>
                      <label className="text-sm font-medium">Retries</label>
                      <Input
                        type="number"
                        defaultValue={toolForSettings.configuration?.retries || 3}
                        className="mt-1"
                        min="0"
                        max="10"
                        placeholder="3"
                      />
                      <p className="text-xs text-muted-foreground mt-1">
                        Number of retry attempts on failure
                      </p>
                    </div>

                    <div>
                      <label className="text-sm font-medium">Rate Limit (requests/min)</label>
                      <Input
                        type="number"
                        defaultValue={60}
                        className="mt-1"
                        min="1"
                        placeholder="60"
                      />
                      <p className="text-xs text-muted-foreground mt-1">
                        Maximum number of requests per minute
                      </p>
                    </div>
                  </div>
                </div>

                <div className="border-t pt-4">
                  <h4 className="text-sm font-medium mb-3">Caching</h4>
                  <div className="flex items-center justify-between">
                    <div>
                      <label className="text-sm font-medium">Enable Cache</label>
                      <p className="text-xs text-muted-foreground">
                        Cache successful responses for faster repeated requests
                      </p>
                    </div>
                    <Switch
                      defaultChecked={toolForSettings.configuration?.cache?.enabled}
                    />
                  </div>
                  <div className="mt-3">
                    <label className="text-sm font-medium">Cache TTL (seconds)</label>
                    <Input
                      type="number"
                      defaultValue={300}
                      className="mt-1"
                      placeholder="300"
                    />
                  </div>
                </div>

                <div className="border-t pt-4">
                  <h4 className="text-sm font-medium mb-3">Authentication</h4>
                  <Select defaultValue="inherit">
                    <SelectTrigger>
                      <SelectValue placeholder="Select authentication" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="inherit">Inherit from API</SelectItem>
                      <SelectItem value="none">None</SelectItem>
                      <SelectItem value="bearer">Bearer Token</SelectItem>
                      <SelectItem value="api-key">API Key</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-4 border-t">
                <Button
                  variant="outline"
                  onClick={() => setIsSettingsDialogOpen(false)}
                >
                  Cancel
                </Button>
                <Button onClick={() => {
                  notifications.success('Settings Updated', 'Tool configuration saved successfully')
                  setIsSettingsDialogOpen(false)
                }}>
                  Save Settings
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Tool Execution Dialog */}
      <ToolExecutionDialog
        open={isExecutionDialogOpen}
        onOpenChange={setIsExecutionDialogOpen}
        toolForExecution={toolForExecution}
        executionParameters={executionParameters}
        onExecutionParametersChange={setExecutionParameters}
        executionResult={executionResult}
        executeToolMutation={executeToolMutation}
      />


      {/* Delete Confirmation Dialog */}
      <AlertDialog
        open={!!deletingTool}
        onOpenChange={(open) => !open && setDeletingTool(null)}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Are you sure?</AlertDialogTitle>
            <AlertDialogDescription>
              This will permanently delete the tool "{deletingTool?.name}". This
              action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                if (deletingTool) {
                  deleteToolMutation.mutate(deletingTool.id)
                }
              }}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Create Tool Dialog */}
      <CreateToolDialog
        open={isCreateDialogOpen}
        onOpenChange={setIsCreateDialogOpen}
        createForm={createForm}
        createToolMutation={createToolMutation}
        executionMethod={executionMethod}
        onExecutionMethodChange={(v) => setExecutionMethod(v as 'http' | 'graphql' | 'soap' | 'grpc' | 'custom' | 'llm' | 'sdk')}
        toolParameters={toolParameters}
        onToolParametersChange={setToolParameters}
        toolCode={toolCode}
        onToolCodeChange={setToolCode}
        httpConfig={httpConfig}
        onHttpConfigChange={setHttpConfig}
        graphqlConfig={graphqlConfig}
        onGraphqlConfigChange={setGraphqlConfig}
        soapConfig={soapConfig}
        onSoapConfigChange={setSoapConfig}
        grpcConfig={grpcConfig}
        onGrpcConfigChange={setGrpcConfig}
        authConfig={authConfig}
        onAuthConfigChange={setAuthConfig}
        llmConfig={llmConfig}
        onLlmConfigChange={setLlmConfig}
        activeProviders={activeProviders}
        availableApis={availableApis}
        sdkConfig={sdkConfig}
        onSdkConfigChange={setSdkConfig}
      />
    </div>
  )
}
