import React, { useState, useEffect } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Code, Search, Play, Copy, Eye, Trash2, ExternalLink, Settings, Plus, Wrench, Server, Plug, MoreHorizontal, CheckCircle2, Building2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { ProtocolBadge } from '@/components/ui/protocol-badge'
import { LoadingSpinner } from '@/components/ui/loading-spinner'
import { EmptyState } from '@/components/ui/empty-state'
import { QueryError } from '@/components/ui/query-error'
import { useCreateDeepLink } from '@/hooks/use-create-deep-link'
import { PageHeader } from '@/components/layout/page-header'
import { PageIntro } from '@/components/onboarding/page-intro'
import { pluralized } from '@/lib/utils'
import { Switch } from '@/components/ui/switch'
import { Checkbox } from '@/components/ui/checkbox'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from '@/components/ui/dropdown-menu'
import {
  DataTable,
  createSelectColumn,
  createActionsColumn,
  createSortableColumn,
} from '@/components/ui/data-table'
import { toolsApi } from '@/lib/api'
import { useOrganizationStore } from '@/store/organization'
import { useNotifications } from '@/store/app'
import { TeamFilter, useTeamLookup, VisibilityBadge, filterByTeamVisibility, type TeamFilterValue } from '@/components/ui/team-filter'
import { CreateToolDialog } from '@/components/tools/create-tool-dialog'
import { AddMcpServerDialog } from '@/components/tools/add-mcp-server-dialog'
import { McpSourcesPanel } from '@/components/tools/mcp-sources-panel'
import { ToolExecutionDialog } from '@/components/tools/tool-execution-dialog'
import { PublishToolDialog, isPublishable } from '@/components/tools/publish-tool-dialog'
import { ToolHubPage } from '@/pages/tool-hub'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { JsonSchemaBuilder } from '@/components/JsonSchemaBuilder'
import CodeMirror from '@uiw/react-codemirror'
import { javascript } from '@codemirror/lang-javascript'
import { json } from '@codemirror/lang-json'
import { autocompletion } from '@codemirror/autocomplete'
import { githubLight } from '@uiw/codemirror-theme-github'
import { useMemo } from 'react'

// Form Schema for manual tool creation
import { createToolSchema, type CreateToolForm } from '@/components/tools/schema'
import { getApiErrorMessage } from '@/lib/api-error'
import { toolSourceApi, DELETED_API_LABEL } from '@/lib/tool-source'

interface Tool {
  id: string
  name: string
  description?: string
  type: string
  // Read all over this page (row subtitle, detail dialog) but never
  // declared, so every read went through an `any`. Publishing needs it
  // typed: only an HTTP tool can become a template.
  executionMethod?: string | null
  status: string
  operation?: {
    method?: string
    path?: string
  }
  metadata?: {
    autoGenerated?: boolean
    sourceApi?: {
      id?: string
      name?: string
      type?: string
    }
    sourceOperation?: {
      name?: string
      method?: string
      endpoint?: string
    }
  }
  usage?: {
    total: number
    success: number
  }
  configuration?: {
    timeout?: number
    retries?: number
    cache?: {
      enabled: boolean
    }
  }
  createdAt?: string
  updatedAt?: string
}

export function ToolsPage() {
  const [searchParams, setSearchParams] = useSearchParams()
  const activeTab = searchParams.get('tab') === 'hub' ? 'hub' : 'my-tools'

  useEffect(() => {
    document.title = 'Tools | almyty'
    return () => { document.title = 'almyty' }
  }, [])

  const { currentOrganization } = useOrganizationStore()
  const queryClient = useQueryClient()
  const notifications = useNotifications()
  const navigate = useNavigate()

  const [searchQuery, setSearchQuery] = useState('')
  const [statusFilter, setStatusFilter] = useState('all')
  const [typeFilter, setTypeFilter] = useState('all')
  const [apiFilter, setApiFilter] = useState('all')
  const [teamFilter, setTeamFilter] = useState<TeamFilterValue>('all')
  const { byId: teamLookup } = useTeamLookup(currentOrganization?.id)
  const [page, setPage] = useState(1)
  const PAGE_SIZE = 10
  const [selectedTool, setSelectedTool] = useState<Tool | null>(null)
  const [deletingTool, setDeletingTool] = useState<Tool | null>(null)
  const [publishingTool, setPublishingTool] = useState<Tool | null>(null)
  const [toolForExecution, setToolForExecution] = useState<Tool | null>(null)
  const [isDetailsDialogOpen, setIsDetailsDialogOpen] = useState(false)
  const [isExecutionDialogOpen, setIsExecutionDialogOpen] = useState(false)
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false)
  const [isAddMcpDialogOpen, setIsAddMcpDialogOpen] = useState(false)
  // Honour ?new=1 from the command palette Create Tool action.
  useCreateDeepLink(setIsCreateDialogOpen)
  const [executionParameters, setExecutionParameters] = useState<Record<string, any>>({})
  const [executionResult, setExecutionResult] = useState<any>(null)
  const [toolParameters, setToolParameters] = useState<any>({ type: 'object', properties: {} })
  const [toolCode, setToolCode] = useState('')
  const [executionMethod, setExecutionMethod] = useState<'http' | 'graphql' | 'soap' | 'grpc' | 'custom' | 'llm' | 'sdk'>('http')
  const [sdkConfig, setSdkConfig] = useState<any>(null)
  const [llmConfig, setLlmConfig] = useState({
    providerId: '',
    promptTemplate: '',
    systemPrompt: '',
    model: '',
    maxTokens: 1024,
    temperature: 0.7,
    outputMode: 'text' as 'text' | 'json',
    outputSchema: '',
  })

  // Create parameter autocomplete extension for CodeMirror
  const parameterAutocomplete = useMemo(() => {
    const paramNames = Object.keys(toolParameters.properties || {});
    return autocompletion({
      override: [
        (context) => {
          const word = context.matchBefore(/\w*/);
          if (!word || (word.from === word.to && !context.explicit)) return null;

          return {
            from: word.from,
            options: paramNames.map((name) => ({
              label: name,
              type: 'variable',
              detail: toolParameters.properties[name]?.type || 'parameter',
              info: toolParameters.properties[name]?.description || '',
            })),
          };
        },
      ],
    });
  }, [toolParameters])
  const [httpConfig, setHttpConfig] = useState({
    method: 'GET',
    url: '',
    headers: {},
    body: '',
  })
  const [graphqlConfig, setGraphqlConfig] = useState({
    endpoint: '',
    query: '',
    variables: '',
  })
  const [soapConfig, setSoapConfig] = useState({
    wsdlUrl: '',
    operation: '',
  })
  const [grpcConfig, setGrpcConfig] = useState({
    serviceUrl: '',
    method: '',
    protoFile: '',
  })
  const [authConfig, setAuthConfig] = useState({
    type: 'none',
    apiKey: '',
    bearerToken: '',
    username: '',
    password: '',
  })

  const createForm = useForm<CreateToolForm>({
    resolver: zodResolver(createToolSchema),
    defaultValues: {
      name: '',
      description: '',
    },
  })

  const { data: toolsData, isLoading, isError, error: toolsError, refetch: refetchTools } = useQuery({
    queryKey: ['tools', currentOrganization?.id, page],
    queryFn: () => toolsApi.getAll(currentOrganization?.id, { limit: PAGE_SIZE, page }),
    enabled: !!currentOrganization,
    placeholderData: (prev) => prev, // keep previous data while loading next page
  })

  const deleteToolMutation = useMutation({
    mutationFn: (id: string) => toolsApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tools'] })
      notifications.success('Tool deleted', 'The tool has been removed.')
      setDeletingTool(null)
    },
    onError: (error: any) => {
      notifications.error('Could not delete the tool', getApiErrorMessage(error, 'The tool is still there.'))
    },
  })

  const [selectedToolIds, setSelectedToolIds] = useState<Set<string>>(new Set())

  /*
    Bulk activation, by loop rather than by a new endpoint.

    There is no bulk activate route: POST /organizations/:org/tools/:id/activate
    is the only one. The MCP control plane's `activate_tool` already
    handles `toolIds` the same way -- it loops the single-tool service
    method and reports each id -- so looping here keeps one server-side
    code path, one authorization check per tool and per-tool reasons,
    instead of adding a second route that would have to re-derive all of
    that. An 18-operation import is 18 short requests, which is fine; if
    imports ever run to hundreds, a real bulk route is the change to make.
  */
  const activateToolsMutation = useMutation({
    mutationFn: async (toolIds: string[]) => {
      const orgId = currentOrganization?.id || ''
      const results = await Promise.allSettled(
        toolIds.map((toolId) => toolsApi.activate(toolId, orgId)),
      )
      return {
        activated: results.filter((r) => r.status === 'fulfilled').length,
        failed: results
          .map((r, index) => ({ r, toolId: toolIds[index] }))
          .filter(({ r }) => r.status === 'rejected')
          .map(({ r, toolId }) => ({
            toolId,
            reason: getApiErrorMessage((r as PromiseRejectedResult).reason, 'Activation failed.'),
          })),
      }
    },
    onSuccess: ({ activated, failed }) => {
      queryClient.invalidateQueries({ queryKey: ['tools'] })
      setSelectedToolIds(new Set())
      if (failed.length === 0) {
        notifications.success(
          activated === 1 ? 'Tool activated' : `${activated} tools activated`,
          'Active tools can be assigned to a gateway.',
        )
        return
      }
      const detail = [...new Set(failed.map((f) => f.reason))].slice(0, 2).join(' ')
      if (activated === 0) {
        notifications.error('Could not activate', detail)
      } else {
        notifications.warning(
          `${activated} of ${activated + failed.length} tools activated`,
          detail,
        )
      }
    },
    onError: (error: any) => {
      notifications.error('Could not activate', getApiErrorMessage(error, 'Please try again.'))
    },
  })

  // Fetch available APIs for linking HTTP tools
  const { data: apisData } = useQuery({
    queryKey: ['apis', currentOrganization?.id],
    queryFn: () => import('@/lib/api').then(m => m.apisApi.getAll()),
    enabled: !!currentOrganization,
  })
  const apisExtracted = apisData?.apis || apisData || []
  const availableApis = Array.isArray(apisExtracted) ? apisExtracted : []

  const createToolMutation = useMutation({
    mutationFn: (data: any) => {
      let code = undefined;

      if (executionMethod === 'custom') {
        // Custom JavaScript: user writes their own code, no auto-generation
        code = toolCode;
      } else if (executionMethod === 'graphql') {
        code = `
// axios is available as a global — no require needed
// Parameters available as variables
const response = await axios.post('${graphqlConfig.endpoint}', {
  query: \`${graphqlConfig.query}\`,
  variables: parameters
});
return response;
`;
      } else if (executionMethod === 'soap') {
        code = `
// soap is available as a global — no require needed
const client = await soap.createClientAsync('${soapConfig.wsdlUrl}');
// Parameters available as variables
const result = await client.${soapConfig.operation}Async(parameters);
return result;
`;
      } else if (executionMethod === 'grpc') {
        code = `
const grpc = require('@grpc/grpc-js');
const protoLoader = require('@grpc/proto-loader');

// Load proto definition
const packageDefinition = protoLoader.loadSync('${grpcConfig.protoFile}', {});
const protoDescriptor = grpc.loadPackageDefinition(packageDefinition);

// Create client
const client = new protoDescriptor.${grpcConfig.method.split('/')[0]}('${grpcConfig.serviceUrl}', grpc.credentials.createInsecure());

// Call method
return new Promise((resolve, reject) => {
  client.${grpcConfig.method.split('/')[1]}(parameters, (error, response) => {
    if (error) reject(error);
    else resolve(response);
  });
});
`;
      }
      // HTTP: no code generation — uses httpConfig instead

      // Auto-assign tool type based on execution method
      let type = 'function';
      if (executionMethod === 'http') {
        type = ['POST', 'PUT', 'PATCH', 'DELETE'].includes(httpConfig.method) ? 'action' : 'query';
      } else if (executionMethod === 'graphql') {
        type = graphqlConfig.query.trim().startsWith('mutation') ? 'mutation' : 'query';
      } else if (executionMethod === 'sdk') {
        type = 'function';
      }

      // Build LLM config if LLM execution method
      let llmConfigPayload = undefined;
      if (executionMethod === 'llm') {
        llmConfigPayload = {
          providerId: llmConfig.providerId,
          promptTemplate: llmConfig.promptTemplate,
          systemPrompt: llmConfig.systemPrompt || undefined,
          model: llmConfig.model || undefined,
          maxTokens: llmConfig.maxTokens,
          temperature: llmConfig.temperature,
          outputMode: llmConfig.outputMode,
          outputSchema: llmConfig.outputMode === 'json' && llmConfig.outputSchema
            ? JSON.parse(llmConfig.outputSchema)
            : undefined,
        };
      }

      // Build httpConfig payload for HTTP tools (structured, no code)
      let httpConfigPayload = undefined;
      if (executionMethod === 'http') {
        httpConfigPayload = {
          method: httpConfig.method,
          path: httpConfig.url,
          bodyEncoding: ['POST', 'PUT', 'PATCH'].includes(httpConfig.method) ? undefined : undefined,
          bodyTemplate: httpConfig.body || undefined,
          headers: httpConfig.headers && Object.keys(httpConfig.headers).length > 0 ? httpConfig.headers : undefined,
        };
      }

      // The Authentication block was collected, rendered, and never
      // sent, so every hand-built HTTP tool executed unauthenticated --
      // and there is no tool edit UI, so it could not be added later
      // either. The backend stores it nested (`{ type, config }`), while
      // the form holds it flat, hence the reshape.
      const inlineAuth =
        authConfig.type === 'bearer' && authConfig.bearerToken
          ? { type: 'bearer', config: { token: authConfig.bearerToken } }
          : authConfig.type === 'apiKey' && authConfig.apiKey
            ? { type: 'apiKey', config: { key: authConfig.apiKey, headerName: 'X-API-Key' } }
            : authConfig.type === 'basic' && authConfig.username
              ? { type: 'basic', config: { username: authConfig.username, password: authConfig.password } }
              : null;

      const payload: any = {
        ...data,
        type,
        parameters: toolParameters,
        executionMethod,
        llmConfig: llmConfigPayload,
        ...(inlineAuth ? { authConfig: inlineAuth } : {}),
      };

      // HTTP tools: send httpConfig, no code
      if (executionMethod === 'http') {
        payload.httpConfig = httpConfigPayload;
      } else if (executionMethod === 'sdk') {
        // SDK tools: send sdkConfig, no code
        payload.sdkConfig = sdkConfig;
      } else {
        // All other methods that generate code
        payload.code = code;
      }

      return toolsApi.create(payload, currentOrganization?.id);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tools'] })
      notifications.success('Tool created', 'It is ready to assign to a gateway.')
      setIsCreateDialogOpen(false)
      createForm.reset()
      setToolParameters({ type: 'object', properties: {} })
      setToolCode('')
      setHttpConfig({ method: 'GET', url: '', headers: {}, body: '' })
      setSdkConfig(null)
      setExecutionMethod('http')
    },
    onError: (error: any) => {
      const msg = getApiErrorMessage(error, 'Failed to create tool')
      notifications.error('Error', msg)
    },
  })

  const executeToolMutation = useMutation({
    mutationFn: ({ id, parameters }: { id: string; parameters: Record<string, any> }) =>
      toolsApi.execute(id, { parameters }, currentOrganization?.id || ''),
    onSuccess: (response: any) => {
      setExecutionResult(response)
      if (response.success) {
        notifications.success('Tool executed', 'The run finished successfully.')
      } else {
        notifications.error('Execution Failed', response.error || 'Tool execution failed')
      }
    },
    onError: (error: any) => {
      notifications.error('Error', error.message || 'Failed to execute tool')
      setExecutionResult({
        success: false,
        error: error.message || 'Failed to execute tool',
      })
    },
  })

  const toolsExtracted = toolsData?.tools || toolsData || []
  const tools = Array.isArray(toolsExtracted) ? toolsExtracted : []
  const toolsTotal = toolsData?.total ?? tools.length
  const totalPages = Math.max(1, Math.ceil(toolsTotal / PAGE_SIZE))

  // Client-side filters applied to the current page of results
  // Note: for full search across all tools, backend search support is needed
  const filteredTools = filterByTeamVisibility(tools as any[], teamFilter).filter((tool: Tool) => {
    const matchesSearch =
      !searchQuery ||
      tool.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (tool.description || '').toLowerCase().includes(searchQuery.toLowerCase()) ||
      (toolSourceApi(tool).name || '').toLowerCase().includes(searchQuery.toLowerCase())

    const matchesStatus = statusFilter === 'all' || tool.status === statusFilter
    const matchesType = typeFilter === 'all' || tool.type === typeFilter
    const matchesApi =
      apiFilter === 'all' || toolSourceApi(tool).name === apiFilter

    return matchesSearch && matchesStatus && matchesType && matchesApi
  })

  // Get unique API sources for filter (from current page only)
  const apiSources = Array.from(
    new Set(
      tools
        .map((t: Tool) => toolSourceApi(t).name)
        .filter(Boolean)
    )
  ) as string[]

  const handleCopyEndpoint = (tool: Tool) => {
    const endpoint = tool.metadata?.sourceOperation?.endpoint || tool.operation?.path || '/unknown'
    navigator.clipboard.writeText(endpoint)
    notifications.success('Copied', 'Endpoint copied to clipboard')
  }

  const handleViewDetails = (tool: Tool) => {
    navigate(`/tools/${tool.id}`)
  }

  /*
    Selection is held here rather than inside DataTable because DataTable
    keeps its row selection private and exposes no way to read it, and a
    bulk action needs the ids.
  */
  const visibleSelectedIds = filteredTools
    .filter((tool: Tool) => selectedToolIds.has(tool.id))
    .map((tool: Tool) => tool.id)
  const selectableDraftIds = filteredTools
    .filter((tool: Tool) => tool.status !== 'active')
    .map((tool: Tool) => tool.id)

  const toggleToolSelected = (toolId: string, selected: boolean) =>
    setSelectedToolIds((current) => {
      const next = new Set(current)
      if (selected) next.add(toolId)
      else next.delete(toolId)
      return next
    })

  const columns = [
    {
      id: 'select',
      header: () => (
        <Checkbox
          checked={
            visibleSelectedIds.length > 0 && visibleSelectedIds.length === filteredTools.length
              ? true
              : visibleSelectedIds.length > 0
                ? 'indeterminate'
                : false
          }
          onCheckedChange={(value) =>
            setSelectedToolIds(
              value ? new Set(filteredTools.map((tool: Tool) => tool.id)) : new Set<string>(),
            )
          }
          aria-label="Select all tools"
        />
      ),
      cell: ({ row }: any) => (
        <div onClick={(e) => e.stopPropagation()}>
          <Checkbox
            checked={selectedToolIds.has(row.original.id)}
            onCheckedChange={(value) => toggleToolSelected(row.original.id, !!value)}
            aria-label={`Select ${row.original.name}`}
          />
        </div>
      ),
      enableSorting: false,
      enableHiding: false,
    },
    {
      accessorKey: 'name',
      header: 'Name',
      cell: ({ row }: any) => {
        const tool = row.original
        const isRunnerTool = !!tool.runnerConfig
        const isMcpTool = tool.type === 'mcp'
        return (
          <div className="flex items-center space-x-3">
            <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${isRunnerTool ? 'bg-cyan-500/10' : 'bg-primary/10'}`}>
              {isRunnerTool ? <Server className="h-5 w-5 text-cyan-500" /> : <Code className="h-5 w-5 text-primary" />}
            </div>
            <div className="max-w-[300px]">
              <div className="flex items-center gap-2">
                <span className="font-medium text-primary hover:underline truncate" title={tool.name}>{tool.name}</span>
                {isRunnerTool && (
                  <Badge variant="outline" className="text-cyan-600 border-cyan-300 dark:border-cyan-800 dark:text-cyan-400 shrink-0">
                    runner: {tool.runnerConfig?.runnerName}
                  </Badge>
                )}
                {isMcpTool && (
                  <ProtocolBadge protocol="mcp" className="shrink-0" />
                )}
                <VisibilityBadge
                  visibility={(tool as any).visibility}
                  teamId={(tool as any).teamId}
                  teamLookup={teamLookup}
                />
              </div>
              <div className="text-sm text-muted-foreground truncate">
                {isRunnerTool ? `runner method: ${tool.runnerConfig?.method}` : isMcpTool ? `MCP server: ${tool.metadata?.mcpSource?.name ?? "external"}` : toolSourceApi(tool).name || (tool.type === 'api' ? DELETED_API_LABEL : tool.executionMethod === 'custom' ? 'Custom JavaScript' : tool.executionMethod === 'llm' ? 'Model Tool' : tool.executionMethod === 'graphql' ? 'GraphQL Tool' : tool.executionMethod === 'http' ? 'HTTP Tool' : tool.executionMethod === 'sdk' ? 'SDK Tool' : 'Custom Tool')}
              </div>
            </div>
          </div>
        )
      },
    },
    {
      accessorKey: 'status',
      header: 'Status',
      cell: ({ row }: any) => {
        const status = row.original.status
        const variant = status === 'active' ? 'success' : 'secondary'
        return <Badge variant={variant}>{status === 'active' ? 'Active' : 'Inactive'}</Badge>
      },
    },
    createActionsColumn<Tool>({
      cell: ({ row }: any) => {
        const tool: Tool = row.original
        const isActive = tool.status === 'active'

        return (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" className="h-8 w-8 p-0" onClick={(e) => e.stopPropagation()}>
                <span className="sr-only">Actions</span>
                <MoreHorizontal className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem
                onClick={(e) => {
                  e.stopPropagation()
                  handleViewDetails(tool)
                }}
              >
                View details
              </DropdownMenuItem>
              <DropdownMenuItem
                onClick={(e) => {
                  e.stopPropagation()
                  setToolForExecution(tool)
                  setExecutionParameters({})
                  setExecutionResult(null)
                  setIsExecutionDialogOpen(true)
                }}
              >
                Test tool
              </DropdownMenuItem>
              {/*
                Activate, here, on the row.

                Every tool generated from a schema is a draft, and a
                gateway only serves active tools -- so this was the one
                action a new user had to take, and the only place in the
                product that offered it was a toggle on a single tool's
                detail page. An eighteen-operation import meant eighteen
                page visits, and nothing said so.
              */}
              {!isActive && (
                <DropdownMenuItem
                  onClick={(e) => {
                    e.stopPropagation()
                    activateToolsMutation.mutate([tool.id])
                  }}
                >
                  Activate
                </DropdownMenuItem>
              )}
              {/*
                Publish, here, on the row.

                Nothing in the product wrote a tool template, so the Tool
                Hub tab was a permanent empty state. This is the authoring
                path: a working tool becomes a template your organization
                can install anywhere. Offered only for HTTP tools, because
                that is the only shape a template carries back into a tool
                that can execute.
              */}
              {isPublishable(tool) && (
                <DropdownMenuItem
                  onClick={(e) => {
                    e.stopPropagation()
                    setPublishingTool(tool)
                  }}
                >
                  Publish to hub
                </DropdownMenuItem>
              )}
              <DropdownMenuSeparator />
              <DropdownMenuItem
                onClick={(e) => {
                  e.stopPropagation()
                  setDeletingTool(tool)
                }}
              >
                Delete
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        )
      },
    }),
  ]

  if (!currentOrganization) {
    return (
      <EmptyState
        variant="panel"
        icon={Building2}
        title="No organization selected"
        description="Select or create an organization to see its tools."
      />
    )
  }
  return (
    <div className="space-y-6">
      <PageHeader
        title="Tools"
        description={pluralized(toolsTotal, 'tool')}
        actions={
          activeTab === 'my-tools' ? (
            <>
              <Button
                variant="outline"
                onClick={() => setIsAddMcpDialogOpen(true)}
                disabled={!currentOrganization}
              >
                <Plug className="mr-2 h-4 w-4" />
                Add MCP server
              </Button>
              <Button onClick={() => setIsCreateDialogOpen(true)} disabled={!currentOrganization}>
                <Plus className="mr-2 h-4 w-4" />
                Create tool
              </Button>
            </>
          ) : undefined
        }
      />
      <PageIntro topic="tools" />

      <Tabs value={activeTab} onValueChange={(v) => setSearchParams(v === 'hub' ? { tab: 'hub' } : {})}>
        <TabsList>
          <TabsTrigger value="my-tools">My tools</TabsTrigger>
          <TabsTrigger value="hub">Tool Hub</TabsTrigger>
        </TabsList>
        <TabsContent value="hub">
          <ToolHubPage />
        </TabsContent>
        <TabsContent value="my-tools">

      {/* Connected MCP servers (hidden while none registered) */}
      <McpSourcesPanel organizationId={currentOrganization?.id} />

      {/* Tools Table */}
      {isError ? (
        <QueryError error={toolsError} onRetry={() => refetchTools()} title="Couldn't load tools" />
      ) : !isLoading && tools.length === 0 ? (
        // The sample offer belongs here, on the branch that actually
        // renders: a DataTable emptyState under this branch is never
        // reached, which once left a new user with no way to the sample.
        <EmptyState
          variant="panel"
          icon={Wrench}
          title="No tools yet"
          description="Tools are generated from your APIs. Import an API and its operations appear here."
          action={
            <Button onClick={() => navigate('/apis?new=1')}>
              <Plus className="mr-2 h-4 w-4" />
              Import API
            </Button>
          }
        />
      ) : (
        <Card>
          <CardContent className="pt-6 space-y-4">
            {/*
              Bulk activation bar. Drafts are the normal state of a fresh
              import, so the count of drafts on screen is shown even
              before anything is selected -- that is the fact the product
              used to keep to itself.
            */}
            {(visibleSelectedIds.length > 0 || selectableDraftIds.length > 0) && (
              <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-cyan-500/30 bg-cyan-500/5 p-3">
                <p className="text-sm text-muted-foreground">
                  {visibleSelectedIds.length > 0
                    ? `${visibleSelectedIds.length} selected.`
                    : `${selectableDraftIds.length} tool${selectableDraftIds.length === 1 ? ' is a draft' : 's are drafts'}. A gateway only serves active tools.`}
                </p>
                <div className="flex items-center gap-2">
                  {visibleSelectedIds.length === 0 ? (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setSelectedToolIds(new Set(selectableDraftIds))}
                    >
                      Select the drafts
                    </Button>
                  ) : (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setSelectedToolIds(new Set())}
                    >
                      Clear
                    </Button>
                  )}
                  <Button
                    size="sm"
                    disabled={visibleSelectedIds.length === 0 || activateToolsMutation.isPending}
                    onClick={() => activateToolsMutation.mutate(visibleSelectedIds)}
                  >
                    <CheckCircle2 className="mr-2 h-4 w-4" />
                    {activateToolsMutation.isPending ? 'Activating…' : 'Activate selected'}
                  </Button>
                </div>
              </div>
            )}
            <DataTable
              columns={columns}
              data={filteredTools}
              loading={isLoading}
              onRowClick={(tool) => handleViewDetails(tool)}
              hideSelectionCount
              manualPagination
              pageCount={totalPages}
              pageIndex={page - 1}
              onPageChange={(idx) => setPage(idx + 1)}
              pageSize={PAGE_SIZE}
              headerExtra={
                <div className="flex items-center gap-4 flex-1">
                  <div className="flex-1">
                    <div className="relative">
                      <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                      <Input
                        placeholder="Search current page..."
                        className="pl-10"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                      />
                    </div>
                  </div>
                  <Select value={statusFilter} onValueChange={setStatusFilter}>
                    <SelectTrigger className="w-32">
                      <SelectValue placeholder="Status" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Status</SelectItem>
                      <SelectItem value="active">Active</SelectItem>
                      <SelectItem value="inactive">Inactive</SelectItem>
                    </SelectContent>
                  </Select>
                  <Select value={typeFilter} onValueChange={setTypeFilter}>
                    <SelectTrigger className="w-32" aria-label="Filter by Type">
                      <SelectValue placeholder="Type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Types</SelectItem>
                      <SelectItem value="REST_API">REST</SelectItem>
                      <SelectItem value="GRAPHQL">GraphQL</SelectItem>
                      <SelectItem value="SOAP">SOAP</SelectItem>
                    </SelectContent>
                  </Select>
                  {apiSources.length > 0 && (
                    <Select value={apiFilter} onValueChange={setApiFilter}>
                      <SelectTrigger className="w-48" aria-label="Filter by API">
                        <SelectValue placeholder="Filter by API" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="all">All APIs</SelectItem>
                        {apiSources.map((apiName: string) => (
                          <SelectItem key={apiName} value={apiName}>
                            {apiName}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  )}
                  <TeamFilter
                    organizationId={currentOrganization?.id}
                    value={teamFilter}
                    onChange={setTeamFilter}
                  />
                </div>
              }
            />
          </CardContent>
        </Card>
      )}

      </TabsContent>
      </Tabs>

      {/* Tool Details Dialog */}
      <Dialog open={isDetailsDialogOpen} onOpenChange={setIsDetailsDialogOpen}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-3">
              <Code className="h-5 w-5" />
              {selectedTool?.name}
            </DialogTitle>
            <DialogDescription>
              {selectedTool?.description || 'AI tool generated from API operation'}
            </DialogDescription>
          </DialogHeader>

          {selectedTool && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <h4 className="text-sm font-medium mb-2">Source API</h4>
                  <div className="text-sm space-y-1">
                    <div>
                      <span className="text-muted-foreground">API: </span>
                      {toolSourceApi(selectedTool).name || DELETED_API_LABEL}
                    </div>
                    <div>
                      <span className="text-muted-foreground">Type: </span>
                      {selectedTool.metadata?.sourceApi?.type || 'Unknown'}
                    </div>
                    <div>
                      <span className="text-muted-foreground">Operation: </span>
                      {selectedTool.metadata?.sourceOperation?.name || 'Unknown'}
                    </div>
                    <div>
                      <span className="text-muted-foreground">Method: </span>
                      <Badge className="font-mono">
                        {selectedTool.metadata?.sourceOperation?.method ||
                          selectedTool.operation?.method ||
                          'GET'}
                      </Badge>
                    </div>
                    <div>
                      <span className="text-muted-foreground">Endpoint: </span>
                      <code className="text-xs bg-muted px-1 py-0.5 rounded">
                        {selectedTool.metadata?.sourceOperation?.endpoint ||
                          selectedTool.operation?.path ||
                          'Unknown'}
                      </code>
                    </div>
                  </div>
                </div>

                <div>
                  <h4 className="text-sm font-medium mb-2">Configuration</h4>
                  <div className="text-sm space-y-1">
                    <div>
                      <span className="text-muted-foreground">Status: </span>
                      <Badge
                        variant={
                          selectedTool.status === 'active' ? 'success' : 'secondary'
                        }
                      >
                        {selectedTool.status}
                      </Badge>
                    </div>
                    <div>
                      <span className="text-muted-foreground">Timeout: </span>
                      {selectedTool.configuration?.timeout || 30000}ms
                    </div>
                    <div>
                      <span className="text-muted-foreground">Retries: </span>
                      {selectedTool.configuration?.retries || 3}
                    </div>
                    <div>
                      <span className="text-muted-foreground">Cache: </span>
                      {selectedTool.configuration?.cache?.enabled
                        ? 'Enabled'
                        : 'Disabled'}
                    </div>
                    <div>
                      <span className="text-muted-foreground">Auto-generated: </span>
                      {selectedTool.metadata?.autoGenerated ? 'Yes' : 'No'}
                    </div>
                  </div>
                </div>
              </div>

              <div className="border-t pt-4">
                <h4 className="text-sm font-medium mb-2">Assigned Gateways</h4>
                <div className="flex gap-2 flex-wrap">
                  {(selectedTool as any)?.gatewayAssociations?.length > 0 ? (
                    (selectedTool as any).gatewayAssociations.map((assoc: any) => (
                      <Badge key={assoc.id} variant="secondary">
                        {assoc.gateway?.name || 'Unknown'} ({assoc.gateway?.type?.toUpperCase() || 'N/A'})
                      </Badge>
                    ))
                  ) : (
                    <p className="text-sm text-muted-foreground">
                      Not assigned to any gateway. Go to <a href="/gateways" className="underline">Gateways page</a> to assign this tool.
                    </p>
                  )}
                </div>
              </div>

              <div className="flex gap-2 pt-4 border-t">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => handleCopyEndpoint(selectedTool)}
                >
                  <Copy className="h-3 w-3 mr-1" />
                  Copy endpoint
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => {
                    // Execute tool with empty parameters for quick test
                    if (selectedTool) {
                      executeToolMutation.mutate({
                        id: selectedTool.id,
                        parameters: {}
                      })
                    }
                  }}
                  disabled={executeToolMutation.isPending}
                >
                  <Play className="h-3 w-3 mr-1" />
                  {executeToolMutation.isPending ? 'Testing...' : 'Test tool'}
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => {
                    // Close details dialog and open execution dialog to show parameters
                    setIsDetailsDialogOpen(false)
                    setToolForExecution(selectedTool)
                    setIsExecutionDialogOpen(true)
                  }}
                >
                  <ExternalLink className="h-3 w-3 mr-1" />
                  View parameters
                </Button>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Tool Settings Dialog */}
      {/* The Tool Settings dialog lived here. It could never open --
          nothing ever called setIsSettingsDialogOpen(true) -- and if it
          had, every field was uncontrolled and "Save Settings" only
          raised a success toast: no mutation, no request. A dialog that
          reports success without saving is worse than a missing one,
          because the person believes the setting took. Timeout, retries,
          rate limit, cache and per-tool auth genuinely have no UI; that
          is now visibly true rather than faked. */}

      {/* Tool Execution Dialog */}
      <ToolExecutionDialog
        open={isExecutionDialogOpen}
        onOpenChange={setIsExecutionDialogOpen}
        toolForExecution={toolForExecution}
        executionParameters={executionParameters}
        onExecutionParametersChange={setExecutionParameters}
        executionResult={executionResult}
        executeToolMutation={executeToolMutation}
      />

      <PublishToolDialog
        tool={publishingTool}
        onOpenChange={(open) => !open && setPublishingTool(null)}
      />

      {/* Delete Confirmation Dialog */}
      <AlertDialog
        open={!!deletingTool}
        onOpenChange={(open) => !open && setDeletingTool(null)}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete tool?</AlertDialogTitle>
            <AlertDialogDescription>
              This will permanently delete the tool "{deletingTool?.name}". This
              action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                if (deletingTool) {
                  deleteToolMutation.mutate(deletingTool.id)
                }
              }}
              variant="destructive"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Create Tool Dialog */}
      <CreateToolDialog
        open={isCreateDialogOpen}
        onOpenChange={(open) => {
          setIsCreateDialogOpen(open)
          if (!open) {
            createForm.reset()
            createToolMutation.reset()
            setToolParameters({ type: 'object', properties: {} })
            setToolCode('')
            setHttpConfig({ method: 'GET', url: '', headers: {}, body: '' })
            setSdkConfig(null)
            setExecutionMethod('http')
          }
        }}
        createForm={createForm}
        createToolMutation={createToolMutation}
        executionMethod={executionMethod}
        onExecutionMethodChange={(v) => setExecutionMethod(v as 'http' | 'graphql' | 'soap' | 'grpc' | 'custom' | 'llm' | 'sdk')}
        toolParameters={toolParameters}
        onToolParametersChange={setToolParameters}
        toolCode={toolCode}
        onToolCodeChange={setToolCode}
        httpConfig={httpConfig}
        onHttpConfigChange={setHttpConfig}
        graphqlConfig={graphqlConfig}
        onGraphqlConfigChange={setGraphqlConfig}
        soapConfig={soapConfig}
        onSoapConfigChange={setSoapConfig}
        grpcConfig={grpcConfig}
        onGrpcConfigChange={setGrpcConfig}
        authConfig={authConfig}
        onAuthConfigChange={setAuthConfig}
        llmConfig={llmConfig}
        onLlmConfigChange={setLlmConfig}
        availableApis={availableApis}
        sdkConfig={sdkConfig}
        onSdkConfigChange={setSdkConfig}
      />

      {/* Add MCP Server Dialog */}
      <AddMcpServerDialog
        open={isAddMcpDialogOpen}
        onOpenChange={setIsAddMcpDialogOpen}
        organizationId={currentOrganization?.id}
      />
    </div>
  )
}
