import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { In, Repository } from 'typeorm';

import { Agent, AgentPipelineNode } from '../../entities/agent.entity';
import { AgentRun } from '../../entities/agent-run.entity';
import { AgentFile } from '../../entities/file.entity';
import { ApprovalRequest, ApprovalStatus } from '../../entities/approval-request.entity';
import { LlmProvider } from '../../entities/llm-provider.entity';
import { Organization } from '../../entities/organization.entity';
import { Tool } from '../../entities/tool.entity';
import { AgentsService } from './agents.service';
import { AgentConstraintsService } from '../agent-constraints/agent-constraints.service';
import { BUILT_IN_TOOLS } from './agent-runtime.service';

// ── Document shape ──

export interface TechDocModelEntry {
  /** Where this model reference lives on the agent. */
  source: string;
  providerId: string | null;
  providerName: string | null;
  providerType: string | null;
  model: string | null;
  temperature: number | null;
  maxTokens: number | null;
}

export interface TechDocToolEntry {
  id: string;
  name: string | null;
  type: string | null;
  description: string | null;
  /** Name of the source API for auto-generated tools, if any. */
  apiSource: string | null;
  /** Where the agent references this tool (agent tool list / pipeline node). */
  referencedBy: string[];
}

export interface TechDocBuiltInToolEntry {
  name: string;
  description: string;
}

export interface AgentTechnicalDocumentation {
  documentType: 'agent-technical-documentation';
  standard: 'EU AI Act Annex IV (informative mapping)';
  generatedAt: string;
  generalDescription: {
    id: string;
    name: string;
    description: string | null;
    purpose: string | null;
    mode: 'workflow' | 'autonomous';
    status: string;
    version: string;
    organization: { id: string; name: string | null };
    visibility: string | null;
    createdAt: Date | null;
    updatedAt: Date | null;
  };
  modelAndProviders: {
    models: TechDocModelEntry[];
    providers: Array<{ id: string; name: string; type: string }>;
    contextCompaction: { enabled: boolean; strategy: string | null };
  };
  capabilitiesAndTools: {
    tools: TechDocToolEntry[];
    unresolvedToolIds: string[];
    builtInTools: TechDocBuiltInToolEntry[];
    canCallAgents: boolean;
    canCreateAgents: boolean;
    pipelineSummary: {
      nodeCount: number;
      edgeCount: number;
      nodeTypes: Record<string, number>;
    } | null;
    collaboration: { strategy: string; agentCount: number } | null;
  };
  humanOversight: {
    approvalGate: {
      requestApprovalToolAvailable: boolean;
      note: string;
    };
    approvalHistory: {
      total: number;
      pending: number;
      approved: number;
      rejected: number;
      expired: number;
    };
    constraints: {
      promptInjectionEnabled: boolean;
      autoLearnEnabled: boolean;
      total: number;
      active: number;
      rules: Array<{ rule: string; origin: string; active: boolean; createdAt: Date }>;
    };
    verification: {
      enabled: boolean;
      policy: string | null;
      triggers: string[] | null;
      checkerCount: number;
      pipelineVerifyNodes: number;
    };
  };
  dataGovernance: {
    memory: { enabled: boolean; autoSave: boolean; scopes: string[] };
    fileAttachments: { count: number };
    inputs: {
      webhook: { configured: boolean };
      schedule: { enabled: boolean; intervalMinutes: number | null };
      heartbeat: { enabled: boolean; intervalMinutes: number | null };
    };
  };
  loggingAndTraceability: {
    executions: {
      total: number;
      successful: number;
      successRatePercent: number;
      averageExecutionTimeMs: number;
      totalCostUsd: number;
      lastExecutedAt: Date | null;
    };
    autonomousRuns: { total: number };
    auditLog: { available: boolean; endpoint: string };
    entityVersioning: { available: boolean; mechanism: string; note: string };
  };
  changeHistory: Array<{
    version: string;
    savedAt: string;
    changelog: string;
    nodeCount: number;
  }>;
  disclaimer: string;
}

const DISCLAIMER =
  'This document was machine-generated by almyty from the agent configuration and ' +
  'operational records at the time of export. It is an informative aid mapped to the ' +
  'structure of EU AI Act Annex IV; it is not a conformity assessment. The deployer ' +
  'remains responsible for their own risk classification, conformity assessment, and ' +
  'any legally required technical documentation.';

const CHANGE_HISTORY_LIMIT = 10;

/**
 * Assembles an EU AI Act Annex-IV-style technical documentation export
 * ("agent card") for a single agent, reusing what almyty already knows:
 * model/provider config, tools, constraints, memory config, oversight
 * (request_approval + approvals history), schedule/webhook inputs and
 * version history. Also renders the same data as Markdown.
 */
@Injectable()
export class AgentTechDocHelper {
  constructor(
    private readonly agentsService: AgentsService,
    private readonly constraintsService: AgentConstraintsService,
    @InjectRepository(Tool)
    private readonly toolRepository: Repository<Tool>,
    @InjectRepository(LlmProvider)
    private readonly llmProviderRepository: Repository<LlmProvider>,
    @InjectRepository(Organization)
    private readonly organizationRepository: Repository<Organization>,
    @InjectRepository(AgentRun)
    private readonly runRepository: Repository<AgentRun>,
    @InjectRepository(ApprovalRequest)
    private readonly approvalRepository: Repository<ApprovalRequest>,
    @InjectRepository(AgentFile)
    private readonly fileRepository: Repository<AgentFile>,
  ) {}

  async build(agentId: string, organizationId: string): Promise<AgentTechnicalDocumentation> {
    // Throws NotFoundException (404) for missing agents — reuse the canonical lookup.
    const agent = await this.agentsService.getAgent(agentId, organizationId);
    const organization = await this.organizationRepository.findOne({ where: { id: organizationId } });

    const nodes: AgentPipelineNode[] = agent.pipeline?.nodes ?? [];
    const edges = agent.pipeline?.edges ?? [];

    const modelEntries = this.collectModelEntries(agent, nodes);
    await this.resolveProviders(modelEntries, organizationId);

    const { tools, unresolvedToolIds } = await this.collectTools(agent, nodes, organizationId);

    const [approvalCounts, constraints, runCount, fileCount] = await Promise.all([
      this.countApprovals(agentId, organizationId),
      this.constraintsService.list(organizationId, agentId),
      this.runRepository.count({ where: { agentId, organizationId } }),
      this.fileRepository.count({ where: { agentId, organizationId } }),
    ]);

    const isAutonomous = agent.mode === 'autonomous';
    const verify = agent.agentConfig?.verify;
    const pipelineVerifyNodes = nodes.filter((n) => n.type === 'verify').length;
    const schedule = agent.settings?.schedule as
      | { enabled?: boolean; intervalMinutes?: number }
      | undefined;

    const nodeTypes: Record<string, number> = {};
    for (const node of nodes) {
      nodeTypes[node.type] = (nodeTypes[node.type] ?? 0) + 1;
    }

    const versions = (agent.metadata?.versions ?? []) as Array<{
      version: string;
      savedAt: string;
      changelog: string;
      pipeline?: { nodes?: unknown[] };
    }>;

    const providers = [
      ...new Map(
        modelEntries
          .filter((e) => e.providerId && e.providerName)
          .map((e) => [
            e.providerId as string,
            { id: e.providerId as string, name: e.providerName as string, type: e.providerType ?? 'unknown' },
          ]),
      ).values(),
    ];

    return {
      documentType: 'agent-technical-documentation',
      standard: 'EU AI Act Annex IV (informative mapping)',
      generatedAt: new Date().toISOString(),

      generalDescription: {
        id: agent.id,
        name: agent.name,
        description: agent.description ?? null,
        purpose: agent.instructions || agent.description || null,
        mode: agent.mode,
        status: agent.status,
        version: agent.version,
        organization: { id: organizationId, name: organization?.name ?? null },
        visibility: agent.visibility ?? null,
        createdAt: agent.createdAt ?? null,
        updatedAt: agent.updatedAt ?? null,
      },

      modelAndProviders: {
        models: modelEntries,
        providers,
        contextCompaction: {
          enabled: !!agent.modelConfig?.compaction?.enabled,
          strategy: agent.modelConfig?.compaction?.strategy ?? null,
        },
      },

      capabilitiesAndTools: {
        tools,
        unresolvedToolIds,
        builtInTools: this.collectBuiltInTools(agent),
        canCallAgents: !!agent.agentConfig?.canCallAgents,
        canCreateAgents: !!agent.agentConfig?.canCreateAgents,
        pipelineSummary: isAutonomous
          ? null
          : { nodeCount: nodes.length, edgeCount: edges.length, nodeTypes },
        collaboration: agent.collaboration?.strategy
          ? {
              strategy: agent.collaboration.strategy,
              agentCount: agent.collaboration.agents?.length ?? 0,
            }
          : null,
      },

      humanOversight: {
        approvalGate: {
          requestApprovalToolAvailable: isAutonomous,
          note: isAutonomous
            ? 'The built-in request_approval tool pauses the run (WAITING_APPROVAL) until an authorized user approves or rejects. Rejection cancels the run.'
            : 'Workflow (pipeline) agents execute a fixed DAG; the request_approval built-in tool is only injected into autonomous runs.',
        },
        approvalHistory: approvalCounts,
        constraints: {
          promptInjectionEnabled: !!agent.agentConfig?.constraints?.enabled,
          autoLearnEnabled: !!agent.agentConfig?.constraints?.autoLearn,
          total: constraints.length,
          active: constraints.filter((c) => c.active).length,
          rules: constraints.map((c) => ({
            rule: c.rule,
            origin: c.origin,
            active: c.active,
            createdAt: c.createdAt,
          })),
        },
        verification: {
          enabled: !!verify?.enabled || pipelineVerifyNodes > 0,
          policy: verify?.policy ?? null,
          triggers: verify?.triggers ?? null,
          checkerCount: this.collectVerifyCheckers(agent, nodes).length,
          pipelineVerifyNodes,
        },
      },

      dataGovernance: {
        memory: {
          enabled: !!agent.memoryConfig?.enabled,
          autoSave: !!agent.memoryConfig?.autoSave,
          scopes: agent.memoryConfig?.scopes ?? [],
        },
        fileAttachments: { count: fileCount },
        inputs: {
          webhook: { configured: !!agent.webhookUrl },
          schedule: {
            enabled: !!schedule?.enabled,
            intervalMinutes: schedule?.intervalMinutes ?? null,
          },
          heartbeat: {
            enabled: !!agent.heartbeat?.enabled,
            intervalMinutes: agent.heartbeat?.intervalMinutes ?? null,
          },
        },
      },

      loggingAndTraceability: {
        executions: {
          total: agent.totalExecutions ?? 0,
          successful: agent.successfulExecutions ?? 0,
          successRatePercent: agent.totalExecutions
            ? Math.round(((agent.successfulExecutions ?? 0) / agent.totalExecutions) * 1000) / 10
            : 0,
          averageExecutionTimeMs: agent.averageExecutionTime ?? 0,
          totalCostUsd: agent.totalCost ?? 0,
          lastExecutedAt: agent.lastExecutedAt ?? null,
        },
        autonomousRuns: { total: runCount },
        auditLog: {
          available: true,
          endpoint: `/agents/${agent.id}/audit-log`,
        },
        entityVersioning: {
          available: true,
          mechanism: 'typeorm-versions',
          note: 'Every create/update/delete of the agent entity is snapshotted automatically and retrievable via the versions API.',
        },
      },

      changeHistory: versions
        .slice(-CHANGE_HISTORY_LIMIT)
        .reverse()
        .map((v) => ({
          version: v.version,
          savedAt: v.savedAt,
          changelog: v.changelog,
          nodeCount: v.pipeline?.nodes?.length ?? 0,
        })),

      disclaimer: DISCLAIMER,
    };
  }

  /** Render the structured document as human-readable Markdown. */
  renderMarkdown(doc: AgentTechnicalDocumentation): string {
    const g = doc.generalDescription;
    const lines: string[] = [];
    const fmt = (v: unknown): string => {
      if (v === null || v === undefined || v === '') return '—';
      if (v instanceof Date) return v.toISOString();
      return String(v);
    };

    lines.push(`# Technical Documentation: ${g.name}`);
    lines.push('');
    lines.push(`_${doc.standard}. Generated ${doc.generatedAt} by almyty._`);
    lines.push('');

    lines.push('## 1. General Description');
    lines.push('');
    lines.push(`- **Agent ID**: ${g.id}`);
    lines.push(`- **Name**: ${g.name}`);
    lines.push(`- **Description**: ${fmt(g.description)}`);
    lines.push(`- **Intended purpose**: ${fmt(g.purpose)}`);
    lines.push(`- **Mode**: ${g.mode}`);
    lines.push(`- **Status**: ${g.status}`);
    lines.push(`- **Current version**: ${g.version}`);
    lines.push(`- **Organization**: ${fmt(g.organization.name)} (${g.organization.id})`);
    lines.push(`- **Created**: ${fmt(g.createdAt)}`);
    lines.push(`- **Last updated**: ${fmt(g.updatedAt)}`);
    lines.push('');

    lines.push('## 2. Models and Providers');
    lines.push('');
    if (doc.modelAndProviders.models.length === 0) {
      lines.push('No LLM model configuration found on this agent.');
    } else {
      lines.push('| Source | Provider | Type | Model | Temperature | Max tokens |');
      lines.push('|---|---|---|---|---|---|');
      for (const m of doc.modelAndProviders.models) {
        lines.push(
          `| ${m.source} | ${fmt(m.providerName)} | ${fmt(m.providerType)} | ${fmt(m.model)} | ${fmt(m.temperature)} | ${fmt(m.maxTokens)} |`,
        );
      }
    }
    lines.push('');
    lines.push(
      `Context compaction: ${doc.modelAndProviders.contextCompaction.enabled ? `enabled (${fmt(doc.modelAndProviders.contextCompaction.strategy)})` : 'disabled'}.`,
    );
    lines.push('');

    const c = doc.capabilitiesAndTools;
    lines.push('## 3. Capabilities and Tools');
    lines.push('');
    if (c.tools.length === 0) {
      lines.push('No user-defined tools are attached to this agent.');
    } else {
      lines.push('| Tool | Type | API source | Description | Referenced by |');
      lines.push('|---|---|---|---|---|');
      for (const t of c.tools) {
        lines.push(
          `| ${fmt(t.name)} | ${fmt(t.type)} | ${fmt(t.apiSource)} | ${fmt(t.description)} | ${t.referencedBy.join('; ')} |`,
        );
      }
    }
    if (c.unresolvedToolIds.length > 0) {
      lines.push('');
      lines.push(`Unresolved tool references (deleted or inaccessible): ${c.unresolvedToolIds.join(', ')}`);
    }
    lines.push('');
    if (c.builtInTools.length > 0) {
      lines.push('Built-in tools:');
      lines.push('');
      for (const b of c.builtInTools) {
        lines.push(`- **${b.name}**: ${b.description}`);
      }
      lines.push('');
    }
    lines.push(`- Can invoke other agents: ${c.canCallAgents ? 'yes' : 'no'}`);
    lines.push(`- Can create temporary agents: ${c.canCreateAgents ? 'yes' : 'no'}`);
    if (c.pipelineSummary) {
      const types = Object.entries(c.pipelineSummary.nodeTypes)
        .map(([k, v]) => `${k} ×${v}`)
        .join(', ');
      lines.push(
        `- Pipeline: ${c.pipelineSummary.nodeCount} nodes, ${c.pipelineSummary.edgeCount} edges (${types || 'empty'})`,
      );
    }
    if (c.collaboration) {
      lines.push(`- Collaboration: ${c.collaboration.strategy} with ${c.collaboration.agentCount} agents`);
    }
    lines.push('');

    const h = doc.humanOversight;
    lines.push('## 4. Human Oversight');
    lines.push('');
    lines.push(
      `- request_approval tool available: ${h.approvalGate.requestApprovalToolAvailable ? 'yes' : 'no'}`,
    );
    lines.push(`- ${h.approvalGate.note}`);
    lines.push(
      `- Approval history: ${h.approvalHistory.total} total (${h.approvalHistory.approved} approved, ${h.approvalHistory.rejected} rejected, ${h.approvalHistory.pending} pending, ${h.approvalHistory.expired} expired)`,
    );
    lines.push(
      `- Constraints: ${h.constraints.active} active of ${h.constraints.total} (prompt injection ${h.constraints.promptInjectionEnabled ? 'on' : 'off'}, auto-learn ${h.constraints.autoLearnEnabled ? 'on' : 'off'})`,
    );
    for (const r of h.constraints.rules.filter((x) => x.active)) {
      lines.push(`  - [${r.origin}] ${r.rule}`);
    }
    lines.push(
      `- Verification: ${h.verification.enabled ? 'enabled' : 'disabled'}${h.verification.policy ? ` (policy: ${h.verification.policy})` : ''}, ${h.verification.checkerCount} checkers, ${h.verification.pipelineVerifyNodes} pipeline verify nodes`,
    );
    lines.push('');

    const d = doc.dataGovernance;
    lines.push('## 5. Data Governance');
    lines.push('');
    lines.push(
      `- Long-term memory: ${d.memory.enabled ? 'enabled' : 'disabled'}${d.memory.enabled ? ` (auto-save ${d.memory.autoSave ? 'on' : 'off'}${d.memory.scopes.length ? `, scopes: ${d.memory.scopes.join(', ')}` : ''})` : ''}`,
    );
    lines.push(`- File attachments: ${d.fileAttachments.count}`);
    lines.push(`- Webhook trigger: ${d.inputs.webhook.configured ? 'configured' : 'not configured'}`);
    lines.push(
      `- Schedule: ${d.inputs.schedule.enabled ? `every ${d.inputs.schedule.intervalMinutes} minutes` : 'disabled'}`,
    );
    lines.push(
      `- Heartbeat: ${d.inputs.heartbeat.enabled ? `every ${d.inputs.heartbeat.intervalMinutes} minutes` : 'disabled'}`,
    );
    lines.push('');

    const l = doc.loggingAndTraceability;
    lines.push('## 6. Logging and Traceability');
    lines.push('');
    lines.push(
      `- Pipeline executions: ${l.executions.total} total, ${l.executions.successful} successful (${l.executions.successRatePercent}% success rate)`,
    );
    lines.push(`- Autonomous runs: ${l.autonomousRuns.total}`);
    lines.push(`- Average execution time: ${l.executions.averageExecutionTimeMs} ms`);
    lines.push(`- Accumulated cost: $${l.executions.totalCostUsd}`);
    lines.push(`- Last executed: ${fmt(l.executions.lastExecutedAt)}`);
    lines.push(`- Audit log: available at \`${l.auditLog.endpoint}\``);
    lines.push(`- Entity versioning: ${l.entityVersioning.mechanism} — ${l.entityVersioning.note}`);
    lines.push('');

    lines.push('## 7. Change History');
    lines.push('');
    if (doc.changeHistory.length === 0) {
      lines.push('No saved version snapshots.');
    } else {
      lines.push('| Version | Saved at | Changelog | Pipeline nodes |');
      lines.push('|---|---|---|---|');
      for (const v of doc.changeHistory) {
        lines.push(`| ${v.version} | ${v.savedAt} | ${fmt(v.changelog)} | ${v.nodeCount} |`);
      }
    }
    lines.push('');

    lines.push('## Disclaimer');
    lines.push('');
    lines.push(doc.disclaimer);
    lines.push('');

    return lines.join('\n');
  }

  // ── Internals ──

  private nodeConfig(node: AgentPipelineNode): Record<string, any> {
    return node.data || node.config || {};
  }

  private collectModelEntries(agent: Agent, nodes: AgentPipelineNode[]): TechDocModelEntry[] {
    const entries: TechDocModelEntry[] = [];
    const push = (source: string, cfg: { providerId?: string; model?: string; temperature?: number; maxTokens?: number }) => {
      entries.push({
        source,
        providerId: cfg.providerId ?? null,
        providerName: null,
        providerType: null,
        model: cfg.model ?? null,
        temperature: cfg.temperature ?? null,
        maxTokens: cfg.maxTokens ?? null,
      });
    };

    if (agent.modelConfig && (agent.modelConfig.providerId || agent.modelConfig.model)) {
      push('agent config', agent.modelConfig);
    }
    for (const node of nodes.filter((n) => n.type === 'llm_call')) {
      push(`pipeline llm_call node ${node.id}`, this.nodeConfig(node));
    }
    for (const checker of this.collectVerifyCheckers(agent, nodes)) {
      push(`verify checker${checker.name ? ` "${checker.name}"` : ''}`, checker);
    }
    if (agent.modelConfig?.compaction?.enabled && agent.modelConfig.compaction.providerId) {
      push('context compaction', agent.modelConfig.compaction);
    }
    return entries;
  }

  private collectVerifyCheckers(
    agent: Agent,
    nodes: AgentPipelineNode[],
  ): Array<{ name?: string; providerId?: string; model?: string; temperature?: number; maxTokens?: number }> {
    const checkers = [...(agent.agentConfig?.verify?.checkers ?? [])];
    for (const node of nodes.filter((n) => n.type === 'verify')) {
      const cfg = this.nodeConfig(node);
      if (Array.isArray(cfg.checkers)) checkers.push(...cfg.checkers);
    }
    return checkers;
  }

  private async resolveProviders(entries: TechDocModelEntry[], organizationId: string): Promise<void> {
    const ids = [...new Set(entries.map((e) => e.providerId).filter(Boolean))] as string[];
    if (ids.length === 0) return;
    const providers = await this.llmProviderRepository.find({
      where: { id: In(ids), organizationId },
    });
    const byId = new Map(providers.map((p) => [p.id, p]));
    for (const entry of entries) {
      const provider = entry.providerId ? byId.get(entry.providerId) : undefined;
      if (provider) {
        entry.providerName = provider.name;
        entry.providerType = provider.type;
      }
    }
  }

  private async collectTools(
    agent: Agent,
    nodes: AgentPipelineNode[],
    organizationId: string,
  ): Promise<{ tools: TechDocToolEntry[]; unresolvedToolIds: string[] }> {
    const references = new Map<string, string[]>();
    const addRef = (toolId: string, source: string) => {
      if (!toolId) return;
      const existing = references.get(toolId) ?? [];
      if (!existing.includes(source)) existing.push(source);
      references.set(toolId, existing);
    };

    for (const toolId of agent.toolIds ?? []) addRef(toolId, 'agent tool list');
    for (const node of nodes.filter((n) => n.type === 'tool_call')) {
      const cfg = this.nodeConfig(node);
      if (cfg.toolId) addRef(cfg.toolId, `pipeline tool_call node ${node.id}`);
    }
    for (const node of nodes.filter((n) => n.type === 'llm_call')) {
      const cfg = this.nodeConfig(node);
      for (const toolId of cfg.toolIds ?? []) addRef(toolId, `pipeline llm_call node ${node.id}`);
    }

    const toolIds = [...references.keys()];
    const found =
      toolIds.length > 0
        ? await this.toolRepository.find({
            where: { id: In(toolIds), organizationId },
            relations: ['api'],
          })
        : [];
    const foundById = new Map(found.map((t) => [t.id, t]));

    const tools: TechDocToolEntry[] = [];
    const unresolvedToolIds: string[] = [];
    for (const toolId of toolIds) {
      const tool = foundById.get(toolId);
      if (!tool) {
        unresolvedToolIds.push(toolId);
        continue;
      }
      tools.push({
        id: tool.id,
        name: tool.name ?? null,
        type: tool.type ?? null,
        description: tool.description ?? null,
        apiSource: tool.api?.name ?? null,
        referencedBy: references.get(toolId) ?? [],
      });
    }
    return { tools, unresolvedToolIds };
  }

  private collectBuiltInTools(agent: Agent): TechDocBuiltInToolEntry[] {
    // Mirrors AgentRuntimeBuilders.buildToolDefinitions — built-in tools are
    // injected only for autonomous runs.
    if (agent.mode !== 'autonomous') return [];
    const tools: TechDocBuiltInToolEntry[] = [
      { name: BUILT_IN_TOOLS.wait.name, description: BUILT_IN_TOOLS.wait.description },
      { name: BUILT_IN_TOOLS.ask_user.name, description: BUILT_IN_TOOLS.ask_user.description },
      {
        name: BUILT_IN_TOOLS.request_approval.name,
        description: BUILT_IN_TOOLS.request_approval.description,
      },
    ];
    if (agent.memoryConfig?.enabled) {
      tools.push(
        { name: BUILT_IN_TOOLS.store_memory.name, description: BUILT_IN_TOOLS.store_memory.description },
        { name: BUILT_IN_TOOLS.recall_memory.name, description: BUILT_IN_TOOLS.recall_memory.description },
      );
    }
    if (agent.agentConfig?.canCreateAgents) {
      tools.push(
        { name: 'create_agent', description: 'Create a temporary specialist agent for a specific task.' },
        { name: 'invoke_agent', description: 'Run another agent with the given input and wait for its response.' },
      );
    }
    return tools;
  }

  private async countApprovals(
    agentId: string,
    organizationId: string,
  ): Promise<{ total: number; pending: number; approved: number; rejected: number; expired: number }> {
    const statuses: ApprovalStatus[] = ['pending', 'approved', 'rejected', 'expired'];
    const [pending, approved, rejected, expired] = await Promise.all(
      statuses.map((status) =>
        this.approvalRepository.count({ where: { agentId, organizationId, status } }),
      ),
    );
    return { total: pending + approved + rejected + expired, pending, approved, rejected, expired };
  }
}
