apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: almyty-ingress
  namespace: almyty
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.almyty.dev
    secretName: api-apif-ai-tls
  - hosts:
    - app.almyty.dev
    secretName: app-apif-ai-tls
  rules:
  - host: api.almyty.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: almyty-api
            port:
              number: 3000
  - host: app.almyty.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: almyty-frontend
            port:
              number: 8080
