import { Client } from 'pg';

import { ToolGeneratedFlag1750812200000 } from '../../migrations/1750812200000-ToolGeneratedFlag';

/**
 * The migration that takes the 'system' sentinel out of tools."createdBy"
 * and tool_versions."createdBy", run as shipped against a real Postgres,
 * on tables shaped like the ones the initial schema creates (metadata is a
 * `json` column there).
 */
const describeOrSkip = process.env.RUN_DB_INTEGRATION === '1' ? describe : describe.skip;

describeOrSkip('tool generated-flag migration (real Postgres)', () => {
  let db: Client;
  const OWNER = '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d';
  const MEMBER = '1b4e28ba-2fa1-11d2-883f-0016d3cca427';

  beforeAll(async () => {
    db = new Client({
      host: process.env.DATABASE_HOST || 'localhost',
      port: Number(process.env.DATABASE_PORT || 5432),
      user: process.env.DATABASE_USERNAME || 'postgres',
      password: process.env.DATABASE_PASSWORD || 'postgres',
      database: process.env.DATABASE_NAME || 'almyty_test',
    });
    await db.connect();
    await db.query('DROP SCHEMA IF EXISTS toolgenmig CASCADE');
    await db.query('CREATE SCHEMA toolgenmig');
    await db.query('SET search_path TO toolgenmig');
    await db.query(`
      CREATE TABLE tools (
        "id" text PRIMARY KEY,
        "metadata" json,
        "createdBy" character varying
      )`);
    await db.query(`
      CREATE TABLE tool_versions (
        "id" text PRIMARY KEY,
        "createdBy" character varying
      )`);
  }, 30_000);

  afterAll(async () => {
    await db.query('DROP SCHEMA IF EXISTS toolgenmig CASCADE');
    await db.end();
  });

  it("flags every generated tool and replaces the 'system' creator with null", async () => {
    await db.query(
      `INSERT INTO tools ("id", "metadata", "createdBy") VALUES
        ('generated-system', '{"autoGenerated": true}', 'system'),
        ('system-no-metadata', NULL, 'system'),
        ('generated-private-api', '{"autoGenerated": true}', $1),
        ('mcp-source', '{"autoGenerated": true, "mcpSource": {"id": "s"}}', $2),
        ('handmade', '{"note": "x"}', $2),
        ('handmade-unowned', NULL, NULL)`,
      [OWNER, MEMBER],
    );
    await db.query(
      `INSERT INTO tool_versions ("id", "createdBy") VALUES ('v-system', 'system'), ('v-member', $1), ('v-none', NULL)`,
      [MEMBER],
    );

    const migration = new ToolGeneratedFlag1750812200000();
    const runner = { query: (sql: string) => db.query(sql) } as any;
    await migration.up(runner);
    // Idempotent: a second run changes nothing.
    await migration.up(runner);

    const { rows } = await db.query(`SELECT "id", "createdBy", "generated" FROM tools ORDER BY "id"`);
    expect(Object.fromEntries(rows.map((r) => [r.id, [r.createdBy, r.generated]]))).toEqual({
      'generated-system': [null, true],
      'system-no-metadata': [null, true],
      'generated-private-api': [OWNER, true],
      'mcp-source': [MEMBER, true],
      handmade: [MEMBER, false],
      'handmade-unowned': [null, false],
    });
    const versions = await db.query(`SELECT "id", "createdBy" FROM tool_versions ORDER BY "id"`);
    expect(Object.fromEntries(versions.rows.map((r) => [r.id, r.createdBy]))).toEqual({
      'v-member': MEMBER,
      'v-none': null,
      'v-system': null,
    });

    await migration.down(runner);
    const columns = await db.query(
      `SELECT column_name FROM information_schema.columns WHERE table_schema = 'toolgenmig' AND table_name = 'tools'`,
    );
    expect(columns.rows.map((r) => r.column_name)).not.toContain('generated');
  });
});
