import { Test, TestingModule } from '@nestjs/testing';
import { HttpException, HttpStatus } from '@nestjs/common';
import { UtcpController } from './utcp.controller';
import { UtcpService } from '../utcp.service';

describe('UtcpController', () => {
  let controller: UtcpController;
  let utcpService: jest.Mocked<UtcpService>;

  const mockManual = {
    version: '1.0',
    info: { title: 'Test Manual', version: '1.0.0' },
    tools: [
      {
        id: 'tool-1',
        name: 'Test Tool',
        description: 'A test tool',
        version: '1.0.0',
        inputSchema: { type: 'object' },
        metadata: { autoGenerated: true }
      },
      {
        id: 'tool-2',
        name: 'Manual Tool',
        description: 'A manual tool',
        version: '1.0.0',
        inputSchema: { type: 'object' },
        metadata: { autoGenerated: false }
      },
    ],
    callTemplates: [
      {
        id: 'template-1',
        name: 'Test Template',
        protocol: 'http' as const,
        endpoint: { url: 'https://api.example.com' },
        requestMapping: { parameters: {} },
        responseMapping: { successCodes: [200] },
      }
    ],
    authentication: [{ type: 'api_key', scheme: 'api_key' }],
    metadata: { generatedAt: '2025-10-09T00:00:00Z' },
  } as any;

  beforeEach(async () => {
    const mockUtcpService: any = {
      generateManual: jest.fn(),
      executeUtcpTool: jest.fn(),
      validateManual: jest.fn(),
      getToolManual: jest.fn(),
      getDiscoveryInfo: jest.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      controllers: [UtcpController],
      providers: [
        {
          provide: UtcpService,
          useValue: mockUtcpService,
        },
      ],
    }).compile();

    controller = module.get<UtcpController>(UtcpController);
    utcpService = module.get(UtcpService);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('discovery', () => {
    it('should return global discovery info', async () => {
      const discoveryInfo = {
        name: 'apifai UTCP Server',
        version: '1.0.0',
        capabilities: ['manual-generation', 'direct-calling'],
      } as any;
      (utcpService.getDiscoveryInfo as jest.Mock).mockResolvedValue(discoveryInfo);

      const result = await controller.discovery();

      expect(result).toEqual(discoveryInfo);
      expect(utcpService.getDiscoveryInfo).toHaveBeenCalledWith('global');
    });
  });

  describe('organizationDiscovery', () => {
    it('should return organization-specific discovery info', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-1' } };
      const discoveryInfo = {
        name: 'Org 1 UTCP',
        version: '1.0.0',
        capabilities: ['manual-generation'],
      } as any;
      (utcpService.getDiscoveryInfo as jest.Mock).mockResolvedValue(discoveryInfo);

      const result = await controller.organizationDiscovery('org-1', mockRequest);

      expect(result).toEqual(discoveryInfo);
      expect(utcpService.getDiscoveryInfo).toHaveBeenCalledWith('org-1');
    });

    it('should throw 403 if user does not have access to organization', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-2' } };

      await expect(
        controller.organizationDiscovery('org-1', mockRequest)
      ).rejects.toThrow(HttpException);
    });
  });

  describe('getManual', () => {
    it('should generate and return UTCP manual', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-1' } };
      utcpService.generateManual.mockResolvedValue(mockManual);

      const result = await controller.getManual('org-1', mockRequest);

      expect(result).toEqual(mockManual);
      expect(utcpService.generateManual).toHaveBeenCalledWith('org-1');
    });

    it('should throw 403 if user does not have access', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-2' } };

      await expect(
        controller.getManual('org-1', mockRequest)
      ).rejects.toThrow(HttpException);
    });
  });

  describe('getToolManual', () => {
    it('should return manual for specific tool', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-1' } };
      const toolManual = {
        id: 'tool-1',
        name: 'Test Tool',
        description: 'Tool description',
        version: '1.0.0',
        inputSchema: { type: 'object' }
      };
      utcpService.getToolManual.mockResolvedValue(toolManual as any);

      const result = await controller.getToolManual('org-1', 'tool-1', mockRequest);

      expect(result).toEqual(toolManual);
      expect(utcpService.getToolManual).toHaveBeenCalledWith('tool-1', 'org-1');
    });

    it('should throw 403 if user does not have access', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-2' } };

      await expect(
        controller.getToolManual('org-1', 'tool-1', mockRequest)
      ).rejects.toThrow(HttpException);
    });
  });

  describe('executeUtcpTool', () => {
    it('should execute UTCP tool in proxy mode', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-1' } };
      const context = {
        toolId: 'tool-1',
        callTemplateId: 'template-1',
        parameters: { input: 'test' }
      };
      const executionResult = {
        success: true,
        data: { output: 'result' },
        metadata: {
          executionTime: 100,
          toolId: 'tool-1',
          callTemplateId: 'template-1',
          requestId: 'req-1',
          timestamp: '2025-10-09T00:00:00Z'
        }
      };
      utcpService.executeUtcpTool.mockResolvedValue(executionResult);

      const result = await controller.executeUtcpTool('org-1', context, mockRequest);

      expect(result).toEqual(executionResult);
      expect(utcpService.executeUtcpTool).toHaveBeenCalledWith(context, 'org-1');
    });

    it('should throw 403 if user does not have access', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-2' } };
      const context = {
        toolId: 'tool-1',
        callTemplateId: 'template-1',
        parameters: {}
      };

      await expect(
        controller.executeUtcpTool('org-1', context, mockRequest)
      ).rejects.toThrow(HttpException);
    });
  });

  describe('validateManual', () => {
    it('should validate UTCP manual successfully', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-1' } };
      utcpService.validateManual.mockResolvedValue({
        isValid: true,
        errors: [],
        warnings: [],
      });

      const result = await controller.validateManual('org-1', mockManual, mockRequest);

      expect(result.isValid).toBe(true);
      expect(result.errors).toEqual([]);
      expect(utcpService.validateManual).toHaveBeenCalledWith(mockManual);
    });

    it('should return validation errors', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-1' } };
      utcpService.validateManual.mockResolvedValue({
        isValid: false,
        errors: ['Invalid tool schema'],
        warnings: ['Deprecated field used'],
      });

      const result = await controller.validateManual('org-1', mockManual, mockRequest);

      expect(result.isValid).toBe(false);
      expect(result.errors).toContain('Invalid tool schema');
      expect(result.warnings).toContain('Deprecated field used');
    });

    it('should throw 403 if user does not have access', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-2' } };

      await expect(
        controller.validateManual('org-1', mockManual, mockRequest)
      ).rejects.toThrow(HttpException);
    });
  });

  describe('getCapabilities', () => {
    it('should return UTCP capabilities', async () => {
      const result = await controller.getCapabilities();

      expect(result).toEqual({
        protocol: 'utcp',
        version: '1.0.0',
        server: 'apifai',
        capabilities: expect.objectContaining({
          manualGeneration: true,
          directCalling: true,
          proxyMode: true,
        }),
        features: expect.objectContaining({
          manualGeneration: true,
          directCalling: true,
          autoToolGeneration: true,
        }),
      });
    });
  });

  describe('health', () => {
    it('should return UTCP health status', async () => {
      const result = await controller.health();

      expect(result).toEqual({
        protocol: 'utcp',
        status: 'healthy',
        server: 'apifai',
        version: '1.0.0',
        timestamp: expect.any(String),
        uptime: expect.any(Number),
      });
    });
  });

  describe('exportManual', () => {
    it('should export manual in JSON format', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-1' } };
      utcpService.generateManual.mockResolvedValue(mockManual);

      const result = await controller.exportManual('org-1', 'json', mockRequest);

      expect(result).toEqual(mockManual);
    });

    it('should throw NOT_IMPLEMENTED for YAML export', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-1' } };
      utcpService.generateManual.mockResolvedValue(mockManual);

      await expect(
        controller.exportManual('org-1', 'yaml', mockRequest)
      ).rejects.toThrow(HttpException);
    });

    it('should throw NOT_IMPLEMENTED for markdown export', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-1' } };
      utcpService.generateManual.mockResolvedValue(mockManual);

      await expect(
        controller.exportManual('org-1', 'markdown', mockRequest)
      ).rejects.toThrow(HttpException);
    });

    it('should throw BAD_REQUEST for unsupported format', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-1' } };
      utcpService.generateManual.mockResolvedValue(mockManual);

      await expect(
        controller.exportManual('org-1', 'xml' as any, mockRequest)
      ).rejects.toThrow(HttpException);
    });

    it('should throw 403 if user does not have access', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-2' } };

      await expect(
        controller.exportManual('org-1', 'json', mockRequest)
      ).rejects.toThrow(HttpException);
    });
  });

  describe('getUtcpStats', () => {
    it('should return UTCP usage statistics', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-1' } };
      utcpService.generateManual.mockResolvedValue(mockManual);

      const result = await controller.getUtcpStats('org-1', mockRequest);

      expect(result).toEqual({
        organizationId: 'org-1',
        manual: {
          version: '1.0',
          toolCount: 2,
          callTemplateCount: 1,
          authSchemeCount: 1,
        },
        features: {
          directCalling: 1,
          proxyMode: 2,
          autoGenerated: 1,
        },
        generatedAt: '2025-10-09T00:00:00Z',
      });
    });

    it('should throw 403 if user does not have access', async () => {
      const mockRequest = { user: { currentOrganizationId: 'org-2' } };

      await expect(
        controller.getUtcpStats('org-1', mockRequest)
      ).rejects.toThrow(HttpException);
    });
  });
});