name: Development

on:
  push:
    branches: [development]

permissions:
  contents: read
  packages: write

concurrency:
  group: deploy-development
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: development
      sha: ${{ github.sha }}
      push: true
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
    secrets: inherit
