apiVersion: v1
kind: ConfigMap
metadata:
  name: almyty-config
  namespace: almyty
data:
  CORS_ORIGIN: "https://app.staging.almyty.com"
  CORS_ALLOWED_ORIGINS: "https://app.staging.almyty.com"
  BASE_URL: "https://api.staging.almyty.com"
  HOSTED_CHAT_BASE_DOMAIN: "staging.almyty.com"

